/**
 * locations.js — Base de données des lieux du monde
 * Chaque lieu a : id, name, country, lat, lng, image (Wikimedia Commons), difficulty
 */

export const LOCATIONS = [
  // ── Europe ────────────────────────────────────────────────────────────────
  {
    id: 1,
    name: 'Tour Eiffel',
    country: 'France',
    lat: 48.8584,
    lng: 2.2945,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/600px-Tour_Eiffel_Wikimedia_Commons.jpg',
    difficulty: 'easy',
  },
  {
    id: 2,
    name: 'Colisée',
    country: 'Italie',
    lat: 41.8902,
    lng: 12.4922,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/600px-Colosseo_2020.jpg',
    difficulty: 'easy',
  },
  {
    id: 3,
    name: 'Big Ben',
    country: 'Royaume-Uni',
    lat: 51.5007,
    lng: -0.1246,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Clock_Tower_-_Palace_of_Westminster%2C_London_-_May_2007.jpg/600px-Clock_Tower_-_Palace_of_Westminster%2C_London_-_May_2007.jpg',
    difficulty: 'easy',
  },
  {
    id: 4,
    name: 'Sagrada Família',
    country: 'Espagne',
    lat: 41.4036,
    lng: 2.1744,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Sagrada_Familia_01.jpg/600px-Sagrada_Familia_01.jpg',
    difficulty: 'easy',
  },
  {
    id: 5,
    name: 'Alhambra',
    country: 'Espagne',
    lat: 37.1760,
    lng: -3.5880,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Alhambra_evening_panorama_Mirador_San_Nicolas_sRGB-1.jpg/600px-Alhambra_evening_panorama_Mirador_San_Nicolas_sRGB-1.jpg',
    difficulty: 'medium',
  },
  {
    id: 6,
    name: 'Cathédrale Saint-Basile',
    country: 'Russie',
    lat: 55.7525,
    lng: 37.6231,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Moscow_StBasile.jpg/600px-Moscow_StBasile.jpg',
    difficulty: 'easy',
  },
  {
    id: 7,
    name: 'Stonehenge',
    country: 'Royaume-Uni',
    lat: 51.1789,
    lng: -1.8262,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Stonehenge2007_07_30.jpg/600px-Stonehenge2007_07_30.jpg',
    difficulty: 'medium',
  },
  {
    id: 8,
    name: 'Château de Neuschwanstein',
    country: 'Allemagne',
    lat: 47.5576,
    lng: 10.7498,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Schloss_Neuschwanstein_2013.jpg/600px-Schloss_Neuschwanstein_2013.jpg',
    difficulty: 'medium',
  },
  {
    id: 9,
    name: 'Parthénon',
    country: 'Grèce',
    lat: 37.9715,
    lng: 23.7267,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/The_Parthenon_in_Athens.jpg/600px-The_Parthenon_in_Athens.jpg',
    difficulty: 'easy',
  },
  {
    id: 10,
    name: 'Santorin',
    country: 'Grèce',
    lat: 36.3932,
    lng: 25.4615,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Santorini_in_Greece_1.jpg/600px-Santorini_in_Greece_1.jpg',
    difficulty: 'medium',
  },
  {
    id: 11,
    name: 'Météores',
    country: 'Grèce',
    lat: 39.7218,
    lng: 21.6306,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Meteora_monastery2.jpg/600px-Meteora_monastery2.jpg',
    difficulty: 'hard',
  },
  {
    id: 12,
    name: 'Côte Amalfitaine',
    country: 'Italie',
    lat: 40.6340,
    lng: 14.6027,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Amalfi_Coast.jpg/600px-Amalfi_Coast.jpg',
    difficulty: 'medium',
  },
  {
    id: 13,
    name: 'Lacs de Plitvice',
    country: 'Croatie',
    lat: 44.8654,
    lng: 15.6082,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Plitvice_lakes_below_Novakovića_Brod.jpg/600px-Plitvice_lakes_below_Novakovića_Brod.jpg',
    difficulty: 'hard',
  },
  {
    id: 14,
    name: 'Vieille ville de Dubrovnik',
    country: 'Croatie',
    lat: 42.6507,
    lng: 18.0944,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Dubrovnik_-_Old_City.jpg/600px-Dubrovnik_-_Old_City.jpg',
    difficulty: 'medium',
  },
  {
    id: 15,
    name: 'Hallstatt',
    country: 'Autriche',
    lat: 47.5622,
    lng: 13.6493,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Hallstatt_in_Austria.jpg/600px-Hallstatt_in_Austria.jpg',
    difficulty: 'hard',
  },
  {
    id: 16,
    name: 'Fjord de Geiranger',
    country: 'Norvège',
    lat: 62.1015,
    lng: 7.2031,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Geiranger_fjord%2C_Norway_crop.jpg/600px-Geiranger_fjord%2C_Norway_crop.jpg',
    difficulty: 'hard',
  },

  // ── Asie ─────────────────────────────────────────────────────────────────
  {
    id: 17,
    name: 'Taj Mahal',
    country: 'Inde',
    lat: 27.1751,
    lng: 78.0421,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Taj_Mahal_%28Edited%29.jpeg/600px-Taj_Mahal_%28Edited%29.jpeg',
    difficulty: 'easy',
  },
  {
    id: 18,
    name: 'Grande Muraille de Chine',
    country: 'Chine',
    lat: 40.4319,
    lng: 116.5704,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/600px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg',
    difficulty: 'easy',
  },
  {
    id: 19,
    name: 'Mont Fuji',
    country: 'Japon',
    lat: 35.3606,
    lng: 138.7274,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Fujisan_from_Koyodai.jpg/600px-Fujisan_from_Koyodai.jpg',
    difficulty: 'easy',
  },
  {
    id: 20,
    name: 'Angkor Vat',
    country: 'Cambodge',
    lat: 13.4125,
    lng: 103.8670,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Angkor_Wat%2C_Angkor%2C_Cambodia.jpg/600px-Angkor_Wat%2C_Angkor%2C_Cambodia.jpg',
    difficulty: 'medium',
  },
  {
    id: 21,
    name: 'Palais du Potala',
    country: 'Tibet / Chine',
    lat: 29.6578,
    lng: 91.1175,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Potala_palace_27-june-2009.jpg/600px-Potala_palace_27-june-2009.jpg',
    difficulty: 'medium',
  },
  {
    id: 22,
    name: 'Burj Khalifa',
    country: 'Émirats arabes unis',
    lat: 25.1972,
    lng: 55.2744,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Burj_Khalifa.jpg/600px-Burj_Khalifa.jpg',
    difficulty: 'easy',
  },
  {
    id: 23,
    name: 'Petra',
    country: 'Jordanie',
    lat: 30.3285,
    lng: 35.4444,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Petra_Jordan_BW_21.JPG/600px-Petra_Jordan_BW_21.JPG',
    difficulty: 'medium',
  },
  {
    id: 24,
    name: 'Mosquée Bleue',
    country: 'Turquie',
    lat: 41.0055,
    lng: 28.9768,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Blue_Mosque%2C_Istanbul%2C_Turkey.jpg/600px-Blue_Mosque%2C_Istanbul%2C_Turkey.jpg',
    difficulty: 'medium',
  },
  {
    id: 25,
    name: 'Cappadoce',
    country: 'Turquie',
    lat: 38.6431,
    lng: 34.8292,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Cappadocia_Ballooning.jpg/600px-Cappadocia_Ballooning.jpg',
    difficulty: 'medium',
  },
  {
    id: 26,
    name: 'Baie d\'Hạ Long',
    country: 'Viêt Nam',
    lat: 20.9101,
    lng: 107.1839,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Halong_bay_overview.jpg/600px-Halong_bay_overview.jpg',
    difficulty: 'medium',
  },
  {
    id: 27,
    name: 'Borobudur',
    country: 'Indonésie',
    lat: -7.6079,
    lng: 110.2038,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Borobudur-perfect-when-there-s-no-mist.jpg/600px-Borobudur-perfect-when-there-s-no-mist.jpg',
    difficulty: 'hard',
  },
  {
    id: 28,
    name: 'Pagodes de Bagan',
    country: 'Myanmar',
    lat: 21.1717,
    lng: 94.8585,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Bagan%2C_Myanmar.jpg/600px-Bagan%2C_Myanmar.jpg',
    difficulty: 'hard',
  },
  {
    id: 29,
    name: 'Zhangjiajie',
    country: 'Chine',
    lat: 29.3248,
    lng: 110.4354,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/ZhangJiaJie_3.jpg/600px-ZhangJiaJie_3.jpg',
    difficulty: 'hard',
  },

  // ── Afrique ───────────────────────────────────────────────────────────────
  {
    id: 30,
    name: 'Pyramides de Gizeh',
    country: 'Égypte',
    lat: 29.9792,
    lng: 31.1342,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kheops-Pyramid.jpg/600px-Kheops-Pyramid.jpg',
    difficulty: 'easy',
  },
  {
    id: 31,
    name: 'Abu Simbel',
    country: 'Égypte',
    lat: 22.3372,
    lng: 31.6258,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/ASwan_Abu_Simbel1.jpg/600px-ASwan_Abu_Simbel1.jpg',
    difficulty: 'medium',
  },
  {
    id: 32,
    name: 'Place Jemaa el-Fna',
    country: 'Maroc',
    lat: 31.6260,
    lng: -7.9892,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Jemaa_el-Fna_square.jpg/600px-Jemaa_el-Fna_square.jpg',
    difficulty: 'medium',
  },
  {
    id: 33,
    name: 'Table Mountain',
    country: 'Afrique du Sud',
    lat: -33.9626,
    lng: 18.4098,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Table_Mountain_DanielaC_01.jpg/600px-Table_Mountain_DanielaC_01.jpg',
    difficulty: 'medium',
  },
  {
    id: 34,
    name: 'Chutes Victoria',
    country: 'Zambie / Zimbabwe',
    lat: -17.9243,
    lng: 25.8572,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Victoria_Falls_Aerial_Dec_2006.jpg/600px-Victoria_Falls_Aerial_Dec_2006.jpg',
    difficulty: 'hard',
  },
  {
    id: 35,
    name: 'Kilimandjaro',
    country: 'Tanzanie',
    lat: -3.0674,
    lng: 37.3556,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Kilimanjaro_Tanzania.jpg/600px-Kilimanjaro_Tanzania.jpg',
    difficulty: 'medium',
  },

  // ── Amériques ─────────────────────────────────────────────────────────────
  {
    id: 36,
    name: 'Statue de la Liberté',
    country: 'États-Unis',
    lat: 40.6892,
    lng: -74.0445,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Statue_of_Liberty_7.jpg/600px-Statue_of_Liberty_7.jpg',
    difficulty: 'easy',
  },
  {
    id: 37,
    name: 'Golden Gate Bridge',
    country: 'États-Unis',
    lat: 37.8199,
    lng: -122.4783,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/GoldenGateBridge-001.jpg/600px-GoldenGateBridge-001.jpg',
    difficulty: 'easy',
  },
  {
    id: 38,
    name: 'Grand Canyon',
    country: 'États-Unis',
    lat: 36.1069,
    lng: -112.1129,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/USA_09847_Grand_Canyon_Luca_Galuzzi_2007.jpg/600px-USA_09847_Grand_Canyon_Luca_Galuzzi_2007.jpg',
    difficulty: 'medium',
  },
  {
    id: 39,
    name: 'Chutes Niagara',
    country: 'Canada / États-Unis',
    lat: 43.0962,
    lng: -79.0377,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Niagara_Falls_in_winter.jpg/600px-Niagara_Falls_in_winter.jpg',
    difficulty: 'medium',
  },
  {
    id: 40,
    name: 'Tour CN',
    country: 'Canada',
    lat: 43.6426,
    lng: -79.3871,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Toronto_-_ON_-_CN_Tower_from_above1.jpg/600px-Toronto_-_ON_-_CN_Tower_from_above1.jpg',
    difficulty: 'medium',
  },
  {
    id: 41,
    name: 'Christ Rédempteur',
    country: 'Brésil',
    lat: -22.9519,
    lng: -43.2105,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Christ_the_Redeemer_-_Christ_Redentor.jpg/600px-Christ_the_Redeemer_-_Christ_Redentor.jpg',
    difficulty: 'easy',
  },
  {
    id: 42,
    name: 'Machu Picchu',
    country: 'Pérou',
    lat: -13.1631,
    lng: -72.5450,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/600px-Machu_Picchu%2C_Peru.jpg',
    difficulty: 'easy',
  },
  {
    id: 43,
    name: 'Chichén Itzá',
    country: 'Mexique',
    lat: 20.6843,
    lng: -88.5678,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Chichen_Itza_3.jpg/600px-Chichen_Itza_3.jpg',
    difficulty: 'medium',
  },
  {
    id: 44,
    name: 'Chutes d\'Iguazú',
    country: 'Argentine / Brésil',
    lat: -25.6953,
    lng: -54.4367,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/IguazuFalls_Panorama.jpg/600px-IguazuFalls_Panorama.jpg',
    difficulty: 'medium',
  },
  {
    id: 45,
    name: 'Statues Moaï',
    country: 'Île de Pâques (Chili)',
    lat: -27.1213,
    lng: -109.3661,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Moai_Rano_raraku.jpg/600px-Moai_Rano_raraku.jpg',
    difficulty: 'hard',
  },

  // ── Océanie ───────────────────────────────────────────────────────────────
  {
    id: 46,
    name: 'Opéra de Sydney',
    country: 'Australie',
    lat: -33.8568,
    lng: 151.2153,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Sydney_Opera_House_Sails.jpg/600px-Sydney_Opera_House_Sails.jpg',
    difficulty: 'easy',
  },
  {
    id: 47,
    name: 'Uluru',
    country: 'Australie',
    lat: -25.3444,
    lng: 131.0369,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Uluru_Australia%2816%29.jpg/600px-Uluru_Australia%2816%29.jpg',
    difficulty: 'medium',
  },
  {
    id: 48,
    name: 'Bora Bora',
    country: 'Polynésie française',
    lat: -16.5004,
    lng: -151.7415,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Bora_Bora_Top.jpg/600px-Bora_Bora_Top.jpg',
    difficulty: 'hard',
  },

  // ── Quelques suppléments variés ──────────────────────────────────────────
  {
    id: 49,
    name: 'Prambanan',
    country: 'Indonésie',
    lat: -7.7521,
    lng: 110.4914,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Candi_Prambanan.jpg/600px-Candi_Prambanan.jpg',
    difficulty: 'hard',
  },
  {
    id: 50,
    name: 'Mont Saint-Michel',
    country: 'France',
    lat: 48.6361,
    lng: -1.5115,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Mont_Saint-Michel_3%2C_Brittany%2C_France_-_July_2011.jpg/600px-Mont_Saint-Michel_3%2C_Brittany%2C_France_-_July_2011.jpg',
    difficulty: 'medium',
  },
];

/**
 * Retourne N lieux aléatoires et uniques.
 * @param {number} n
 * @returns {object[]}
 */
export function pickLocations(n) {
  const arr = [...LOCATIONS];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, Math.min(n, arr.length));
}
