/**
 * locations.js — Base de données des lieux du monde
 * Chaque lieu a : id, name, country, region, lat, lng, difficulty
 * (les images Street View sont chargées dynamiquement via Mapillary)
 */

/** Régions disponibles (valeur = clé de filtre, label affiché dans l'UI). */
export const REGIONS = {
  monde:     '🌍 Monde entier',
  europe:    '🇪🇺 Europe',
  asie:      '🌏 Asie',
  afrique:   '🌍 Afrique',
  ameriques: '🌎 Amériques',
  oceanie:   '🦘 Océanie',
};

export const LOCATIONS = [
  // ── Europe ────────────────────────────────────────────────────────────────
  {
    id: 1,
    name: 'Tour Eiffel',
    country: 'France',
    region: 'europe',
    lat: 48.8584,
    lng: 2.2945,
    difficulty: 'easy',
  },
  {
    id: 2,
    name: 'Colisée',
    country: 'Italie',
    region: 'europe',
    lat: 41.8902,
    lng: 12.4922,
    difficulty: 'easy',
  },
  {
    id: 3,
    name: 'Big Ben',
    country: 'Royaume-Uni',
    region: 'europe',
    lat: 51.5007,
    lng: -0.1246,
    difficulty: 'easy',
  },
  {
    id: 4,
    name: 'Sagrada Família',
    country: 'Espagne',
    region: 'europe',
    lat: 41.4036,
    lng: 2.1744,
    difficulty: 'easy',
  },
  {
    id: 5,
    name: 'Alhambra',
    country: 'Espagne',
    region: 'europe',
    lat: 37.1760,
    lng: -3.5880,
    difficulty: 'medium',
  },
  {
    id: 6,
    name: 'Cathédrale Saint-Basile',
    country: 'Russie',
    region: 'europe',
    lat: 55.7525,
    lng: 37.6231,
    difficulty: 'easy',
  },
  {
    id: 7,
    name: 'Stonehenge',
    country: 'Royaume-Uni',
    region: 'europe',
    lat: 51.1789,
    lng: -1.8262,
    difficulty: 'medium',
  },
  {
    id: 8,
    name: 'Château de Neuschwanstein',
    country: 'Allemagne',
    region: 'europe',
    lat: 47.5576,
    lng: 10.7498,
    difficulty: 'medium',
  },
  {
    id: 9,
    name: 'Parthénon',
    country: 'Grèce',
    region: 'europe',
    lat: 37.9715,
    lng: 23.7267,
    difficulty: 'easy',
  },
  {
    id: 10,
    name: 'Santorin',
    country: 'Grèce',
    region: 'europe',
    lat: 36.3932,
    lng: 25.4615,
    difficulty: 'medium',
  },
  {
    id: 11,
    name: 'Météores',
    country: 'Grèce',
    region: 'europe',
    lat: 39.7218,
    lng: 21.6306,
    difficulty: 'hard',
  },
  {
    id: 12,
    name: 'Côte Amalfitaine',
    country: 'Italie',
    region: 'europe',
    lat: 40.6340,
    lng: 14.6027,
    difficulty: 'medium',
  },
  {
    id: 13,
    name: 'Lacs de Plitvice',
    country: 'Croatie',
    region: 'europe',
    lat: 44.8654,
    lng: 15.6082,
    difficulty: 'hard',
  },
  {
    id: 14,
    name: 'Vieille ville de Dubrovnik',
    country: 'Croatie',
    region: 'europe',
    lat: 42.6507,
    lng: 18.0944,
    difficulty: 'medium',
  },
  {
    id: 15,
    name: 'Hallstatt',
    country: 'Autriche',
    region: 'europe',
    lat: 47.5622,
    lng: 13.6493,
    difficulty: 'hard',
  },
  {
    id: 16,
    name: 'Fjord de Geiranger',
    country: 'Norvège',
    region: 'europe',
    lat: 62.1015,
    lng: 7.2031,
    difficulty: 'hard',
  },

  // ── Asie ─────────────────────────────────────────────────────────────────
  {
    id: 17,
    name: 'Taj Mahal',
    country: 'Inde',
    region: 'asie',
    lat: 27.1751,
    lng: 78.0421,
    difficulty: 'easy',
  },
  {
    id: 18,
    name: 'Grande Muraille de Chine',
    country: 'Chine',
    region: 'asie',
    lat: 40.4319,
    lng: 116.5704,
    difficulty: 'easy',
  },
  {
    id: 19,
    name: 'Mont Fuji',
    country: 'Japon',
    region: 'asie',
    lat: 35.3606,
    lng: 138.7274,
    difficulty: 'easy',
  },
  {
    id: 20,
    name: 'Angkor Vat',
    country: 'Cambodge',
    region: 'asie',
    lat: 13.4125,
    lng: 103.8670,
    difficulty: 'medium',
  },
  {
    id: 21,
    name: 'Palais du Potala',
    country: 'Tibet / Chine',
    region: 'asie',
    lat: 29.6578,
    lng: 91.1175,
    difficulty: 'medium',
  },
  {
    id: 22,
    name: 'Burj Khalifa',
    country: 'Émirats arabes unis',
    region: 'asie',
    lat: 25.1972,
    lng: 55.2744,
    difficulty: 'easy',
  },
  {
    id: 23,
    name: 'Petra',
    country: 'Jordanie',
    region: 'asie',
    lat: 30.3285,
    lng: 35.4444,
    difficulty: 'medium',
  },
  {
    id: 24,
    name: 'Mosquée Bleue',
    country: 'Turquie',
    region: 'asie',
    lat: 41.0055,
    lng: 28.9768,
    difficulty: 'medium',
  },
  {
    id: 25,
    name: 'Cappadoce',
    country: 'Turquie',
    region: 'asie',
    lat: 38.6431,
    lng: 34.8292,
    difficulty: 'medium',
  },
  {
    id: 26,
    name: 'Baie d\'Hạ Long',
    country: 'Viêt Nam',
    region: 'asie',
    lat: 20.9101,
    lng: 107.1839,
    difficulty: 'medium',
  },
  {
    id: 27,
    name: 'Borobudur',
    country: 'Indonésie',
    region: 'asie',
    lat: -7.6079,
    lng: 110.2038,
    difficulty: 'hard',
  },
  {
    id: 28,
    name: 'Pagodes de Bagan',
    country: 'Myanmar',
    region: 'asie',
    lat: 21.1717,
    lng: 94.8585,
    difficulty: 'hard',
  },
  {
    id: 29,
    name: 'Zhangjiajie',
    country: 'Chine',
    region: 'asie',
    lat: 29.3248,
    lng: 110.4354,
    difficulty: 'hard',
  },

  // ── Afrique ───────────────────────────────────────────────────────────────
  {
    id: 30,
    name: 'Pyramides de Gizeh',
    country: 'Égypte',
    region: 'afrique',
    lat: 29.9792,
    lng: 31.1342,
    difficulty: 'easy',
  },
  {
    id: 31,
    name: 'Abu Simbel',
    country: 'Égypte',
    region: 'afrique',
    lat: 22.3372,
    lng: 31.6258,
    difficulty: 'medium',
  },
  {
    id: 32,
    name: 'Place Jemaa el-Fna',
    country: 'Maroc',
    region: 'afrique',
    lat: 31.6260,
    lng: -7.9892,
    difficulty: 'medium',
  },
  {
    id: 33,
    name: 'Table Mountain',
    country: 'Afrique du Sud',
    region: 'afrique',
    lat: -33.9626,
    lng: 18.4098,
    difficulty: 'medium',
  },
  {
    id: 34,
    name: 'Chutes Victoria',
    country: 'Zambie / Zimbabwe',
    region: 'afrique',
    lat: -17.9243,
    lng: 25.8572,
    difficulty: 'hard',
  },
  {
    id: 35,
    name: 'Kilimandjaro',
    country: 'Tanzanie',
    region: 'afrique',
    lat: -3.0674,
    lng: 37.3556,
    difficulty: 'medium',
  },

  // ── Amériques ─────────────────────────────────────────────────────────────
  {
    id: 36,
    name: 'Statue de la Liberté',
    country: 'États-Unis',
    region: 'ameriques',
    lat: 40.6892,
    lng: -74.0445,
    difficulty: 'easy',
  },
  {
    id: 37,
    name: 'Golden Gate Bridge',
    country: 'États-Unis',
    region: 'ameriques',
    lat: 37.8199,
    lng: -122.4783,
    difficulty: 'easy',
  },
  {
    id: 38,
    name: 'Grand Canyon',
    country: 'États-Unis',
    region: 'ameriques',
    lat: 36.1069,
    lng: -112.1129,
    difficulty: 'medium',
  },
  {
    id: 39,
    name: 'Chutes Niagara',
    country: 'Canada / États-Unis',
    region: 'ameriques',
    lat: 43.0962,
    lng: -79.0377,
    difficulty: 'medium',
  },
  {
    id: 40,
    name: 'Tour CN',
    country: 'Canada',
    region: 'ameriques',
    lat: 43.6426,
    lng: -79.3871,
    difficulty: 'medium',
  },
  {
    id: 41,
    name: 'Christ Rédempteur',
    country: 'Brésil',
    region: 'ameriques',
    lat: -22.9519,
    lng: -43.2105,
    difficulty: 'easy',
  },
  {
    id: 42,
    name: 'Machu Picchu',
    country: 'Pérou',
    region: 'ameriques',
    lat: -13.1631,
    lng: -72.5450,
    difficulty: 'easy',
  },
  {
    id: 43,
    name: 'Chichén Itzá',
    country: 'Mexique',
    region: 'ameriques',
    lat: 20.6843,
    lng: -88.5678,
    difficulty: 'medium',
  },
  {
    id: 44,
    name: 'Chutes d\'Iguazú',
    country: 'Argentine / Brésil',
    region: 'ameriques',
    lat: -25.6953,
    lng: -54.4367,
    difficulty: 'medium',
  },
  {
    id: 45,
    name: 'Statues Moaï',
    country: 'Île de Pâques (Chili)',
    region: 'oceanie',
    lat: -27.1213,
    lng: -109.3661,
    difficulty: 'hard',
  },

  // ── Océanie ───────────────────────────────────────────────────────────────
  {
    id: 46,
    name: 'Opéra de Sydney',
    country: 'Australie',
    region: 'oceanie',
    lat: -33.8568,
    lng: 151.2153,
    difficulty: 'easy',
  },
  {
    id: 47,
    name: 'Uluru',
    country: 'Australie',
    region: 'oceanie',
    lat: -25.3444,
    lng: 131.0369,
    difficulty: 'medium',
  },
  {
    id: 48,
    name: 'Bora Bora',
    country: 'Polynésie française',
    region: 'oceanie',
    lat: -16.5004,
    lng: -151.7415,
    difficulty: 'hard',
  },

  // ── Quelques suppléments variés ──────────────────────────────────────────
  {
    id: 49,
    name: 'Prambanan',
    country: 'Indonésie',
    region: 'asie',
    lat: -7.7521,
    lng: 110.4914,
    difficulty: 'hard',
  },
  {
    id: 50,
    name: 'Mont Saint-Michel',
    country: 'France',
    region: 'europe',
    lat: 48.6361,
    lng: -1.5115,
    difficulty: 'medium',
  },
];

/**
 * Retourne N lieux aléatoires et uniques, filtrés par région si précisé.
 * @param {number} n
 * @param {string} [region='monde']  clé de région (voir REGIONS), 'monde' = toutes
 * @returns {object[]}
 */
export function pickLocations(n, region = 'monde') {
  const arr = region !== 'monde'
    ? LOCATIONS.filter(l => l.region === region)
    : [...LOCATIONS];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, Math.min(n, arr.length));
}
