// This file is auto-generated by .github/scripts/sync-match3-version.mjs
// It mirrors root /version.js so that Capacitor (webDir: dj-mix) can bundle it.
export const SITE_SEMVER = {
  major: 2,
  minor: 25,
  patch: 0,
  prerelease: '',
  buildDate: '2026-07-31T01:28:50.060Z',
};

export function getVersion() {
  const { major, minor, patch, prerelease } = SITE_SEMVER;
  const base = `${major}.${minor}.${patch}`;
  return prerelease ? `${base}-${prerelease}` : base;
}

export function getBuildDate() {
  return SITE_SEMVER.buildDate || '';
}
