/**
 * questions-data.js — Questions françaises intégrées (~100 questions)
 * Utilisées en fallback si l'API est inaccessible.
 */

export const BUNDLED_QUESTIONS = [
  // ── Histoire ──────────────────────────────────────────────────────────────
  { id: 'h01', category: 'history', difficulty: 'easy',
    text: 'En quelle année a eu lieu la Révolution française ?',
    correctAnswer: '1789', incorrectAnswers: ['1776', '1804', '1815'],
    trivia: 'La prise de la Bastille le 14 juillet 1789 est devenue la Fête nationale française.' },
  { id: 'h02', category: 'history', difficulty: 'easy',
    text: 'Qui était le premier Président de la Ve République française ?',
    correctAnswer: 'Charles de Gaulle', incorrectAnswers: ['Georges Pompidou', 'François Mitterrand', 'Valéry Giscard d\'Estaing'],
    trivia: 'De Gaulle mesurait 1,96 m et s\'est auto-proclamé chef de la France libre depuis Londres en 1940.' },
  { id: 'h03', category: 'history', difficulty: 'easy',
    text: 'En quelle année le mur de Berlin est-il tombé ?',
    correctAnswer: '1989', incorrectAnswers: ['1987', '1991', '1985'],
    trivia: 'Le mur de Berlin mesurait 155 km de long et était gardé par des miradors. Il a été construit en 1961.' },
  { id: 'h04', category: 'history', difficulty: 'easy',
    text: 'Quel roi de France était surnommé "le Roi-Soleil" ?',
    correctAnswer: 'Louis XIV', incorrectAnswers: ['Louis XV', 'Louis XVI', 'François Ier'],
    trivia: 'Louis XIV a régné 72 ans, soit le règne le plus long de l\'histoire des monarchies européennes.' },
  { id: 'h05', category: 'history', difficulty: 'easy',
    text: 'En quelle année Christophe Colomb a-t-il découvert l\'Amérique ?',
    correctAnswer: '1492', incorrectAnswers: ['1488', '1500', '1497'],
    trivia: 'Colomb pensait avoir atteint l\'Asie. Il n\'a jamais su qu\'il avait découvert un nouveau continent.' },
  { id: 'h06', category: 'history', difficulty: 'medium',
    text: 'En quelle année Napoléon Bonaparte a-t-il été exilé à Sainte-Hélène ?',
    correctAnswer: '1815', incorrectAnswers: ['1814', '1821', '1808'],
    trivia: 'Napoléon mourut à Sainte-Hélène en 1821. Son cœur et son estomac furent conservés séparément de son corps.' },
  { id: 'h07', category: 'history', difficulty: 'medium',
    text: 'Quel empire a été le plus grand de l\'histoire par superficie ?',
    correctAnswer: 'L\'empire mongol', incorrectAnswers: ['L\'empire britannique', 'L\'empire romain', 'L\'empire ottoman'],
    trivia: 'L\'empire mongol couvrait 24 millions de km² au XIIIe siècle, reliant l\'Europe à l\'Asie via la Route de la Soie.' },
  { id: 'h08', category: 'history', difficulty: 'easy',
    text: 'Quelle guerre s\'est terminée avec le traité de Versailles en 1919 ?',
    correctAnswer: 'La Première Guerre mondiale', incorrectAnswers: ['La Seconde Guerre mondiale', 'La guerre franco-prussienne', 'La guerre de Crimée'],
    trivia: 'Le traité de Versailles a imposé à l\'Allemagne de payer d\'énormes réparations, semant les graines de la Seconde Guerre mondiale.' },
  { id: 'h09', category: 'history', difficulty: 'medium',
    text: 'Quel pharaon est associé au tombeau découvert en 1922 dans la Vallée des Rois ?',
    correctAnswer: 'Toutankhamon', incorrectAnswers: ['Ramsès II', 'Akhenaton', 'Séti Ier'],
    trivia: 'Toutankhamon est mort à environ 18 ans. Son tombeau recelait plus de 5 000 objets, dont le masque en or massif.' },
  { id: 'h10', category: 'history', difficulty: 'easy',
    text: 'Qui a peint la Joconde ?',
    correctAnswer: 'Léonard de Vinci', incorrectAnswers: ['Michel-Ange', 'Raphaël', 'Botticelli'],
    trivia: 'La Joconde a été peinte entre 1503 et 1519 et représenterait Lisa Gherardini, épouse d\'un marchand florentin.' },
  { id: 'h11', category: 'history', difficulty: 'medium',
    text: 'En quelle année les femmes ont-elles obtenu le droit de vote en France ?',
    correctAnswer: '1944', incorrectAnswers: ['1920', '1936', '1958'],
    trivia: 'La France a accordé le droit de vote aux femmes plus tard que la plupart des pays occidentaux, après la Nouvelle-Zélande (1893) et les États-Unis (1920).' },
  { id: 'h12', category: 'history', difficulty: 'hard',
    text: 'Quel traité a mis fin à la guerre de Trente Ans en 1648 ?',
    correctAnswer: 'La paix de Westphalie', incorrectAnswers: ['Le traité de Vienne', 'La paix d\'Utrecht', 'Le traité de Nimègue'],
    trivia: 'La paix de Westphalie est souvent citée comme l\'acte fondateur du système des États-nations modernes en Europe.' },

  // ── Géographie ────────────────────────────────────────────────────────────
  { id: 'g01', category: 'geography', difficulty: 'medium',
    text: 'Quelle est la capitale de l\'Australie ?',
    correctAnswer: 'Canberra', incorrectAnswers: ['Sydney', 'Melbourne', 'Brisbane'],
    trivia: 'Canberra a été choisie en 1908 comme compromis entre Sydney et Melbourne, qui se disputaient le titre de capitale.' },
  { id: 'g02', category: 'geography', difficulty: 'easy',
    text: 'Quel est le plus long fleuve du monde ?',
    correctAnswer: 'Le Nil', incorrectAnswers: ['L\'Amazone', 'Le Yangtsé', 'Le Mississippi'],
    trivia: 'Le Nil coule sur environ 6 650 km à travers 11 pays africains, de sa source en Éthiopie jusqu\'à la mer Méditerranée.' },
  { id: 'g03', category: 'geography', difficulty: 'easy',
    text: 'Dans quel pays se trouve le Machu Picchu ?',
    correctAnswer: 'Pérou', incorrectAnswers: ['Mexique', 'Bolivie', 'Équateur'],
    trivia: 'Le Machu Picchu est situé à 2 430 m d\'altitude dans les Andes et fut construit vers 1450 par les Incas.' },
  { id: 'g04', category: 'geography', difficulty: 'easy',
    text: 'Quel est le plus petit pays du monde ?',
    correctAnswer: 'Vatican', incorrectAnswers: ['Monaco', 'Saint-Marin', 'Liechtenstein'],
    trivia: 'Le Vatican couvre seulement 0,44 km², soit moins que Central Park à New York.' },
  { id: 'g05', category: 'geography', difficulty: 'easy',
    text: 'Quelle est la plus haute montagne du monde ?',
    correctAnswer: 'Mont Everest', incorrectAnswers: ['K2', 'Kangchenjunga', 'Mont Blanc'],
    trivia: 'L\'Everest mesure 8 849 m et continue de grandir d\'environ 4 mm par an en raison des mouvements tectoniques.' },
  { id: 'g06', category: 'geography', difficulty: 'easy',
    text: 'Quel est le plus grand désert chaud du monde ?',
    correctAnswer: 'Le Sahara', incorrectAnswers: ['Le désert d\'Arabie', 'Le Gobi', 'Le Namib'],
    trivia: 'Le Sahara couvre 9 millions de km² (la taille des États-Unis) mais était autrefois une savane verdoyante il y a 10 000 ans.' },
  { id: 'g07', category: 'geography', difficulty: 'easy',
    text: 'Quel océan est le plus grand ?',
    correctAnswer: 'L\'océan Pacifique', incorrectAnswers: ['L\'océan Atlantique', 'L\'océan Indien', 'L\'océan Arctique'],
    trivia: 'L\'océan Pacifique couvre plus de la moitié de la surface des océans mondiaux et contient à lui seul plus d\'eau que toutes les terres émergées réunies.' },
  { id: 'g08', category: 'geography', difficulty: 'medium',
    text: 'Quelle ville est la plus peuplée du monde ?',
    correctAnswer: 'Tokyo', incorrectAnswers: ['Delhi', 'Shanghai', 'São Paulo'],
    trivia: 'L\'agglomération de Tokyo compte environ 37 millions d\'habitants, soit plus que la population entière du Canada.' },
  { id: 'g09', category: 'geography', difficulty: 'easy',
    text: 'Quel est le pays le plus grand du monde ?',
    correctAnswer: 'La Russie', incorrectAnswers: ['Le Canada', 'La Chine', 'Les États-Unis'],
    trivia: 'La Russie couvre 17 millions de km², soit 11 % des terres émergées. Elle s\'étend sur 11 fuseaux horaires.' },
  { id: 'g10', category: 'geography', difficulty: 'medium',
    text: 'Quel est le plus long fleuve d\'Europe ?',
    correctAnswer: 'La Volga', incorrectAnswers: ['Le Danube', 'Le Rhin', 'La Loire'],
    trivia: 'La Volga mesure 3 692 km et se jette dans la mer Caspienne. Elle constitue le berceau de la culture russe.' },
  { id: 'g11', category: 'geography', difficulty: 'medium',
    text: 'Combien de pays composent l\'Amérique du Sud ?',
    correctAnswer: '12', incorrectAnswers: ['10', '14', '11'] },
  { id: 'g12', category: 'geography', difficulty: 'easy',
    text: 'Quelle est la capitale du Brésil ?',
    correctAnswer: 'Brasília', incorrectAnswers: ['Rio de Janeiro', 'São Paulo', 'Salvador'],
    trivia: 'Brasília a été construite de toutes pièces en seulement 41 mois et inaugurée comme capitale en 1960.' },

  // ── Sciences ──────────────────────────────────────────────────────────────
  { id: 's01', category: 'science', difficulty: 'easy',
    text: 'Quel est le symbole chimique de l\'or ?',
    correctAnswer: 'Au', incorrectAnswers: ['Ag', 'Fe', 'Cu'],
    trivia: '"Au" vient du latin "aurum". L\'or est l\'un des rares éléments connus depuis la Préhistoire, inaltérable et imputrescible.' },
  { id: 's02', category: 'science', difficulty: 'medium',
    text: 'Combien d\'os possède le corps humain adulte ?',
    correctAnswer: '206', incorrectAnswers: ['196', '216', '186'],
    trivia: 'Les bébés naissent avec environ 270 os. Certains fusionnent pendant l\'enfance, aboutissant aux 206 os de l\'adulte.' },
  { id: 's03', category: 'science', difficulty: 'easy',
    text: 'Quelle planète est la plus grande du système solaire ?',
    correctAnswer: 'Jupiter', incorrectAnswers: ['Saturne', 'Uranus', 'Neptune'],
    trivia: 'Jupiter est si massive qu\'elle pourrait contenir 1 300 Terres. La Grande Tache Rouge est une tempête qui dure depuis plus de 350 ans.' },
  { id: 's04', category: 'science', difficulty: 'easy',
    text: 'Quel gaz est le plus abondant dans l\'atmosphère terrestre ?',
    correctAnswer: 'L\'azote', incorrectAnswers: ['L\'oxygène', 'Le dioxyde de carbone', 'L\'argon'],
    trivia: 'L\'azote représente 78 % de l\'air. Bien qu\'essentiel à la vie, les plantes ne peuvent pas l\'absorber directement de l\'air.' },
  { id: 's05', category: 'science', difficulty: 'easy',
    text: 'Qui a théorisé la relativité générale ?',
    correctAnswer: 'Albert Einstein', incorrectAnswers: ['Isaac Newton', 'Nikola Tesla', 'Max Planck'],
    trivia: 'Einstein a développé la relativité générale en 1915. Ce n\'est qu\'en 2019 qu\'on a photographié un trou noir pour la première fois, confirmant sa théorie.' },
  { id: 's06', category: 'science', difficulty: 'easy',
    text: 'Quel est le numéro atomique de l\'hydrogène ?',
    correctAnswer: '1', incorrectAnswers: ['2', '6', '8'],
    trivia: 'L\'hydrogène est l\'élément le plus abondant de l\'univers. Le Soleil convertit 600 millions de tonnes d\'hydrogène en hélium chaque seconde.' },
  { id: 's07', category: 'science', difficulty: 'medium',
    text: 'Combien de chromosomes possède une cellule humaine normale ?',
    correctAnswer: '46', incorrectAnswers: ['23', '48', '42'],
    trivia: 'Les chromosomes humains contiennent environ 3 milliards de paires de bases d\'ADN. Si vous les dépliiez, l\'ADN d\'une seule cellule mesurerait environ 2 mètres.' },
  { id: 's08', category: 'science', difficulty: 'easy',
    text: 'Quelle est la formule chimique de l\'eau ?',
    correctAnswer: 'H₂O', incorrectAnswers: ['CO₂', 'H₂O₂', 'NaCl'],
    trivia: 'H₂O est l\'une des rares substances qui existe naturellement sous trois états : solide (glace), liquide (eau) et gazeux (vapeur).' },
  { id: 's09', category: 'science', difficulty: 'medium',
    text: 'À combien de degrés Celsius l\'eau bout-elle au niveau de la mer ?',
    correctAnswer: '100', incorrectAnswers: ['90', '110', '95'],
    trivia: 'L\'eau bout à une température plus basse en altitude. À l\'Everest (8 849 m), elle bout à seulement 70 °C.' },
  { id: 's10', category: 'science', difficulty: 'hard',
    text: 'Quelle particule subatomique a une charge électrique positive ?',
    correctAnswer: 'Le proton', incorrectAnswers: ['L\'électron', 'Le neutron', 'Le quark'],
    trivia: 'Les protons ont été découverts par Ernest Rutherford en 1917. Ils sont composés de trois quarks liés par des gluons.' },
  { id: 's11', category: 'science', difficulty: 'medium',
    text: 'Quel scientifique a découvert la pénicilline ?',
    correctAnswer: 'Alexander Fleming', incorrectAnswers: ['Louis Pasteur', 'Marie Curie', 'Joseph Lister'],
    trivia: 'Fleming a découvert la pénicilline par accident en 1928 en observant qu\'une moisissure tuait les bactéries dans sa boîte de Petri.' },
  { id: 's12', category: 'science', difficulty: 'easy',
    text: 'Combien de planètes compte notre système solaire ?',
    correctAnswer: '8', incorrectAnswers: ['9', '7', '10'],
    trivia: 'Pluton a été reclassée en "planète naine" en 2006 par l\'Union Astronomique Internationale, réduisant le nombre de planètes officielles de 9 à 8.' },

  // ── Culture Générale ──────────────────────────────────────────────────────
  { id: 'c01', category: 'general_knowledge', difficulty: 'medium',
    text: 'Quelle est la langue la plus parlée dans le monde ?',
    correctAnswer: 'Le mandarin', incorrectAnswers: ['L\'anglais', 'L\'espagnol', 'L\'hindi'],
    trivia: 'Le mandarin est la langue maternelle d\'environ 920 millions de personnes, mais l\'anglais reste la langue la plus parlée en comptant les locuteurs non-natifs.' },
  { id: 'c02', category: 'general_knowledge', difficulty: 'easy',
    text: 'Combien de couleurs comporte un arc-en-ciel ?',
    correctAnswer: '7', incorrectAnswers: ['6', '8', '5'],
    trivia: 'Les 7 couleurs (rouge, orange, jaune, vert, bleu, indigo, violet) ont été définies par Newton qui voulait un nombre lié aux notes de musique.' },
  { id: 'c03', category: 'general_knowledge', difficulty: 'easy',
    text: 'Quelle est la monnaie officielle du Japon ?',
    correctAnswer: 'Le yen', incorrectAnswers: ['Le won', 'Le yuan', 'Le dong'],
    trivia: '"Yen" signifie "cercle" ou "pièce ronde" en japonais. Le Japon possède l\'une des plus importantes réserves de devises étrangères au monde.' },
  { id: 'c04', category: 'general_knowledge', difficulty: 'easy',
    text: 'Combien de joueurs composent une équipe de football ?',
    correctAnswer: '11', incorrectAnswers: ['10', '12', '9'] },
  { id: 'c05', category: 'general_knowledge', difficulty: 'medium',
    text: 'En quelle année ont eu lieu les premiers Jeux Olympiques modernes ?',
    correctAnswer: '1896', incorrectAnswers: ['1900', '1888', '1904'],
    trivia: 'Les premiers JO modernes se sont tenus à Athènes avec 241 athlètes de 14 pays. Il n\'y avait aucune femme participante.' },
  { id: 'c06', category: 'general_knowledge', difficulty: 'easy',
    text: 'Quelle est la devise de la France ?',
    correctAnswer: 'Liberté, Égalité, Fraternité', incorrectAnswers: ['Honneur et Patrie', 'Liberté, Justice, Fraternité', 'Unité, Travail, Progrès'],
    trivia: 'Cette devise est apparue pendant la Révolution française et n\'est devenue officielle qu\'avec la Constitution de 1958.' },
  { id: 'c07', category: 'general_knowledge', difficulty: 'medium',
    text: 'Quel est l\'instrument à cordes le plus grand de l\'orchestre ?',
    correctAnswer: 'La contrebasse', incorrectAnswers: ['Le violoncelle', 'La harpe', 'La guitare basse'],
    trivia: 'La contrebasse peut mesurer jusqu\'à 2 mètres. Son ancêtre, le violone, était un instrument à frettes du XVIe siècle.' },
  { id: 'c08', category: 'general_knowledge', difficulty: 'easy',
    text: 'Quel est l\'animal le plus rapide du monde ?',
    correctAnswer: 'Le guépard', incorrectAnswers: ['Le lion', 'L\'antilope', 'Le faucon pèlerin'],
    trivia: 'Le guépard peut atteindre 110 km/h en quelques secondes mais ne peut maintenir cette vitesse que sur 300 à 400 mètres.' },
  { id: 'c09', category: 'general_knowledge', difficulty: 'easy',
    text: 'Combien de secondes y a-t-il dans une heure ?',
    correctAnswer: '3600', incorrectAnswers: ['600', '1800', '7200'] },
  { id: 'c10', category: 'general_knowledge', difficulty: 'medium',
    text: 'Quel est le numéro d\'urgence européen ?',
    correctAnswer: '112', incorrectAnswers: ['999', '911', '118'],
    trivia: 'Le 112 fonctionne dans tous les pays de l\'UE depuis 1991 et peut être composé même sans crédit sur un téléphone portable.' },

  // ── Cinéma & TV ───────────────────────────────────────────────────────────
  { id: 'f01', category: 'film_and_tv', difficulty: 'easy',
    text: 'Quel acteur joue Tony Stark / Iron Man dans les films Marvel ?',
    correctAnswer: 'Robert Downey Jr.', incorrectAnswers: ['Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'],
    trivia: 'Robert Downey Jr. a joué Iron Man dans 10 films Marvel. Son salaire pour "Avengers" (2012) était d\'environ 50 millions de dollars.' },
  { id: 'f02', category: 'film_and_tv', difficulty: 'easy',
    text: 'Quel film Disney raconte l\'histoire d\'un poisson-clown cherchant son fils ?',
    correctAnswer: 'Le Monde de Nemo', incorrectAnswers: ['Dumbo', 'Bambi', 'L\'Île au trésor'],
    trivia: '"Le Monde de Nemo" (2003) a entraîné une hausse de 40 % des ventes de poissons-clowns dans le monde, mettant en danger l\'espèce.' },
  { id: 'f03', category: 'film_and_tv', difficulty: 'medium',
    text: 'Quelle actrice française a remporté l\'Oscar de la meilleure actrice en 2012 ?',
    correctAnswer: 'Marion Cotillard', incorrectAnswers: ['Audrey Tautou', 'Isabelle Huppert', 'Juliette Binoche'],
    trivia: 'Marion Cotillard a remporté l\'Oscar pour son rôle d\'Édith Piaf dans "La Môme" (2007). Elle est la seule française à avoir remporté cet Oscar pour un rôle en français.' },
  { id: 'f04', category: 'film_and_tv', difficulty: 'medium',
    text: 'Dans quel film Jodie Foster joue-t-elle la détective Clarice Starling ?',
    correctAnswer: 'Le Silence des agneaux', incorrectAnswers: ['Panic Room', 'Contact', 'Nell'] },
  { id: 'f05', category: 'film_and_tv', difficulty: 'medium',
    text: 'Quel film a remporté la Palme d\'Or à Cannes en 2019 ?',
    correctAnswer: 'Parasite', incorrectAnswers: ['Titane', 'Portrait de la jeune fille en feu', 'Once Upon a Time in Hollywood'],
    trivia: '"Parasite" du réalisateur Bong Joon-ho est le premier film en langue étrangère à remporter l\'Oscar du meilleur film en 2020.' },
  { id: 'f06', category: 'film_and_tv', difficulty: 'easy',
    text: 'Qui a réalisé la trilogie "Le Seigneur des Anneaux" ?',
    correctAnswer: 'Peter Jackson', incorrectAnswers: ['Ridley Scott', 'James Cameron', 'Steven Spielberg'],
    trivia: 'La trilogie a été tournée entièrement en Nouvelle-Zélande. Le tournage simultané des trois films a duré 438 jours.' },
  { id: 'f07', category: 'film_and_tv', difficulty: 'easy',
    text: 'Dans quelle série trouve-t-on la famille Stark de Winterfell ?',
    correctAnswer: 'Game of Thrones', incorrectAnswers: ['Vikings', 'The Last Kingdom', 'Outlander'] },
  { id: 'f08', category: 'film_and_tv', difficulty: 'medium',
    text: 'Quel film de Stanley Kubrick se passe à bord d\'une station spatiale en route vers Jupiter ?',
    correctAnswer: '2001 : l\'Odyssée de l\'espace', incorrectAnswers: ['Full Metal Jacket', 'Eyes Wide Shut', 'Barry Lyndon'],
    trivia: 'Sorti en 1968, "2001 : l\'Odyssée de l\'espace" a influencé la NASA. Les effets spéciaux étaient si réalistes que certains ont prétendu que Kubrick avait aidé à truquer les images de la Lune.' },
  { id: 'f09', category: 'film_and_tv', difficulty: 'easy',
    text: 'Dans quel pays a été créée la série "La Casa de Papel" ?',
    correctAnswer: 'Espagne', incorrectAnswers: ['Mexique', 'Colombie', 'Argentine'] },
  { id: 'f10', category: 'film_and_tv', difficulty: 'medium',
    text: 'Quel réalisateur français est connu pour la trilogie "Trois couleurs" ?',
    correctAnswer: 'Krzysztof Kieślowski', incorrectAnswers: ['Jean-Luc Godard', 'François Truffaut', 'Claude Chabrol'],
    trivia: 'Kieślowski était polonais, pas français. La trilogie (Bleu, Blanc, Rouge) symbolise les couleurs du drapeau français et leurs valeurs.' },

  // ── Sport ─────────────────────────────────────────────────────────────────
  { id: 'sp01', category: 'sport_and_leisure', difficulty: 'medium',
    text: 'Combien de fois la France a-t-elle remporté la Coupe du Monde de football ?',
    correctAnswer: '2', incorrectAnswers: ['1', '3', '4'],
    trivia: 'La France a remporté la Coupe du Monde en 1998 (à domicile) et en 2018 en Russie. Les Bleus sont l\'une des 8 nations à avoir soulevé le trophée.' },
  { id: 'sp02', category: 'sport_and_leisure', difficulty: 'easy',
    text: 'Quel pays a remporté le plus de Coupes du Monde de football ?',
    correctAnswer: 'Brésil', incorrectAnswers: ['Allemagne', 'Italie', 'Argentine'],
    trivia: 'Le Brésil a remporté 5 Coupes du Monde (1958, 1962, 1970, 1994, 2002) et est le seul pays à avoir participé à toutes les éditions.' },
  { id: 'sp03', category: 'sport_and_leisure', difficulty: 'medium',
    text: 'Quelle est la longueur officielle d\'un marathon ?',
    correctAnswer: '42,195 km', incorrectAnswers: ['40 km', '45 km', '41 km'],
    trivia: 'Cette distance précise a été fixée aux JO de Londres en 1908 pour que la course parte du château de Windsor et arrive devant la loge royale.' },
  { id: 'sp04', category: 'sport_and_leisure', difficulty: 'easy',
    text: 'Quel athlète est surnommé "La Foudre" ou "Lightning Bolt" ?',
    correctAnswer: 'Usain Bolt', incorrectAnswers: ['Carl Lewis', 'Mo Farah', 'Yohan Blake'],
    trivia: 'Usain Bolt détient le record du monde du 100m depuis 2009 avec 9,58 secondes. Sa vitesse de pointe a été mesurée à 44,72 km/h.' },
  { id: 'sp05', category: 'sport_and_leisure', difficulty: 'easy',
    text: 'Combien de joueurs composent une équipe de basketball ?',
    correctAnswer: '5', incorrectAnswers: ['6', '7', '4'] },
  { id: 'sp06', category: 'sport_and_leisure', difficulty: 'easy',
    text: 'Quel est le surnom de l\'équipe nationale de rugby de Nouvelle-Zélande ?',
    correctAnswer: 'Les All Blacks', incorrectAnswers: ['Les Springboks', 'Les Wallabies', 'Les Pumas'],
    trivia: 'Le haka des All Blacks est une danse guerrière maorie. Leur taux de victoire global dépasse 75 %, le meilleur de toutes les équipes nationales de rugby.' },
  { id: 'sp07', category: 'sport_and_leisure', difficulty: 'easy',
    text: 'Sur quelle surface se joue le tournoi de Roland-Garros ?',
    correctAnswer: 'Terre battue', incorrectAnswers: ['Gazon', 'Surface dure', 'Moquette'],
    trivia: 'La terre battue de Roland-Garros est en fait de la brique pilée de couleur rouge-orangé. Elle ralentit la balle et favorise les échanges longs.' },
  { id: 'sp08', category: 'sport_and_leisure', difficulty: 'medium',
    text: 'Quel nageur a remporté le plus de médailles d\'or olympiques de l\'histoire ?',
    correctAnswer: 'Michael Phelps', incorrectAnswers: ['Mark Spitz', 'Ian Thorpe', 'Ryan Lochte'],
    trivia: 'Michael Phelps a remporté 23 médailles d\'or olympiques. Ses bras s\'étendent sur 201 cm, soit plus que sa taille.' },
  { id: 'sp09', category: 'sport_and_leisure', difficulty: 'medium',
    text: 'Dans quelle ville se sont déroulés les Jeux Olympiques d\'été de 2024 ?',
    correctAnswer: 'Paris', incorrectAnswers: ['Los Angeles', 'Tokyo', 'Londres'],
    trivia: 'Paris 2024 a été la 3ème fois que la capitale française accueillait les JO d\'été, après 1900 et 1924.' },
  { id: 'sp10', category: 'sport_and_leisure', difficulty: 'medium',
    text: 'Quel joueur de tennis a remporté le plus grand nombre de tournois du Grand Chelem ?',
    correctAnswer: 'Novak Djokovic', incorrectAnswers: ['Rafael Nadal', 'Roger Federer', 'Pete Sampras'],
    trivia: 'Novak Djokovic a remporté 24 tournois du Grand Chelem, dont un record de 10 Open d\'Australie.' },

  // ── Musique ───────────────────────────────────────────────────────────────
  { id: 'm01', category: 'music', difficulty: 'easy',
    text: 'Quel groupe de rock britannique a enregistré l\'album "Abbey Road" ?',
    correctAnswer: 'Les Beatles', incorrectAnswers: ['The Rolling Stones', 'The Who', 'Led Zeppelin'],
    trivia: '"Abbey Road" (1969) était le dernier album enregistré par les Beatles. Le célèbre passage piéton existe encore et est photographié des millions de fois par an.' },
  { id: 'm02', category: 'music', difficulty: 'easy',
    text: 'Quelle chanteuse française a chanté "Non, je ne regrette rien" ?',
    correctAnswer: 'Édith Piaf', incorrectAnswers: ['Dalida', 'Barbara', 'Mireille Mathieu'],
    trivia: 'Édith Piaf surnommée "La Môme" mesurait seulement 1,47 m. Elle est la chanteuse française la plus reconnue dans le monde.' },
  { id: 'm03', category: 'music', difficulty: 'easy',
    text: 'Qui est l\'artiste derrière l\'album "Thriller" (1982) ?',
    correctAnswer: 'Michael Jackson', incorrectAnswers: ['Prince', 'Madonna', 'David Bowie'],
    trivia: '"Thriller" reste l\'album le plus vendu de l\'histoire avec environ 70 millions d\'exemplaires. Le clip de "Thriller" dure 14 minutes.' },
  { id: 'm04', category: 'music', difficulty: 'easy',
    text: 'Quel compositeur classique était sourd en composant sa 9e symphonie ?',
    correctAnswer: 'Beethoven', incorrectAnswers: ['Mozart', 'Bach', 'Schubert'],
    trivia: 'Beethoven était presque totalement sourd quand il a composé sa 9e symphonie. Lors de sa création en 1824, il fallut lui montrer les applaudissements car il ne les entendait pas.' },
  { id: 'm05', category: 'music', difficulty: 'easy',
    text: 'Quel groupe est connu pour la chanson "Bohemian Rhapsody" ?',
    correctAnswer: 'Queen', incorrectAnswers: ['The Beatles', 'Led Zeppelin', 'Pink Floyd'],
    trivia: '"Bohemian Rhapsody" dure 5 minutes 55 secondes, ce qui était très inhabituel pour un single en 1975. Les maisons de disques pensaient que c\'était trop long.' },
  { id: 'm06', category: 'music', difficulty: 'easy',
    text: 'Dans quel pays est né Bob Marley ?',
    correctAnswer: 'Jamaïque', incorrectAnswers: ['Cuba', 'Barbade', 'Trinité-et-Tobago'],
    trivia: 'Bob Marley a popularisé le reggae dans le monde entier. Il est décédé à 36 ans d\'un cancer du mélanome sous l\'ongle du gros orteil.' },
  { id: 'm07', category: 'music', difficulty: 'medium',
    text: 'Quelle artiste française a représenté la France à l\'Eurovision en 2021 avec "Voilà" ?',
    correctAnswer: 'Barbara Pravi', incorrectAnswers: ['Amir', 'Alma', 'Bilal Hassani'],
    trivia: 'Barbara Pravi a terminé 2ème à l\'Eurovision 2021. C\'est le meilleur résultat de la France depuis 1991.' },
  { id: 'm08', category: 'music', difficulty: 'medium',
    text: 'Quel chanteur français est connu pour l\'album "La Fête" et "Partir un jour" ?',
    correctAnswer: 'Indochine', incorrectAnswers: ['Téléphone', 'Bashung', 'Cabrel'] },
  { id: 'm09', category: 'music', difficulty: 'easy',
    text: 'Quel rappeur américain est connu sous le nom "Eminem" ?',
    correctAnswer: 'Marshall Mathers', incorrectAnswers: ['Shawn Carter', 'Dwayne Carter', 'Curtis Jackson'],
    trivia: 'Eminem est l\'artiste solo le plus vendu des années 2000. Son nom de scène vient de ses initiales M.M. (Marshall Mathers).' },
  { id: 'm10', category: 'music', difficulty: 'medium',
    text: 'De quel pays est originaire le groupe ABBA ?',
    correctAnswer: 'Suède', incorrectAnswers: ['Norvège', 'Danemark', 'Finlande'],
    trivia: 'ABBA (Agnetha, Björn, Benny, Anni-Frid) a remporté l\'Eurovision 1974 avec "Waterloo". Leur musique génère plus de revenus annuels que l\'ensemble de l\'industrie sidérurgique suédoise.' },

  // ── Arts & Littérature ────────────────────────────────────────────────────
  { id: 'a01', category: 'arts_and_literature', difficulty: 'easy',
    text: 'Qui a écrit "Les Misérables" ?',
    correctAnswer: 'Victor Hugo', incorrectAnswers: ['Gustave Flaubert', 'Émile Zola', 'Alexandre Dumas'],
    trivia: 'Victor Hugo a mis 17 ans à écrire "Les Misérables". La télégramme qu\'il a envoyé à son éditeur pour savoir si le livre se vendait bien — "?" — est l\'une des plus courtes correspondances littéraires célèbres. La réponse : "!".' },
  { id: 'a02', category: 'arts_and_literature', difficulty: 'easy',
    text: 'Quel peintre est connu pour ses tableaux de tournesols et ses nuits étoilées ?',
    correctAnswer: 'Vincent van Gogh', incorrectAnswers: ['Claude Monet', 'Paul Gauguin', 'Paul Cézanne'],
    trivia: 'Van Gogh a peint environ 900 tableaux en seulement 10 ans. Il n\'a vendu qu\'un seul tableau de son vivant.' },
  { id: 'a03', category: 'arts_and_literature', difficulty: 'medium',
    text: 'Qui a écrit "À la recherche du temps perdu" ?',
    correctAnswer: 'Marcel Proust', incorrectAnswers: ['Albert Camus', 'Jean-Paul Sartre', 'André Gide'],
    trivia: '"À la recherche du temps perdu" est l\'un des plus longs romans jamais écrits avec environ 1,5 million de mots répartis en 7 volumes.' },
  { id: 'a04', category: 'arts_and_literature', difficulty: 'easy',
    text: 'Quel musée parisien abrite la Joconde ?',
    correctAnswer: 'Le Louvre', incorrectAnswers: ['Le musée d\'Orsay', 'Le musée Picasso', 'Le Centre Pompidou'],
    trivia: 'La Joconde mesure seulement 53 × 77 cm. Les visiteurs sont souvent surpris par sa petite taille. Elle est assurée pour environ 800 millions de dollars.' },
  { id: 'a05', category: 'arts_and_literature', difficulty: 'easy',
    text: 'Qui a écrit "Le Petit Prince" ?',
    correctAnswer: 'Antoine de Saint-Exupéry', incorrectAnswers: ['Jules Verne', 'Jules Renard', 'Jean de La Fontaine'],
    trivia: '"Le Petit Prince" est le livre le plus traduit du monde (après la Bible), avec plus de 300 langues et dialectes.' },
  { id: 'a06', category: 'arts_and_literature', difficulty: 'medium',
    text: 'Quel mouvement artistique est associé à Salvador Dalí ?',
    correctAnswer: 'Le surréalisme', incorrectAnswers: ['Le cubisme', 'Le dadaïsme', 'L\'expressionnisme'],
    trivia: 'Salvador Dalí se disait lui-même le seul surréaliste à ne pas être fou. Il dormait avec une clé dans la main pour se réveiller au moment de s\'endormir et capturer ses visions.' },
  { id: 'a07', category: 'arts_and_literature', difficulty: 'medium',
    text: 'Quel auteur français a reçu le prix Nobel de littérature en 1957 ?',
    correctAnswer: 'Albert Camus', incorrectAnswers: ['Jean-Paul Sartre', 'André Gide', 'François Mauriac'],
    trivia: 'Camus a reçu le Nobel à 44 ans, le deuxième plus jeune lauréat français. Jean-Paul Sartre a refusé ce même prix en 1964.' },
  { id: 'a08', category: 'arts_and_literature', difficulty: 'easy',
    text: 'Qui a écrit "Don Quichotte" ?',
    correctAnswer: 'Miguel de Cervantes', incorrectAnswers: ['William Shakespeare', 'Dante Alighieri', 'Voltaire'],
    trivia: '"Don Quichotte" (1605) est souvent cité comme le premier roman moderne. Cervantes a écrit la partie 1 alors qu\'il était en prison.' },

  // ── Cuisine & Boissons ────────────────────────────────────────────────────
  { id: 'cu01', category: 'food_and_drink', difficulty: 'easy',
    text: 'De quel pays est originaire la paella ?',
    correctAnswer: 'Espagne', incorrectAnswers: ['Italie', 'Portugal', 'Mexique'],
    trivia: 'La paella est originaire de la région de Valence en Espagne. Le mot "paella" désigne la poêle large et plate utilisée pour la cuisson.' },
  { id: 'cu02', category: 'food_and_drink', difficulty: 'easy',
    text: 'De quel pays est originaire la recette du sushi ?',
    correctAnswer: 'Japon', incorrectAnswers: ['Chine', 'Corée du Sud', 'Vietnam'],
    trivia: 'Le sushi a été inventé au Japon au XVIIe siècle. Le "narezushi" original était du poisson fermenté dans du riz pendant des mois.' },
  { id: 'cu03', category: 'food_and_drink', difficulty: 'easy',
    text: 'Quel est l\'ingrédient principal de la guacamole ?',
    correctAnswer: 'Avocat', incorrectAnswers: ['Tomate', 'Poivron', 'Oignon'],
    trivia: 'La guacamole existe depuis l\'époque des Aztèques (vers 500 ap. J.-C.). Le mot vient du nahuatl "ahuacamolli" (sauce d\'avocat).' },
  { id: 'cu04', category: 'food_and_drink', difficulty: 'easy',
    text: 'Quelle boisson alcoolisée est produite à partir de la canne à sucre ?',
    correctAnswer: 'Le rhum', incorrectAnswers: ['Le whisky', 'La vodka', 'Le gin'],
    trivia: 'Le rhum est né dans les Caraïbes au XVIIe siècle. Il était utilisé comme monnaie d\'échange et comme ration quotidienne pour les marins de la Royal Navy jusqu\'en 1970.' },
  { id: 'cu05', category: 'food_and_drink', difficulty: 'medium',
    text: 'Quel fromage français est protégé et vient de la région du Rouerge ?',
    correctAnswer: 'Le Roquefort', incorrectAnswers: ['Le Camembert', 'Le Brie', 'Le Comté'],
    trivia: 'Le Roquefort est affiné dans les caves naturelles de Combalou à Roquefort-sur-Soulzon. C\'est l\'un des fromages les plus anciens du monde.' },
  { id: 'cu06', category: 'food_and_drink', difficulty: 'easy',
    text: 'Quel fruit est utilisé pour faire le vin ?',
    correctAnswer: 'Le raisin', incorrectAnswers: ['La pomme', 'La poire', 'La cerise'],
    trivia: 'La France est le 2ème producteur mondial de vin. Le vin le plus vieux jamais trouvé (datant de 325-350 ap. J.-C.) a été découvert en Allemagne.' },
  { id: 'cu07', category: 'food_and_drink', difficulty: 'medium',
    text: 'Dans quelle ville française est originaire la quiche ?',
    correctAnswer: 'Lorraine (région)', incorrectAnswers: ['Bretagne', 'Alsace', 'Normandie'],
    trivia: 'La quiche lorraine originale ne contenait pas de fromage, seulement des lardons, de la crème et des œufs. Le fromage a été ajouté plus tardivement.' },

  // ── Société & Culture ─────────────────────────────────────────────────────
  { id: 'sc01', category: 'society_and_culture', difficulty: 'easy',
    text: 'Quel réseau social a été fondé par Mark Zuckerberg en 2004 ?',
    correctAnswer: 'Facebook', incorrectAnswers: ['Twitter', 'MySpace', 'Instagram'] },
  { id: 'sc02', category: 'society_and_culture', difficulty: 'easy',
    text: 'Quel est le nom du président américain élu en 2008 ?',
    correctAnswer: 'Barack Obama', incorrectAnswers: ['George W. Bush', 'Bill Clinton', 'John McCain'] },
  { id: 'sc03', category: 'society_and_culture', difficulty: 'medium',
    text: 'Quelle organisation internationale a son siège à Genève, en Suisse ?',
    correctAnswer: 'La Croix-Rouge internationale', incorrectAnswers: ['L\'ONU', 'L\'UNESCO', 'L\'OTAN'] },
  { id: 'sc04', category: 'society_and_culture', difficulty: 'medium',
    text: 'En quelle année a été fondée l\'Union européenne (traité de Maastricht) ?',
    correctAnswer: '1993', incorrectAnswers: ['1985', '1957', '2002'] },
  { id: 'sc05', category: 'society_and_culture', difficulty: 'easy',
    text: 'Quel est le symbole chimique du fer ?',
    correctAnswer: 'Fe', incorrectAnswers: ['Fe2', 'Ir', 'F'] },

  // ── Questions difficiles supplémentaires ─────────────────────────────────
  { id: 'hrd01', category: 'history', difficulty: 'hard',
    text: 'Quel édit de 1598 accordait la liberté de culte aux protestants en France ?',
    correctAnswer: 'L\'édit de Nantes', incorrectAnswers: ['L\'édit de Fontainebleau', 'L\'édit de Villers-Cotterêts', 'L\'édit de Moulins'] },
  { id: 'hrd02', category: 'history', difficulty: 'hard',
    text: 'En quelle année a eu lieu la célèbre bataille de Marignan, victoire de François Ier ?',
    correctAnswer: '1515', incorrectAnswers: ['1512', '1519', '1525'] },
  { id: 'hrd03', category: 'history', difficulty: 'hard',
    text: 'Quel est le nom du premier code de lois écrit, promulgué en Mésopotamie vers 1750 av. J.-C. ?',
    correctAnswer: 'Le Code de Hammurabi', incorrectAnswers: ['Le Code d\'Ur-Nammu', 'Les Lois de Manu', 'Le Code de Lipit-Ishtar'] },
  { id: 'hrd04', category: 'history', difficulty: 'hard',
    text: 'Lors de quelle bataille Alexandre le Grand a-t-il définitivement vaincu Darius III en 331 av. J.-C. ?',
    correctAnswer: 'Gaugamèles', incorrectAnswers: ['Issos', 'Granique', 'Hydaspe'] },
  { id: 'hrd05', category: 'history', difficulty: 'hard',
    text: 'En quelle année l\'Empire romain d\'Occident a-t-il officiellement pris fin ?',
    correctAnswer: '476', incorrectAnswers: ['410', '455', '493'] },
  { id: 'hrd06', category: 'history', difficulty: 'hard',
    text: 'Quel tsar russe a fondé la ville de Saint-Pétersbourg en 1703 ?',
    correctAnswer: 'Pierre le Grand', incorrectAnswers: ['Catherine II', 'Ivan le Terrible', 'Alexandre Ier'] },
  { id: 'hrd07', category: 'history', difficulty: 'hard',
    text: 'Quel est le nom du dernier empereur aztèque, capturé par Hernán Cortés en 1521 ?',
    correctAnswer: 'Cuauhtémoc', incorrectAnswers: ['Moctezuma II', 'Cuitláhuac', 'Axayácatl'] },
  { id: 'hrd08', category: 'history', difficulty: 'hard',
    text: 'Quel pays a lancé le premier satellite artificiel de l\'histoire, Spoutnik 1, en 1957 ?',
    correctAnswer: 'L\'URSS', incorrectAnswers: ['Les États-Unis', 'La Chine', 'Le Royaume-Uni'] },
  { id: 'hrd09', category: 'geography', difficulty: 'hard',
    text: 'Quelle est la plus longue frontière terrestre entre deux pays au monde ?',
    correctAnswer: 'Canada – États-Unis', incorrectAnswers: ['Russie – Kazakhstan', 'Chine – Mongolie', 'Brésil – Pérou'] },
  { id: 'hrd10', category: 'geography', difficulty: 'hard',
    text: 'Quel pays possède le plus grand nombre d\'îles au monde ?',
    correctAnswer: 'Suède', incorrectAnswers: ['Indonésie', 'Philippines', 'Norvège'] },
  { id: 'hrd11', category: 'geography', difficulty: 'hard',
    text: 'Dans quel pays se trouve le lac Titicaca, le plus haut lac navigable du monde ?',
    correctAnswer: 'À la frontière du Pérou et de la Bolivie', incorrectAnswers: ['Équateur', 'Chili', 'Argentine'] },
  { id: 'hrd12', category: 'geography', difficulty: 'hard',
    text: 'Quelle est la capitale actuelle du Kazakhstan (renommée en 2019) ?',
    correctAnswer: 'Nur-Sultan (Astana)', incorrectAnswers: ['Almaty', 'Chymkent', 'Aktobe'] },
  { id: 'hrd13', category: 'science', difficulty: 'hard',
    text: 'Combien d\'électrons peut contenir au maximum la couche électronique M d\'un atome ?',
    correctAnswer: '18', incorrectAnswers: ['8', '32', '2'] },
  { id: 'hrd14', category: 'science', difficulty: 'hard',
    text: 'Quel élément chimique possède le point de fusion le plus élevé ?',
    correctAnswer: 'Le tungstène', incorrectAnswers: ['Le platine', 'L\'osmium', 'Le carbone'] },
  { id: 'hrd15', category: 'science', difficulty: 'hard',
    text: 'Quelle loi décrit la relation entre pression et volume d\'un gaz parfait à température constante ?',
    correctAnswer: 'La loi de Boyle-Mariotte', incorrectAnswers: ['La loi de Charles', 'La loi de Gay-Lussac', 'La loi d\'Avogadro'] },
  { id: 'hrd16', category: 'science', difficulty: 'hard',
    text: 'Quel est le nom de la particule médiatrice de la force électromagnétique ?',
    correctAnswer: 'Le photon', incorrectAnswers: ['Le gluon', 'Le boson W', 'Le graviton'] },
  { id: 'hrd17', category: 'science', difficulty: 'hard',
    text: 'Quelle structure de l\'ADN a été décrite pour la première fois par Watson et Crick en 1953 ?',
    correctAnswer: 'La double hélice', incorrectAnswers: ['La triple hélice', 'La structure en feuillet', 'Le tétramère'] },
  { id: 'hrd18', category: 'film_and_tv', difficulty: 'hard',
    text: 'Quel film de Michelangelo Antonioni a remporté la Palme d\'Or à Cannes en 1960 ?',
    correctAnswer: 'L\'Avventura', incorrectAnswers: ['La Dolce Vita', 'Blow-Up', '8½'] },
  { id: 'hrd19', category: 'film_and_tv', difficulty: 'hard',
    text: 'Quel cinéaste japonais a réalisé "Les Sept Samouraïs" (1954) ?',
    correctAnswer: 'Akira Kurosawa', incorrectAnswers: ['Yasujirō Ozu', 'Kenji Mizoguchi', 'Nagisa Ōshima'] },
  { id: 'hrd20', category: 'sport_and_leisure', difficulty: 'hard',
    text: 'Quel pays a remporté la première Coupe du Monde de football en 1930 ?',
    correctAnswer: 'Uruguay', incorrectAnswers: ['Argentine', 'Brésil', 'Italie'] },
  { id: 'hrd21', category: 'sport_and_leisure', difficulty: 'hard',
    text: 'Combien de Ballons d\'Or Lionel Messi avait-il remportés à fin 2024 ?',
    correctAnswer: '8', incorrectAnswers: ['7', '6', '9'] },
  { id: 'hrd22', category: 'music', difficulty: 'hard',
    text: 'Quel compositeur romantique polonais est surnommé "le poète du piano" ?',
    correctAnswer: 'Frédéric Chopin', incorrectAnswers: ['Franz Liszt', 'Robert Schumann', 'Claude Debussy'] },
  { id: 'hrd23', category: 'music', difficulty: 'hard',
    text: 'Quel est le vrai nom de Lady Gaga ?',
    correctAnswer: 'Stefani Germanotta', incorrectAnswers: ['Alicia Moore', 'Robyn Fenty', 'Belcalis Almánzar'] },
  { id: 'hrd24', category: 'arts_and_literature', difficulty: 'hard',
    text: 'Qui a écrit le roman "Ulysse" (1922), chef-d\'œuvre du modernisme ?',
    correctAnswer: 'James Joyce', incorrectAnswers: ['Virginia Woolf', 'William Faulkner', 'T.S. Eliot'] },
  { id: 'hrd25', category: 'arts_and_literature', difficulty: 'hard',
    text: 'Quel architecte espagnol a conçu la Sagrada Família à Barcelone ?',
    correctAnswer: 'Antoni Gaudí', incorrectAnswers: ['Santiago Calatrava', 'Rafael Moneo', 'Ricardo Bofill'] },
  { id: 'hrd26', category: 'general_knowledge', difficulty: 'hard',
    text: 'Quel est le symbole chimique du tungstène (wolfram) ?',
    correctAnswer: 'W', incorrectAnswers: ['Tu', 'Wf', 'Tn'] },
  { id: 'hrd27', category: 'food_and_drink', difficulty: 'hard',
    text: 'Quelle technique culinaire consiste à cuire des aliments sous vide dans un bain d\'eau à température précise ?',
    correctAnswer: 'La cuisson sous vide (sous-vide)', incorrectAnswers: ['Le confit', 'La cuisson basse température au four', 'Le bain-marie'] },
  { id: 'hrd28', category: 'society_and_culture', difficulty: 'hard',
    text: 'Quel philosophe grec a fondé l\'Académie, la première grande institution philosophique occidentale ?',
    correctAnswer: 'Platon', incorrectAnswers: ['Socrate', 'Aristote', 'Épicure'] },

  // ── Île de la Réunion ─────────────────────────────────────────────────────
  { id: 're01', category: 'reunion', difficulty: 'easy',
    text: 'Quelle est la capitale de l\'île de La Réunion ?',
    correctAnswer: 'Saint-Denis', incorrectAnswers: ['Saint-Pierre', 'Saint-Paul', 'Le Port'] },
  { id: 're02', category: 'reunion', difficulty: 'easy',
    text: 'Dans quel océan se trouve l\'île de La Réunion ?',
    correctAnswer: 'L\'océan Indien', incorrectAnswers: ['L\'océan Atlantique', 'L\'océan Pacifique', 'La mer Méditerranée'] },
  { id: 're03', category: 'reunion', difficulty: 'easy',
    text: 'Quel est le nom du volcan actif de La Réunion ?',
    correctAnswer: 'Le Piton de la Fournaise', incorrectAnswers: ['Le Piton des Neiges', 'Le Maïdo', 'Le Grand Bénare'] },
  { id: 're04', category: 'reunion', difficulty: 'easy',
    text: 'Quel est le point culminant de l\'île de La Réunion ?',
    correctAnswer: 'Le Piton des Neiges', incorrectAnswers: ['Le Piton de la Fournaise', 'Le Maïdo', 'Le Grand Bénare'] },
  { id: 're05', category: 'reunion', difficulty: 'easy',
    text: 'Quel est le numéro de département de La Réunion ?',
    correctAnswer: '974', incorrectAnswers: ['971', '972', '976'] },
  { id: 're06', category: 'reunion', difficulty: 'easy',
    text: 'Quelle monnaie est utilisée à La Réunion ?',
    correctAnswer: 'L\'euro', incorrectAnswers: ['Le franc CFA', 'Le franc réunionnais', 'Le dollar'] },
  { id: 're07', category: 'reunion', difficulty: 'easy',
    text: 'En quelle année La Réunion est-elle devenue un département français ?',
    correctAnswer: '1946', incorrectAnswers: ['1848', '1963', '1974'] },
  { id: 're08', category: 'reunion', difficulty: 'easy',
    text: 'Quel plat réunionnais consiste en une sauce tomate épicée avec des saucisses ?',
    correctAnswer: 'Le rougail saucisse', incorrectAnswers: ['Le carry poulet', 'Le boucané', 'Le vindaye'] },
  { id: 're09', category: 'reunion', difficulty: 'easy',
    text: 'Quelle épice locale donne une couleur jaune aux plats réunionnais ?',
    correctAnswer: 'Le curcuma (safran péi)', incorrectAnswers: ['Le gingembre', 'La cannelle', 'Le cumin'] },
  { id: 're10', category: 'reunion', difficulty: 'medium',
    text: 'Comment s\'appelle le plat traditionnel réunionnais à base de riz et de sauce mijotée ?',
    correctAnswer: 'Le carry', incorrectAnswers: ['Le colombo', 'Le boucané', 'Le rougail'] },
  { id: 're11', category: 'reunion', difficulty: 'medium',
    text: 'Quels sont les trois cirques de La Réunion ?',
    correctAnswer: 'Cilaos, Mafate et Salazie', incorrectAnswers: ['Cilaos, Bras-Panon et Salazie', 'Mafate, Salazie et Saint-Denis', 'Cilaos, Mafate et Piton'] },
  { id: 're12', category: 'reunion', difficulty: 'medium',
    text: 'Quel est le nom de l\'aéroport international principal de La Réunion ?',
    correctAnswer: 'Roland Garros', incorrectAnswers: ['Pierrefonds', 'Saint-Denis Sud', 'La Rivière des Galets'] },
  { id: 're13', category: 'reunion', difficulty: 'medium',
    text: 'Quel oiseau rapace endémique est le symbole de La Réunion ?',
    correctAnswer: 'Le Papangue', incorrectAnswers: ['Le Paille-en-queue', 'Le Tuit-tuit', 'Le Cardinal'] },
  { id: 're14', category: 'reunion', difficulty: 'medium',
    text: 'Quel site de La Réunion est classé au Patrimoine mondial de l\'UNESCO depuis 2010 ?',
    correctAnswer: 'Les Pitons, cirques et remparts', incorrectAnswers: ['Le lagon de Saint-Gilles', 'Le Grand Bénare', 'La forêt de Bébour'] },
  { id: 're15', category: 'reunion', difficulty: 'medium',
    text: 'Quel est le principal produit agricole exporté par La Réunion ?',
    correctAnswer: 'La canne à sucre', incorrectAnswers: ['La vanille', 'L\'ananas', 'Le café'] },
  { id: 're16', category: 'reunion', difficulty: 'medium',
    text: 'Comment appelle-t-on le point de vue panoramique culminant à 2 205 m d\'altitude sur le cirque de Mafate ?',
    correctAnswer: 'Le Maïdo', incorrectAnswers: ['Le Belvédère', 'La Roche Écrite', 'Le Grand Bénare'] },
  { id: 're17', category: 'reunion', difficulty: 'medium',
    text: 'En quelle année l\'esclavage a-t-il été aboli à La Réunion ?',
    correctAnswer: '1848', incorrectAnswers: ['1794', '1835', '1862'] },
  { id: 're18', category: 'reunion', difficulty: 'hard',
    text: 'Sous quel nom a-t-on appelé l\'île de La Réunion lors de sa première colonisation française au XVIIe siècle ?',
    correctAnswer: 'Île Bourbon', incorrectAnswers: ['Île de France', 'Île Mascareignes', 'Île Dauphine'] },
  { id: 're19', category: 'reunion', difficulty: 'hard',
    text: 'Quel est le nom du sentier de grande randonnée qui traverse l\'intégralité de l\'île de La Réunion du nord au sud ?',
    correctAnswer: 'GR R2', incorrectAnswers: ['GR R1', 'GR 20', 'GR R3'] },
  { id: 're20', category: 'reunion', difficulty: 'hard',
    text: 'Quel peuple a été massivement importé comme main-d\'œuvre à La Réunion après l\'abolition de l\'esclavage ?',
    correctAnswer: 'Les engagés indiens', incorrectAnswers: ['Les engagés chinois', 'Les engagés malgaches', 'Les engagés vietnamiens'] },

  // ── Photos — monuments mondiaux connus ───────────────────────────────────
  { id: 'ph001', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tour_Eiffel_Wikimedia_Commons.jpg',
    text: 'Quel est ce monument parisien symbole de la France ?',
    correctAnswer: 'La Tour Eiffel', incorrectAnswers: ['Le Sacré-Cœur', 'La Tour Montparnasse', 'L\'Arc de Triomphe'],
    trivia: 'La Tour Eiffel a été construite pour l\'Exposition universelle de 1889. Elle était le monument le plus haut du monde jusqu\'en 1930.' },
  { id: 'ph002', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kheops-Pyramid.jpg',
    text: 'Cette pyramide est la seule des Sept Merveilles du monde antique encore debout. Comment s\'appelle-t-elle ?',
    correctAnswer: 'La Grande Pyramide de Gizeh', incorrectAnswers: ['La Pyramide de Djéser', 'La Pyramide de Khéphren', 'La Pyramide de Mykérinos'],
    trivia: 'Construite vers 2560 av. J.-C., la Grande Pyramide est restée la plus haute structure humaine pendant près de 3 800 ans.' },
  { id: 'ph003', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Parthenon_in_Athens.jpg',
    text: 'Ce temple dorique du Ve siècle av. J.-C. trône sur quel site athénien classé à l\'UNESCO ?',
    correctAnswer: 'L\'Acropole d\'Athènes', incorrectAnswers: ['L\'Agora antique', 'L\'Olympion', 'Le Théâtre d\'Épidaure'],
    trivia: 'Le Parthénon a servi tour à tour de temple, d\'église chrétienne, de mosquée, puis de poudrière — ce qui explique son explosion partielle en 1687.' },
  { id: 'ph004', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Colosseum_in_Rome,_Italy_-_April_2007.jpg',
    text: 'Quel est ce monument emblématique de la Rome antique ?',
    correctAnswer: 'Le Colisée', incorrectAnswers: ['Le Panthéon', 'Le Circus Maximus', 'Les Thermes de Caracalla'],
    trivia: 'Le Colisée pouvait accueillir entre 50 000 et 80 000 spectateurs. Son vrai nom est l\'Amphithéâtre Flavien.' },
  { id: 'ph005', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Taj_Mahal,_Agra,_India_edit3.jpg',
    text: 'Ce mausolée en marbre blanc a été construit par l\'empereur moghol Shah Jahan. Dans quelle ville indienne se trouve-t-il ?',
    correctAnswer: 'Agra', incorrectAnswers: ['Delhi', 'Jaipur', 'Mumbai'],
    trivia: 'Shah Jahan fit construire le Taj Mahal en mémoire de son épouse Mumtaz Mahal, morte en 1631. Plus de 20 000 artisans y ont travaillé.' },
  { id: 'ph006', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Machu_Picchu,_Peru.jpg',
    text: 'Cette cité inca surnommée « la cité perdue des Andes » a été redécouverte en 1911. Quel est son nom ?',
    correctAnswer: 'Machu Picchu', incorrectAnswers: ['Cuzco', 'Tiwanaku', 'Chan Chan'],
    trivia: 'Construit vers 1450, Machu Picchu fut abandonné un siècle plus tard. Il n\'a jamais été « perdu » pour les populations locales — seulement pour l\'Occident.' },
  { id: 'ph007', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sagrada_Familia_01.jpg',
    text: 'Quel architecte catalan a commencé la construction de cette basilique à Barcelone en 1882 (encore inachevée) ?',
    correctAnswer: 'Antoni Gaudí', incorrectAnswers: ['Santiago Calatrava', 'Rafael Moneo', 'Enric Miralles'],
    trivia: 'Gaudí consacra les 40 dernières années de sa vie à la Sagrada Família. Il fut renversé par un tramway en 1926 et mourut trois jours plus tard.' },
  { id: 'ph008', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Clock_Tower_-_Palace_of_Westminster,_London_-_May_2007.jpg',
    text: 'Le surnom « Big Ben » désigne en réalité quelle partie de cette tour du Parlement britannique ?',
    correctAnswer: 'La cloche principale', incorrectAnswers: ['La tour elle-même', 'L\'horloge', 'La girouette'],
    trivia: 'La tour s\'appelle officiellement la Tour Elizabeth depuis 2012. La grande cloche Big Ben pèse 13,7 tonnes.' },
  { id: 'ph009', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Statue_of_Liberty,_NY.jpg',
    text: 'Quel pays a offert cette statue aux États-Unis pour célébrer leur centenaire d\'indépendance ?',
    correctAnswer: 'La France', incorrectAnswers: ['Le Royaume-Uni', 'L\'Italie', 'L\'Espagne'],
    trivia: 'Inaugurée en 1886, la Statue de la Liberté est l\'œuvre du sculpteur Frédéric Auguste Bartholdi. Sa structure métallique intérieure a été conçue par Gustave Eiffel.' },
  { id: 'ph010', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sydney_Opera_House_-_Dec_2008.jpg',
    text: 'Dans quelle ville australienne se trouve cet opéra aux toits en forme de coquilles ?',
    correctAnswer: 'Sydney', incorrectAnswers: ['Melbourne', 'Brisbane', 'Perth'],
    trivia: 'L\'Opéra de Sydney a été conçu par l\'architecte danois Jørn Utzon. Sa construction, initialement prévue pour 7 ans, en a pris 14 (1959-1973).' },
  { id: 'ph011', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Leaning_tower_of_pisa_2.jpg',
    text: 'Dans quelle ville italienne se trouve cette célèbre tour penchée ?',
    correctAnswer: 'Pise', incorrectAnswers: ['Florence', 'Sienne', 'Bologne'],
    trivia: 'La Tour de Pise penche à cause d\'un sous-sol trop mou d\'un côté. Des travaux de stabilisation menés entre 1990 et 2001 ont réduit l\'inclinaison de 44 cm.' },
  { id: 'ph012', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Arc_de_Triomphe_August_2010.jpg',
    text: 'Ce monument parisien abrite la tombe du Soldat Inconnu. Sur quelle avenue célèbre débouche-t-il ?',
    correctAnswer: 'Les Champs-Élysées', incorrectAnswers: ['Le boulevard Haussmann', 'L\'avenue de la Grande Armée', 'Le boulevard Périphérique'],
    trivia: 'L\'Arc de Triomphe fut commandé par Napoléon en 1806 après la victoire d\'Austerlitz, mais il ne fut achevé qu\'en 1836, sous Louis-Philippe.' },

  // ── Photos — monuments mondiaux peu connus ────────────────────────────────
  { id: 'ph013', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sigiriya_mirror_wall.jpg',
    text: 'Ce rocher-forteresse du Ve siècle, ancienne citadelle royale, se trouve dans quel pays asiatique ?',
    correctAnswer: 'Sri Lanka', incorrectAnswers: ['Inde', 'Myanmar', 'Thaïlande'],
    trivia: 'Sigiriya (« Rocher du Lion ») culmine à 180 m. Le roi Kashyapa y fit construire son palais entre 477 et 495 ap. J.-C. pour se protéger de son frère.' },
  { id: 'ph014', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Easter_Island_Ahu_Tongariki.jpg',
    text: 'Ces statues colossales de pierre ont été sculptées par le peuple Rapa Nui. Sur quelle île du Pacifique se trouvent-elles ?',
    correctAnswer: 'L\'Île de Pâques', incorrectAnswers: ['Tahiti', 'Les Marquises', 'Les Samoa'],
    trivia: 'Les moaïs pèsent en moyenne 14 tonnes. Comment les Rapa Nui les ont-ils transportés reste un mystère, bien que la théorie du « balancement » soit aujourd\'hui privilégiée.' },
  { id: 'ph015', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Borobudur-temple-compounds4.jpg',
    text: 'Ce temple bouddhiste du IXe siècle, le plus grand monument bouddhiste du monde, se trouve dans quel pays ?',
    correctAnswer: 'L\'Indonésie', incorrectAnswers: ['Le Cambodge', 'La Thaïlande', 'Le Myanmar'],
    trivia: 'Borobudur (île de Java) a été abandonné vers 1000 ap. J.-C., probablement après une éruption volcanique, et redécouvert sous les cendres en 1814 par Sir Thomas Stamford Raffles.' },
  { id: 'ph016', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/El_Castillo_Chichen_Itza.jpg',
    text: 'Cette pyramide maya-toltèque surnommée « El Castillo » est le cœur du site de Chichen Itza. Dans quel pays se trouve-t-elle ?',
    correctAnswer: 'Le Mexique', incorrectAnswers: ['Le Guatemala', 'Le Belize', 'Le Honduras'],
    trivia: 'À chaque équinoxe, le soleil crée une illusion de serpent ondulant le long de l\'escalier nord — un effet intentionnel des architectes mayas.' },
  { id: 'ph017', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bete_Giyorgis_church.jpg',
    text: 'Ces églises taillées dans le roc au XIIIe siècle sont surnommées la « Jérusalem de l\'Afrique ». Dans quelle ville d\'Éthiopie se trouvent-elles ?',
    correctAnswer: 'Lalibela', incorrectAnswers: ['Aksoum', 'Gondar', 'Addis-Abeba'],
    trivia: 'Les onze églises monolithiques de Lalibela ont été creusées d\'un seul bloc de roc volcanique. La légende dit que des anges ont aidé les ouvriers à les construire.' },
  { id: 'ph018', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Newgrange.jpg',
    text: 'Ce monument mégalithique irlandais (3200 av. J.-C.) est plus ancien que Stonehenge et que les Pyramides. Comment s\'appelle-t-il ?',
    correctAnswer: 'Newgrange', incorrectAnswers: ['Knowth', 'Dowth', 'Avebury'],
    trivia: 'Newgrange est conçu pour qu\'au solstice d\'hiver, les premiers rayons du soleil illuminent exactement la chambre intérieure pendant 17 minutes.' },
  { id: 'ph019', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Persepolis_Iran.jpg',
    text: 'Ces ruines de la capitale cérémonielle de l\'empire perse achéménide se trouvent dans quel pays ?',
    correctAnswer: 'L\'Iran', incorrectAnswers: ['L\'Irak', 'La Turquie', 'La Syrie'],
    trivia: 'Persépolis fut fondée par Darius Ier vers 518 av. J.-C. et brûlée par Alexandre le Grand en 330 av. J.-C., peut-être par vengeance pour l\'incendie de l\'Acropole.' },
  { id: 'ph020', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Angkor_Wat_from_the_air.JPG',
    text: 'Ce temple khmer du XIIe siècle est le plus grand édifice religieux du monde. Dans quel pays se trouve-t-il ?',
    correctAnswer: 'Le Cambodge', incorrectAnswers: ['Le Myanmar', 'La Thaïlande', 'L\'Indonésie'],
    trivia: 'Angkor Vat a été construit par le roi Suryavarman II entre 1113 et 1150. Son image figure sur le drapeau national cambodgien.' },
  { id: 'ph021', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Meteora_monasteries.jpg',
    text: 'Ces monastères orthodoxes perchés sur d\'immenses pitons rocheux de grès se trouvent dans quelle région de Grèce ?',
    correctAnswer: 'La Thessalie', incorrectAnswers: ['La Macédoine', 'L\'Épire', 'La Béotie'],
    trivia: 'Météora signifie « suspendu dans les airs » en grec. Les premiers moines s\'y hissaient dans des filets ou par des échelles amovibles pour se protéger des invasions.' },
  { id: 'ph022', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Old_Bridge_in_Mostar.jpg',
    text: 'Ce pont reconstruit après la guerre de Bosnie est le symbole de réconciliation de quelle ville ?',
    correctAnswer: 'Mostar', incorrectAnswers: ['Sarajevo', 'Banja Luka', 'Tuzla'],
    trivia: 'Le Vieux Pont (Stari Most) de Mostar fut construit par les Ottomans en 1566. Détruit en 1993 pendant la guerre, il a été reconstruit à l\'identique et inauguré en 2004.' },
  { id: 'ph023', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mont-Saint-Michel_in_Normandy,_France.jpg',
    text: 'Cet îlot-monastère normand est accessible à pied à marée basse. Comment s\'appelle-t-il ?',
    correctAnswer: 'Le Mont Saint-Michel', incorrectAnswers: ['L\'Île Saint-Honorat', 'L\'Île de Bréhat', 'Belle-Île-en-Mer'],
    trivia: 'La communauté bénédictine du Mont Saint-Michel remonte à 966. La marée y monte à la vitesse d\'un cheval au galop — jusqu\'à 10 km/h.' },
  { id: 'ph024', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Alhambra-4.jpg',
    text: 'Ce palais nasride du XIVe siècle est le joyau de l\'architecture hispano-mauresque. Dans quelle ville espagnole se trouve-t-il ?',
    correctAnswer: 'Grenade', incorrectAnswers: ['Séville', 'Cordoue', 'Malaga'],
    trivia: 'L\'Alhambra (« la rouge » en arabe) fut la dernière grande forteresse maure de la péninsule ibérique. En 1492, les Rois Catholiques en prirent possession, achevant la Reconquête.' },

  // ── Photos — animaux connus ───────────────────────────────────────────────
  { id: 'ph025', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Grosser_Panda.JPG',
    text: 'Quel est le régime alimentaire principal de cet animal emblématique de Chine, symbole du WWF ?',
    correctAnswer: 'Le bambou', incorrectAnswers: ['Les insectes', 'Le poisson', 'Les fruits'],
    trivia: 'Le grand panda passe 12 à 16 heures par jour à manger et ingère jusqu\'à 40 kg de bambou quotidiennement, car son système digestif assimile mal la cellulose.' },
  { id: 'ph026', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Quokka_(Setonix_brachyurus).jpg',
    text: 'Ce petit marsupial australien est célèbre pour son expression faciale qui ressemble à un sourire. Comment s\'appelle-t-il ?',
    correctAnswer: 'Le quokka', incorrectAnswers: ['Le wombat', 'Le potoroo', 'Le numbat'],
    trivia: 'Le quokka vit principalement sur l\'île Rottnest, en Australie-Occidentale. Son nom vient de « gwaga » en nyungar, la langue des Aborigènes locaux.' },
  { id: 'ph027', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Axolotl_ganz.jpg',
    text: 'Cet amphibien mexicain a la capacité unique de régénérer ses membres, son cœur et même des parties de son cerveau. Comment s\'appelle-t-il ?',
    correctAnswer: 'L\'axolotl', incorrectAnswers: ['Le triton', 'La salamandre de feu', 'Le crapaud cornu'],
    trivia: 'L\'axolotl est un amphibien « néoténique » : il conserve ses branchies et reste en stade larvaire toute sa vie. Il est en danger critique d\'extinction dans la nature.' },
  { id: 'ph028', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Okapi2.jpg',
    text: 'Cet animal ressemble à un zèbre rayé sur les pattes, mais il est en réalité le plus proche parent de quel animal ?',
    correctAnswer: 'La girafe', incorrectAnswers: ['Le zèbre', 'L\'antilope', 'Le cheval'],
    trivia: 'L\'okapi ne fut décrit scientifiquement qu\'en 1901. Il vit uniquement dans la forêt tropicale du Congo. Sa langue mesure 30 cm et peut lécher ses propres oreilles.' },
  { id: 'ph029', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Emperor_penguins.jpg',
    text: 'Ce manchot est le plus grand et le plus lourd de toutes les espèces de manchots. Lequel est-il ?',
    correctAnswer: 'Le manchot empereur', incorrectAnswers: ['Le manchot royal', 'Le manchot de Humboldt', 'Le gorfou sauteur'],
    trivia: 'Le manchot empereur couve son œuf sur ses pattes, sous un repli de peau, par -60 °C et des vents à 200 km/h en Antarctique. Les mâles jeûnent jusqu\'à 4 mois.' },
  { id: 'ph030', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Flamingo_-_melbourne_zoo.jpg',
    text: 'Pourquoi le flamant rose est-il rose ?',
    correctAnswer: 'À cause des caroténoïdes dans son alimentation (crevettes, algues)', incorrectAnswers: ['C\'est sa couleur génétique naturelle', 'Le soleil colore ses plumes', 'Il absorbe des pigments dans l\'eau'],
    trivia: 'Un flamant rose nourri sans caroténoïdes devient blanc. Les poussins naissent blancs et ne deviennent roses qu\'après deux ans.' },
  { id: 'ph031', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Komodo_dragon_(Varanus_komodoensis)_Rinca.jpg',
    text: 'Ce grand lézard carnivore est le plus grand lézard vivant. Dans quel archipel indonésien vit-il exclusivement ?',
    correctAnswer: 'Les îles de la Sonde (Komodo, Flores, Rinca…)', incorrectAnswers: ['Les Philippines', 'Bornéo', 'Sumatra'],
    trivia: 'Le dragon de Komodo peut atteindre 3 m et peser 70 kg. Sa salive contient des bactéries mortelles et ses glandes produisent un venin anticoagulant.' },
  { id: 'ph032', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Narwhal_(Monodon_monoceros).jpg',
    text: 'La longue « corne » de cet animal marin arctique est en réalité quoi ?',
    correctAnswer: 'Une dent (canine gauche hypertrophiée)', incorrectAnswers: ['Une corne osseuse', 'Un appendice nasal', 'Une nageoire modifiée'],
    trivia: 'La défense du narval peut atteindre 3 m et est spiralée dans le sens antihoraire. Les Vikings la vendaient comme « corne de licorne » à prix d\'or.' },
  { id: 'ph033', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Giant_anteater_Braz.jpg',
    text: 'Cet animal peut ingérer jusqu\'à 35 000 fourmis ou termites par jour grâce à sa longue langue collante. Comment s\'appelle-t-il ?',
    correctAnswer: 'Le fourmilier géant', incorrectAnswers: ['Le tamandua', 'L\'oryctérope', 'L\'échidné'],
    trivia: 'Le fourmilier géant n\'a pas de dents. Il avale ses proies entières et les broie dans son estomac musculeux. Ses griffes sont si puissantes qu\'il peut déchirer des termitières en béton.' },

  // ── Photos — animaux peu connus ───────────────────────────────────────────
  { id: 'ph034', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Saiga_antelope_(Saiga_tatarica)_male_(10684015833).jpg',
    text: 'Cette antilope au nez étrangement bombé ressemble à une créature préhistorique. Sur quel continent vit-elle ?',
    correctAnswer: 'En Asie centrale (Kazakhstan, Russie)', incorrectAnswers: ['En Afrique subsaharienne', 'En Amérique du Sud', 'En Asie du Sud-Est'],
    trivia: 'Le saïga est apparu il y a plus de 250 000 ans. Son nez en trompe filtre la poussière en été et réchauffe l\'air froid en hiver. Sa population a chuté de 95 % en 15 ans.' },
  { id: 'ph035', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Litocranius_walleri.jpg',
    text: 'Cette antilope africaine peut se dresser sur ses pattes arrière pour brouter les feuilles les plus hautes. Comment s\'appelle-t-elle ?',
    correctAnswer: 'Le gerenuk', incorrectAnswers: ['Le dik-dik', 'L\'impala', 'Le kob'],
    trivia: 'Le gerenuk (« cou de girafe » en somali) peut rester debout sur ses pattes arrière pendant de longues minutes. Il ne boit jamais d\'eau, tirant toute son hydratation de sa nourriture.' },
  { id: 'ph036', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Shoebill_Balaeniceps_rex.jpg',
    text: 'Ce grand oiseau africain d\'1,2 m de haut chasse des grenouilles, des serpents et même de petits crocodiles. Comment s\'appelle-t-il ?',
    correctAnswer: 'Le bec-en-sabot', incorrectAnswers: ['Le marabout', 'Le jabiru', 'La cigogne d\'Abdim'],
    trivia: 'Le bec-en-sabot (Balaeniceps rex) possède l\'un des plus grands becs du monde des oiseaux. Il peut rester immobile pendant des heures à attendre sa proie dans les marais.' },
  { id: 'ph037', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Aye-aye_(Daubentonia_madagascariensis).jpg',
    text: 'Ce primate malgache nocturne possède un doigt très allongé pour extraire des larves du bois. Comment s\'appelle-t-il ?',
    correctAnswer: 'L\'aye-aye', incorrectAnswers: ['L\'indri', 'Le lémurien catta', 'Le propithèque soyeux'],
    trivia: 'L\'aye-aye est le seul primate à utiliser l\'écholocation. Dans les traditions malgaches, il est parfois considéré comme un présage de mort. Son 3e doigt est extrêmement fin et articulé.' },
  { id: 'ph038', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sunbear_david.jpg',
    text: 'Cet ours tropical est le plus petit et le moins connu de tous les ours. Dans quelle région du monde vit-il ?',
    correctAnswer: 'En Asie du Sud-Est', incorrectAnswers: ['En Amérique du Sud', 'En Afrique centrale', 'En Asie centrale'],
    trivia: 'L\'ours malais (ou ours du soleil) ne dépasse pas 65 kg. Sa tache dorée sur la poitrine lui vaut son nom. Sa langue peut mesurer 25 cm et extraire le miel avec précision.' },
  { id: 'ph039', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pangolin_on_a_rock_(Cropped).jpg',
    text: 'Cet animal est le seul mammifère entièrement recouvert d\'écailles de kératine. Comment s\'appelle-t-il ?',
    correctAnswer: 'Le pangolin', incorrectAnswers: ['L\'armadillo', 'L\'échidné', 'Le tatou géant'],
    trivia: 'Le pangolin est l\'animal sauvage le plus braconné au monde. Ses écailles, utilisées en médecine traditionnelle asiatique, sont en réalité faites de la même kératine que nos ongles.' },
  { id: 'ph040', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kakapo_from_NLNZ.jpg',
    text: 'Ce perroquet néo-zélandais nocturne est le seul perroquet incapable de voler. Comment s\'appelle-t-il ?',
    correctAnswer: 'Le kakapo', incorrectAnswers: ['Le kea', 'Le kaka', 'Le perroquet vaza'],
    trivia: 'Le kakapo est le plus lourd des perroquets (jusqu\'à 4 kg) et le seul à avoir un système de reproduction à lek. Il ne se reproduit que les années où le rimu fructifie abondamment, ce qui peut espacer les naissances de plusieurs années.' },

  // ── Photos — monuments et paysages de La Réunion ─────────────────────────
  { id: 'ph041', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Piton_de_la_Fournaise.jpg',
    text: 'Ce volcan bouclier actif culmine à 2 632 m sur l\'île de La Réunion. Comment s\'appelle-t-il ?',
    correctAnswer: 'Le Piton de la Fournaise', incorrectAnswers: ['Le Piton des Neiges', 'Le Maïdo', 'Le Grand Bénare'],
    trivia: 'Le Piton de la Fournaise est l\'un des volcans les plus actifs du monde avec en moyenne une éruption tous les 9 mois. Il produit des coulées de lave basaltique qui atteignent parfois l\'océan.' },
  { id: 'ph042', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mafate_le_Maido.jpg',
    text: 'Ce cirque de La Réunion est accessible uniquement à pied ou en hélicoptère. Lequel est-il ?',
    correctAnswer: 'Mafate', incorrectAnswers: ['Cilaos', 'Salazie', 'Grand Ilet'],
    trivia: 'Mafate est l\'un des rares endroits habités de France où l\'on ne peut accéder qu\'à pied ou par les airs. Ses « îlets » isolés abritent environ 1 000 habitants permanents.' },
  { id: 'ph043', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Voile_de_la_mariee,_Salazie.jpg',
    text: 'Cette cascade iconique du cirque de Salazie à La Réunion se nomme le « Voile de la… » ?',
    correctAnswer: 'Mariée', incorrectAnswers: ['Fée', 'Vierge', 'Dentelle'],
    trivia: 'Le Voile de la Mariée à Salazie (La Réunion) plonge de plusieurs centaines de mètres. Salazie est surnommé « l\'île dans l\'île » pour son isolement relatif et son microclimat humide.' },
  { id: 'ph044', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cilaos_vue_aerienne.jpg',
    text: 'Ce cirque réunionnais est réputé pour son vin et son centre thermal. Comment s\'appelle-t-il ?',
    correctAnswer: 'Cilaos', incorrectAnswers: ['Salazie', 'Mafate', 'Hell-Bourg'],
    trivia: 'Cilaos est le seul endroit des DOM-TOM à produire du vin. Ses sources d\'eau thermale sont utilisées depuis le XIXe siècle. Son lentille (légumineuse locale) est renommée.' },
  { id: 'ph045', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Saint-Denis_de_La_Reunion_-_Cathedrale_Saint-Denis.jpg',
    text: 'Cette cathédrale est le principal édifice religieux de la capitale de La Réunion. Dans quelle ville se trouve-t-elle ?',
    correctAnswer: 'Saint-Denis', incorrectAnswers: ['Saint-Paul', 'Saint-Pierre', 'Saint-Louis'],
    trivia: 'La cathédrale de Saint-Denis a été construite entre 1829 et 1832. Elle est dédiée à saint Denis et son style mêle néoclassicisme et influences créoles.' },
  { id: 'ph046', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Grand_Bassin_Reunion.jpg',
    text: 'Ce bassin perdu au cœur des hauts de La Réunion n\'est accessible qu\'après plusieurs heures de marche. Comment s\'appelle-t-il ?',
    correctAnswer: 'Grand Bassin', incorrectAnswers: ['Bassin Bleu', 'Bassin des Cormorans', 'Bassin La Paix'],
    trivia: 'Grand Bassin est l\'un des sites les plus reculés de La Réunion. On y accède par le GR R2 depuis les Makes. Un téléphérique de ravitaillement dessert ses quelques dizaines d\'habitants.' },

  // ── Photos — faune de La Réunion ─────────────────────────────────────────
  { id: 'ph047', category: 'photo', difficulty: 'easy',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Phaethon_rubricauda_1_(Shankbon).jpg',
    text: 'Cet oiseau blanc aux longues plumes caudales rouges plane souvent au-dessus des falaises de La Réunion. Comment s\'appelle-t-il familièrement ?',
    correctAnswer: 'Le paille-en-queue', incorrectAnswers: ['Le papangue', 'Le tuit-tuit', 'L\'oiseau-lunettes'],
    trivia: 'Le paille-en-queue (Phaethon rubricauda) tire son nom créole de ses deux longues plumes rouges en forme de paille. Il niche dans les falaises et les creux de rochers.' },
  { id: 'ph048', category: 'photo', difficulty: 'medium',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Circus_maillardi,_male.jpg',
    text: 'Cet oiseau rapace endémique de La Réunion est en voie d\'extinction et classé au patrimoine de l\'UNESCO. Quel est son nom créole ?',
    correctAnswer: 'Le papangue', incorrectAnswers: ['Le paille-en-queue', 'Le tuit-tuit', 'Le merle de La Réunion'],
    trivia: 'Le papangue (Circus maillardi) est le seul rapace endémique de La Réunion. Sa population ne dépasse pas 400 individus. Il est menacé par la déforestation et les espèces introduites.' },
  { id: 'ph049', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Foudia_rubra.jpg',
    text: 'Ce petit oiseau rouge endémique de La Réunion est en danger critique d\'extinction. Comment l\'appelle-t-on localement ?',
    correctAnswer: 'Le tuit-tuit (Foudi de La Réunion)', incorrectAnswers: ['Le cardinal de La Réunion', 'L\'oiseau-lunettes', 'Le merle'],
    trivia: 'Le tuit-tuit (Foudia rubra) est l\'un des oiseaux les plus menacés au monde avec moins de 200 individus estimés. Il ne vit que dans les forêts de tamarindes de montagne.' },
  { id: 'ph050', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pterodroma_baraui.jpg',
    text: 'Ce pétrel endémique de La Réunion niche dans les falaises du Piton des Neiges. Comment s\'appelle-t-il ?',
    correctAnswer: 'Le pétrel de Barau', incorrectAnswers: ['Le pétrel noir de Bourbon', 'Le puffin tropical', 'Le damier du Cap'],
    trivia: 'Le pétrel de Barau (Pterodroma baraui) passe la majeure partie de sa vie en mer. Il ne vient à terre que pour nidifier. Son cri nocturne guide les Réunionnais dans les hauts : « petite bête ! »' },
  { id: 'ph051', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Zosterops_borbonicus.jpg',
    text: 'Cet oiseau à l\'œil cerclé de blanc est surnommé « oiseau-lunettes » à La Réunion. Quel est son nom scientifique de genre ?',
    correctAnswer: 'Zostérops (Zosterops borbonicus)', incorrectAnswers: ['Pycnonotus', 'Hypsipetes', 'Terpsiphone'],
    trivia: 'Le zostérops de La Réunion (Zosterops borbonicus) est l\'un des oiseaux les plus communs de l\'île en altitude. Il joue un rôle clé dans la pollinisation et la dispersion des graines des forêts endémiques.' },
  { id: 'ph052', category: 'photo', difficulty: 'hard',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Phelsuma_borbonica_borbonica.jpg',
    text: 'Ce gecko à la robe vert vif est endémique de La Réunion. Comment s\'appelle-t-il ?',
    correctAnswer: 'Le gecko vert de La Réunion (Phelsuma borbonica)', incorrectAnswers: ['Le gecko de Madagascar (Phelsuma madagascariensis)', 'Le gecko de Maurice (Phelsuma guimbeaui)', 'Le gecko à points bleus (Phelsuma cepediana)'],
    trivia: 'Phelsuma borbonica est l\'un des rares geckos diurnes de La Réunion. Il se nourrit de nectar et de petits insectes. Ses cousins malgaches sont très prisés dans le commerce illégal d\'animaux exotiques.' },

  // ── Enfants (8-12 ans) ────────────────────────────────────────────────────
  { id: 'kid01', category: 'children', difficulty: 'easy',
    text: 'Quelle est la couleur du ciel par beau temps ?',
    correctAnswer: 'Bleu', incorrectAnswers: ['Rouge', 'Vert', 'Jaune'] },
  { id: 'kid02', category: 'children', difficulty: 'easy',
    text: 'Combien y a-t-il de jours dans une semaine ?',
    correctAnswer: '7', incorrectAnswers: ['5', '6', '8'] },
  { id: 'kid03', category: 'children', difficulty: 'easy',
    text: 'Quel animal est le roi de la jungle ?',
    correctAnswer: 'Le lion', incorrectAnswers: ['Le tigre', 'L\'éléphant', 'Le crocodile'] },
  { id: 'kid04', category: 'children', difficulty: 'easy',
    text: 'De quelle couleur est une banane mûre ?',
    correctAnswer: 'Jaune', incorrectAnswers: ['Rouge', 'Bleue', 'Verte'] },
  { id: 'kid05', category: 'children', difficulty: 'easy',
    text: 'Combien de pattes a une araignée ?',
    correctAnswer: '8', incorrectAnswers: ['6', '4', '10'] },
  { id: 'kid06', category: 'children', difficulty: 'easy',
    text: 'Quel est le plus grand animal terrestre ?',
    correctAnswer: 'L\'éléphant', incorrectAnswers: ['La girafe', 'L\'hippopotame', 'Le rhinocéros'] },
  { id: 'kid07', category: 'children', difficulty: 'easy',
    text: 'Combien font 5 + 3 ?',
    correctAnswer: '8', incorrectAnswers: ['7', '9', '6'] },
  { id: 'kid08', category: 'children', difficulty: 'easy',
    text: 'De quelle couleur est une tomate mûre ?',
    correctAnswer: 'Rouge', incorrectAnswers: ['Jaune', 'Verte', 'Orange'] },
  { id: 'kid09', category: 'children', difficulty: 'easy',
    text: 'Quel animal fait "coin coin" ?',
    correctAnswer: 'Le canard', incorrectAnswers: ['La poule', 'La vache', 'Le mouton'] },
  { id: 'kid10', category: 'children', difficulty: 'easy',
    text: 'Dans quel film retrouve-t-on le personnage de Simba ?',
    correctAnswer: 'Le Roi Lion', incorrectAnswers: ['La Belle et la Bête', 'Aladdin', 'Bambi'] },
  { id: 'kid11', category: 'children', difficulty: 'medium',
    text: 'Quelle est la capitale de la France ?',
    correctAnswer: 'Paris', incorrectAnswers: ['Lyon', 'Marseille', 'Nice'] },
  { id: 'kid12', category: 'children', difficulty: 'medium',
    text: 'Combien y a-t-il de mois dans une année ?',
    correctAnswer: '12', incorrectAnswers: ['10', '11', '13'] },
  { id: 'kid13', category: 'children', difficulty: 'medium',
    text: 'Quel est l\'animal le plus rapide du monde ?',
    correctAnswer: 'Le guépard', incorrectAnswers: ['Le lion', 'L\'aigle', 'Le cheval'] },
  { id: 'kid14', category: 'children', difficulty: 'medium',
    text: 'Combien de côtés a un triangle ?',
    correctAnswer: '3', incorrectAnswers: ['4', '5', '6'] },
  { id: 'kid15', category: 'children', difficulty: 'medium',
    text: 'Quelle planète est la plus proche du Soleil ?',
    correctAnswer: 'Mercure', incorrectAnswers: ['Vénus', 'Mars', 'Terre'] },
  { id: 'kid16', category: 'children', difficulty: 'medium',
    text: 'Quel est le sport où l\'on utilise une raquette et un volant ?',
    correctAnswer: 'Le badminton', incorrectAnswers: ['Le tennis', 'Le squash', 'Le ping-pong'] },
  { id: 'kid17', category: 'children', difficulty: 'medium',
    text: 'De quel pays vient le sushi ?',
    correctAnswer: 'Du Japon', incorrectAnswers: ['De Chine', 'De Corée', 'De Thaïlande'] },
  { id: 'kid18', category: 'children', difficulty: 'medium',
    text: 'Comment appelle-t-on le petit de la vache ?',
    correctAnswer: 'Le veau', incorrectAnswers: ['Le poulain', 'L\'agneau', 'Le chiot'] },
  { id: 'kid19', category: 'children', difficulty: 'medium',
    text: 'Quelle est la couleur obtenue en mélangeant bleu et jaune ?',
    correctAnswer: 'Vert', incorrectAnswers: ['Orange', 'Violet', 'Rose'] },
  { id: 'kid20', category: 'children', difficulty: 'medium',
    text: 'Quel personnage de dessin animé vit dans un ananas sous la mer ?',
    correctAnswer: 'Bob l\'éponge', incorrectAnswers: ['Nemo', 'Patrick', 'Sandy'] },
  { id: 'kid21', category: 'children', difficulty: 'hard',
    text: 'Combien de continents y a-t-il sur Terre ?',
    correctAnswer: '7', incorrectAnswers: ['5', '6', '8'] },
  { id: 'kid22', category: 'children', difficulty: 'hard',
    text: 'Quel est le plus long fleuve du monde ?',
    correctAnswer: 'Le Nil', incorrectAnswers: ['L\'Amazone', 'Le Mississippi', 'Le Yang Tsé Kiang'] },
  { id: 'kid23', category: 'children', difficulty: 'hard',
    text: 'Dans quel pays se trouve la Grande Muraille ?',
    correctAnswer: 'En Chine', incorrectAnswers: ['En Inde', 'Au Japon', 'En Mongolie'] },
  { id: 'kid24', category: 'children', difficulty: 'hard',
    text: 'Combien d\'os possède le corps humain adulte ?',
    correctAnswer: '206', incorrectAnswers: ['186', '226', '196'] },
  { id: 'kid25', category: 'children', difficulty: 'hard',
    text: 'Quelle est la planète la plus grande du système solaire ?',
    correctAnswer: 'Jupiter', incorrectAnswers: ['Saturne', 'Uranus', 'Neptune'] },
];
