// ============================================================
// pyramide/data.js — Données brutes (listes de mots)
// La logique se trouve dans words.js
// ============================================================



// ── MANCHE 2 : Ping-Pong (liste plate) ──────────────────────
// Source : pyramide/mots/famille.json (858 mots)
export const R2_WORDS = [
  '14-Juillet',
  '1er-Avril',
  'Abeille',
  'Abricot',
  'Acrobate',
  'Acteur',
  'Aéroport',
  'Agneau',
  'Agriculteur',
  'Aigle',
  'Aiguille',
  'Ail',
  'Aile',
  'Air',
  'Albert Einstein',
  'Alice au pays des merveilles',
  'Allumette',
  'Amazone',
  'Ambulance',
  'Ampoule',
  'Ananas',
  'Âne',
  'Animal',
  'Anniversaire',
  'Anubis',
  'Aphrodite',
  'Apiculteur',
  'Apollon',
  'Appareil dentaire',
  'Appareil photographique',
  'Aquarium',
  'Araignée',
  'Arbre',
  'Arc-en-ciel',
  'Archéologue',
  'Architecte',
  'Arès',
  'Arête',
  'Argent',
  'Arrosoir',
  'Artémis',
  'Ascenseur',
  'Asperge',
  'Aspirateur',
  'Aspirine',
  'Assiette',
  'Astérix',
  'Astronaute',
  'Astronomie',
  'Athéna',
  'Atterrir',
  'Au clair de la lune',
  'Aubergine',
  'Automne',
  'Autruche',
  'Avion',
  'Bague',
  'Baguette',
  'Bâiller',
  'Balai',
  'Balançoire',
  'Baleine',
  'Baleine bleue',
  'Balle',
  'Ballon',
  'Banane',
  'Banc',
  'Bande dessinée',
  'Barbe',
  'Barque',
  'Barrette',
  'Basket-ball',
  'Bateau',
  'Bâton',
  'Bavoir',
  'Bec',
  'Béquille',
  'Berger',
  'Berger allemand',
  'Bermuda',
  'Beurre',
  'Biberon',
  'Bibliothèque',
  'Bifteck',
  'Big Ben',
  'Bijou',
  'Bijoutier',
  'Bille',
  'Billet',
  'Biologie',
  'Biscuit',
  'Bison',
  'Blé',
  'Bœuf',
  'Boisson',
  'Bol',
  'Bonbon',
  'Bonnet',
  'Boomerang',
  'Botte',
  'Bouche',
  'Boucher',
  'Boucherie',
  'Bouchon',
  'Boue',
  'Bouée',
  'Boulanger',
  'Boulangerie',
  'Bouteille',
  'Bouton',
  'Bracelet',
  'Bras',
  'Bretelle',
  'Brocoli',
  'Brosse à dents',
  'Brouette',
  'Bugs Bunny',
  'Bureau',
  'Bus',
  'Cabane',
  'Cadeau',
  'Cadenas',
  'Café',
  'Cafetière',
  'Cage',
  'Cagoule',
  'Caillou',
  'Calculette',
  'Calendrier',
  'Caméléon',
  'Caméra',
  'Camion',
  'Camping-car',
  'Canapé',
  'Canard',
  'Caniche',
  'Canne à pêche',
  'Car',
  'Caravane',
  'Carnaval',
  'Carotte',
  'Cartable',
  'Casque',
  'Casquette',
  'Casserole',
  'Castor',
  'Ceinture',
  'Cendrillon',
  'Centaure',
  'Cerbère',
  'Cerceau',
  'Céréale',
  'Cerf',
  'Cerf-volant',
  'Cerise',
  'Cerveau',
  'Chaise',
  'Chameau',
  'Champignon',
  'Chandeleur',
  'Chanter',
  'Chanteur',
  'Chapeau',
  'Chariot',
  'Charlemagne',
  'Charpentier',
  'Chasseur',
  'Chat',
  'Châtaigne',
  'Château',
  'Chaton',
  'Chaussette',
  'Chaussettes',
  'Chausson',
  'Chaussure',
  'Chauve-souris',
  'Chemise',
  'Chenille',
  'Chercheur d\'or',
  'Cheval',
  'Cheval de Troie',
  'Chevaliers de la Table ronde',
  'Cheveu',
  'Cheville',
  'Chèvre',
  'Chien',
  'Chiffon',
  'Chiot',
  'Chips',
  'Chirurgien',
  'Chocolat',
  'Chou',
  'Chouette',
  'Christophe Colomb',
  'Chuchoter',
  'Cigogne',
  'Cil',
  'Ciseaux',
  'Citron',
  'Citrouille',
  'Clé',
  'Clémentine',
  'Cléopâtre',
  'Clignotant',
  'Clou',
  'Clown',
  'Coccinelle',
  'Cochon',
  'Cocotte',
  'Cœur',
  'Coffre',
  'Coiffeur',
  'Collant',
  'Colle',
  'Collier',
  'Colorier',
  'Concombre',
  'Conduire',
  'Confiture',
  'Console de jeu',
  'Coq',
  'Coquelicot',
  'Coquillage',
  'Corbeau',
  'Corbeille',
  'Corde',
  'Cou',
  'Coude',
  'Coudre',
  'Couette',
  'Couronne',
  'Coussin',
  'Couteau',
  'Couver',
  'Couvercle',
  'Couverture',
  'Cow-boy',
  'Crabe',
  'Cracher',
  'Craie',
  'Crapaud',
  'Cravate',
  'Crayon',
  'Crèche',
  'Crème solaire',
  'Crêpe',
  'Creuser',
  'Crevette',
  'Crochet',
  'Crocodile',
  'Croissant',
  'Cronos',
  'Croûte',
  'Cube',
  'Cuillère',
  'Cuisinier',
  'Cuisse',
  'Culotte',
  'Cyclisme',
  'Cyclope',
  'Cygne',
  'Danser',
  'Dauphin',
  'Dé',
  'Déchirer',
  'Déguisement',
  'Dent',
  'Dentifrice',
  'Dentiste',
  'Dessert',
  'Diamant',
  'Diane',
  'Dictionnaire',
  'Dindon',
  'Dînette',
  'Dinosaure',
  'Dionysos',
  'Doigt',
  'Domino',
  'Dompteur',
  'Donald Duck',
  'Dormir',
  'Dos',
  'Dragon',
  'Drap',
  'Dromadaire',
  'Eau',
  'Écharpe',
  'Échasse',
  'Échecs',
  'Échelle',
  'École',
  'École maternelle',
  'Écran',
  'Écrire',
  'Écureuil',
  'Égypte',
  'Élastique',
  'Éléphant',
  'Elfe',
  'Empire State Building',
  'Endive',
  'Entonnoir',
  'Enveloppe',
  'Épaule',
  'Épingle',
  'Épiphanie',
  'Éponge',
  'Escalier mécanique',
  'Escargot',
  'Escrime',
  'Espagne',
  'Essence',
  'États-Unis',
  'Été',
  'Étoile',
  'Étoile de mer',
  'Étoile filante',
  'Everest',
  'Facteur',
  'Fantôme',
  'Farine',
  'Fauteuil',
  'Fauteuil roulant',
  'Fée',
  'Fer à repasser',
  'Ferme',
  'Fesse',
  'Fête de la musique',
  'Fête des grands-mères',
  'Fête des mères',
  'Fête des pères',
  'Feutre',
  'Fève',
  'Ficelle',
  'Fièvre',
  'Fil',
  'Fille',
  'Flamant rose',
  'Fleur',
  'Fleuriste',
  'Flûte traversière',
  'Football',
  'Forgeron',
  'Fossile',
  'Four',
  'Fourchette',
  'Fourmi',
  'Fraise',
  'Framboise',
  'France',
  'Frein',
  'Frisbee',
  'Frites',
  'Fromage',
  'Front',
  'Fruit',
  'Fusée',
  'Fusée spatiale',
  'Gaïa',
  'Galère',
  'Galette',
  'Gandhi',
  'Gant',
  'Garage',
  'Garçon',
  'Gardien',
  'Gare',
  'Gargamel',
  'Gâteau',
  'Gaulois',
  'Géant',
  'Genou',
  'Géologie',
  'Girafe',
  'Glaçon',
  'Gobelet',
  'Golf',
  'Gomme',
  'Gorille',
  'Grande Muraille de Chine',
  'Grèce',
  'Grenouille',
  'Griffe',
  'Groseille',
  'Grotte',
  'Grue',
  'Gruyère',
  'Guépard',
  'Guêpe',
  'Guirlande',
  'Gymnase',
  'Gymnastique',
  'Hadès',
  'Halloween',
  'Hamster',
  'Handball',
  'Haricot vert',
  'Hélicoptère',
  'Héphaïstos',
  'Héra',
  'Héraclès',
  'Herbe',
  'Hérisson',
  'Hermès',
  'Hibou',
  'Hippocampe',
  'Hippopotame',
  'Hirondelle',
  'Hiver',
  'Hockey sur glace',
  'Hôpital',
  'Hoquet',
  'Horloge',
  'Horus',
  'Hôtel',
  'Huile',
  'Husky',
  'Icare',
  'Idéfix',
  'Imprimante',
  'Infirmier',
  'Informaticien',
  'Insecte',
  'Italie',
  'Jambe',
  'Jambon',
  'Janus',
  'Japon',
  'Jeanne d\'Arc',
  'Jolly Jumper',
  'Jongler',
  'Jongleur',
  'Joue',
  'Journaliste',
  'Journée internationale des femmes',
  'Judo',
  'Jumelles',
  'Jument',
  'Jupe',
  'Jus d\'orange',
  'Kangourou',
  'Karaté',
  'Ketchup',
  'Kilt',
  'Kiwi',
  'La Reine des neiges',
  'La Schtroumpfette',
  'Lacet',
  'Lait',
  'Lancer du disque',
  'Langue',
  'Lapin',
  'Larme',
  'Las Vegas',
  'Lave-linge',
  'Le Capitaine Haddock',
  'Le Grand Schtroumpf',
  'Le Marsupilami',
  'Le Monde de Nemo',
  'Le Petit Prince',
  'Le Roi lion',
  'Le Schtroumpf à lunettes',
  'Léopard',
  'Les Schtroumpfs',
  'Lèvre',
  'Lèvres',
  'Lézard',
  'Libellule',
  'Libraire',
  'Licorne',
  'Lièvre',
  'Limace',
  'Lion',
  'Lire',
  'Lit',
  'Livre',
  'Louche',
  'Loup',
  'Loupe',
  'Loup-Garou',
  'Lucky Luke',
  'Luge',
  'Lune',
  'Lunettes',
  'Lunettes de soleil',
  'Lutin',
  'Maçon',
  'Magicien',
  'Maillot',
  'Maillot de bain',
  'Main',
  'Maison',
  'Manège',
  'Mante religieuse',
  'Manteau',
  'Marguerite',
  'Marie Curie',
  'Marin',
  'Marionnette',
  'Marmotte',
  'Marteau',
  'Médecin',
  'Médecine',
  'Médicament',
  'Méduse',
  'Melon',
  'Menton',
  'Merlin l\'Enchanteur',
  'Métal',
  'Météorite',
  'Métro',
  'Mexique',
  'Mickey Mouse',
  'Microscope',
  'Mie',
  'Miel',
  'Mille-pattes',
  'Milou',
  'Minnie Mouse',
  'Minotaure',
  'Miroir',
  'Moineau',
  'Monstre du Loch Ness',
  'Mont Blanc',
  'Montagne',
  'Montgolfière',
  'Montre',
  'Morse (animal)',
  'Moteur',
  'Moto',
  'Mouche',
  'Mouchoir',
  'Mouette',
  'Moufle',
  'Moule',
  'Moulin',
  'Moustache',
  'Moustique',
  'Moutarde',
  'Mouton',
  'Mûre',
  'Musique',
  'Nager',
  'Nain',
  'Nappe',
  'Nasique',
  'Navet',
  'Neil Armstrong',
  'Nez',
  'Nid',
  'Nil',
  'Noël',
  'Noisette',
  'Noix',
  'Nombril',
  'Nouvel An Chinois',
  'Noyau',
  'Obélix',
  'Odin',
  'Œil',
  'Œuf',
  'Ogre',
  'Oie',
  'Oignon',
  'Oiseau',
  'Olive',
  'Ongle',
  'ONU (Organisation des Nations unies)',
  'Opticien',
  'Or',
  'Orange',
  'Ordinateur',
  'Ordonnance',
  'Oreille',
  'Oreiller',
  'Ornithorynque',
  'Orque',
  'Orteil',
  'Os',
  'Otarie',
  'Ours',
  'Ours blanc',
  'Oursin',
  'Ouvre-boîte',
  'Ouvrier',
  'Paille',
  'Pain',
  'Palais',
  'Pamplemousse',
  'Panda',
  'Pansement',
  'Pantalon',
  'Panthère',
  'Papier alu',
  'Papillon',
  'Parapluie',
  'Parasol',
  'Paris',
  'Pâte',
  'Pâte à modeler',
  'Pâtes',
  'Pâtisserie',
  'Patte',
  'Peau',
  'Pêche',
  'Pêcheur',
  'Pédale',
  'Pégase',
  'Peigne',
  'Pélican',
  'Pelle',
  'Peluche',
  'Perceuse',
  'Perle',
  'Perroquet',
  'Persil',
  'Pétanque',
  'Petit pois',
  'Pharmacie',
  'Phénix',
  'Phoque',
  'Piano',
  'Picsou',
  'Pied',
  'Pieuvre',
  'Pigeon',
  'Pinceau',
  'Pinocchio',
  'Pion',
  'Piquer',
  'Piqûre',
  'Pizza',
  'Planche',
  'Planche à découper',
  'Plastique',
  'Plâtre',
  'Pleurer',
  'Plombier',
  'Plume',
  'Pneu',
  'Poêle',
  'Poignet',
  'Poing',
  'Poire',
  'Poireau',
  'Poison',
  'Poisson',
  'Police',
  'Pomme',
  'Pomme de terre',
  'Pompier',
  'Poney',
  'Pont',
  'Popcorn',
  'Port',
  'Porte',
  'Portemanteau',
  'Poséidon',
  'Poubelle',
  'Pouce',
  'Poulain',
  'Poule',
  'Poulet',
  'Poumon',
  'Poupée',
  'Poussette',
  'Poussin',
  'Prince',
  'Princesse',
  'Printemps',
  'Prométhée',
  'Prune',
  'Puissance 4',
  'Pull-over',
  'Purée',
  'Putois',
  'Puzzle',
  'Pyjama',
  'Pyramides d\'Égypte',
  'Quetzalcoatl',
  'Queue',
  'Raclette',
  'Radiateur',
  'Radio',
  'Radis',
  'Raisin',
  'Rantanplan',
  'Raquette',
  'Rasoir',
  'Rat',
  'Râteau',
  'Raton laveur',
  'Rê',
  'Recette',
  'Réfrigérateur',
  'Reine',
  'Renard',
  'Requin',
  'Restaurant',
  'Réveil',
  'Rêver',
  'Rhinocéros',
  'Rideau',
  'Riz',
  'Robe',
  'Robinet',
  'Robinson Crusoé',
  'Robot',
  'Roi',
  'Roi Arthur',
  'Rome',
  'Roue',
  'Rouge-Gorge',
  'Rouleau à pâtisserie',
  'Sable',
  'Saint-Valentin',
  'Salade',
  'Salade de fruits',
  'Saladier',
  'Salière',
  'Sang',
  'Sanglier',
  'Sapin',
  'Sardine',
  'S\'asseoir',
  'Satyre',
  'Saumon',
  'Saut à la perche',
  'Savon',
  'Scie',
  'Science',
  'Scooter',
  'Scorpion',
  'Se baisser',
  'Se coucher',
  'Se déshabiller',
  'Se laver',
  'Se maquiller',
  'Se moucher',
  'Seau',
  'Sein',
  'Sel',
  'Serpent',
  'Serpent de mer',
  'Serrure',
  'Serviette',
  'Shampooing',
  'Sherlock Holmes',
  'Shiva',
  'Singe',
  'Sirène',
  'Ski',
  'Soleil',
  'Sonnette',
  'Sorcière',
  'Soucoupe volante',
  'Soupe',
  'Sourcil',
  'Souris',
  'Sous-marin',
  'Sphinx',
  'Squelette',
  'Statue de la Liberté',
  'Stéthoscope',
  'Stylo',
  'Sucre',
  'Superman',
  'Table',
  'Tableau',
  'Tablette',
  'Tablier',
  'Taille-crayon',
  'Talon',
  'Tambour',
  'Tandem',
  'Tapis',
  'Tapis volant',
  'Tarte',
  'Tartine',
  'Tasse',
  'Taupe',
  'Taureau',
  'Télécommande',
  'Téléphone',
  'Téléphone portable',
  'Télévision',
  'Tennis',
  'Tente',
  'Tête',
  'Téter',
  'Thé',
  'Thermomètre',
  'Thor',
  'Thot',
  'Tigre',
  'Timbre',
  'Tiroir',
  'Toboggan',
  'Tomate',
  'Torchon',
  'Tortue',
  'Tour de Pise',
  'Tour Eiffel',
  'Tournevis',
  'Toutatis',
  'Tracteur',
  'Train',
  'Traîneau',
  'Trampoline',
  'Trésor',
  'Tricycle',
  'Trompette',
  'Trône',
  'Trottinette',
  'Trou noir',
  'Trousse',
  'Truie',
  'Tuyau',
  'UE (Union européenne)',
  'Ulysse',
  'Un Saint-Bernard',
  'Un, deux, trois, soleil',
  'Une Laisse',
  'Une souris verte',
  'Univers',
  'Urine',
  'Usine',
  'Vache',
  'Valise',
  'Valkyrie',
  'Vampire',
  'Vase',
  'Vautour',
  'Veau',
  'Vélo',
  'Venise',
  'Ventre',
  'Ver de terre',
  'Verre',
  'Vétérinaire',
  'Viande',
  'Vikings',
  'Vin',
  'Vis',
  'Visage',
  'Voile',
  'Voiture',
  'Volcan',
  'Volet',
  'Xylophone',
  'Yahourt',
  'Yangzi Jiang',
  'Yéti',
  'Zèbre',
  'Zeus',
  'Zombie',
  'Zoo'
];
// ── MANCHE 1 : Les Énigmes (phrases à trous) ────────────────
export const R1_PHRASE_SETS = [
  { theme: 'Synonyme de politesse', phrase: 'Dans une {formule} de {politesse}, un mot {signifiant} {content} et {enchanté} est utilisé', words: ['formule', 'politesse', 'signifiant', 'content', 'enchanté'], reponse: 'ravi' },
  { theme: 'Cuisine italienne', phrase: 'Un élément {rond} de {pâte} {farci} de {légume} est souvent servi avec de la {tomate}', words: ['rond', 'pâte', 'farci', 'légume', 'tomate'], reponse: 'ravioli' },
  { theme: 'Musique & harmonie', phrase: 'Une {partition} contient une {note} et un {rythme} de {son} joué par un {instrument}', words: ['partition', 'note', 'rythme', 'son', 'instrument'], reponse: 'mélodie' },
  { theme: 'Phénomène météo', phrase: 'Après la {pluie} et le {soleil}, un {arc} de {couleur} apparaît dans le {ciel}', words: ['pluie', 'soleil', 'arc', 'couleur', 'ciel'], reponse: 'arc-en-ciel' },
  { theme: 'Vie scolaire', phrase: 'Un {enseignant} utilise une {craie} pour {écrire} sur un {tableau} en {classe}', words: ['enseignant', 'craie', 'écrire', 'tableau', 'classe'], reponse: 'école' },
  { theme: 'Technologie mobile', phrase: 'Un objet {portable} avec {écran} {tactile} permet un {appel} et une {application}', words: ['portable', 'écran', 'tactile', 'appel', 'application'], reponse: 'smartphone' },
  { theme: 'Animal sauvage', phrase: "Un {félin} {sauvage} d'{Afrique} possède des {rayures} {noir} et blanc", words: ['félin', 'sauvage', 'Afrique', 'rayures', 'noir'], reponse: 'zèbre' },
  { theme: 'Pâtisserie & fête', phrase: 'Un aliment {gourmand} au {sucre} et à la {pâte} sort du {four} pour une {fête}', words: ['gourmand', 'sucre', 'pâte', 'four', 'fête'], reponse: 'gâteau' },
  { theme: 'Transport ancien', phrase: 'Un {ancien} moyen de {voyage} avec {wagon} à {vapeur} circule sur des {rails}', words: ['ancien', 'voyage', 'wagon', 'vapeur', 'rails'], reponse: 'locomotive' },
  { theme: 'Nature & étendue', phrase: "Une {vague} de {sable} s'étend à l'{horizon} comme une {plage} sans {sel}", words: ['vague', 'sable', 'horizon', 'plage', 'sel'], reponse: 'mer' },
  { theme: 'Lecture & littérature', phrase: 'Un {roman} avec {couverture} raconte une {histoire} sur plusieurs {pages} écrites par un {auteur}', words: ['roman', 'couverture', 'histoire', 'pages', 'auteur'], reponse: 'livre' },
  { theme: 'Mesure du temps', phrase: "Un objet {mesure} l'{heure} et la {minute} avec un {tic} visible sur un {cadran}", words: ['mesure', 'heure', 'minute', 'tic', 'cadran'], reponse: 'horloge' },
  { theme: 'Aventure & trésor', phrase: "Une {carte} indique un {coffre} rempli d'{or} sur une {île} avec un {trésor}", words: ['carte', 'coffre', 'or', 'île', 'trésor'], reponse: 'pirate' },
  { theme: 'Repas rapide', phrase: 'Un {snack} avec {pain}, {viande} et {sauce} se mange avec la {main}', words: ['snack', 'pain', 'viande', 'sauce', 'main'], reponse: 'sandwich' },
  { theme: 'Jeu vidéo', phrase: "Un {joueur} utilise une {manette} pour battre un {boss} dans un {niveau} à l'{écran}", words: ['joueur', 'manette', 'boss', 'niveau', 'écran'], reponse: 'jeu vidéo' },
  { theme: 'Saison froide', phrase: 'Sur une {montagne}, un {flocon} {blanc} tombe avec la {neige} et le {froid}', words: ['montagne', 'flocon', 'blanc', 'neige', 'froid'], reponse: 'hiver' },
  { theme: 'Végétal & nature', phrase: "Un élément {vert} avec {feuille}, {bois} et {racine} produit de l'{oxygène}", words: ['vert', 'feuille', 'bois', 'racine', 'oxygène'], reponse: 'arbre' },
  { theme: 'Internet & web', phrase: 'Un {moteur} de {recherche} permet un {clic} vers une {page} du {réseau}', words: ['moteur', 'recherche', 'clic', 'page', 'réseau'], reponse: 'navigateur' },
  { theme: 'Astronomie', phrase: "Dans la {nuit}, une {lumière} d'{étoile} brille dans la vaste {galaxie} {infinie}", words: ['nuit', 'lumière', 'étoile', 'galaxie', 'infinie'], reponse: 'univers' },
  { theme: 'Artisanat textile', phrase: 'Un {fil} de {laine} sur une {aiguille} crée un {tissu} en {maille}', words: ['fil', 'laine', 'aiguille', 'tissu', 'maille'], reponse: 'tricot' },
  { theme: 'Sport & performance', phrase: "Un {athlète} {court} sur une {piste} pour battre un {record} de {vitesse}", words: ['athlète', 'court', 'piste', 'record', 'vitesse'], reponse: 'sprint' },
  { theme: 'Animal de mer', phrase: "Un {mammifère} {marin} avec des {nageoires} et un {dos} {bleu} nage en {groupe}", words: ['mammifère', 'marin', 'nageoires', 'dos', 'bleu'], reponse: 'dauphin' },
  { theme: 'Boisson chaude', phrase: "Des {feuilles} {séchées} dans de l'{eau} {chaude} créent une {infusion} {aromatique}", words: ['feuilles', 'séchées', 'eau', 'chaude', 'infusion'], reponse: 'thé' },
  { theme: 'Construction', phrase: "Des {briques} assemblées avec du {ciment} forment un {mur} {solide} d'une {maison}", words: ['briques', 'ciment', 'mur', 'solide', 'maison'], reponse: 'maçon' },
  { theme: 'Sport d\'équipe', phrase: "Onze {joueurs} avec un {ballon} marquent un {but} dans le {filet} adverse sur un {terrain}", words: ['joueurs', 'ballon', 'but', 'filet', 'terrain'], reponse: 'football' },
  { theme: 'Voyage aérien', phrase: "Un {appareil} {volant} avec des {ailes} décolle d'une {piste} vers le {ciel}", words: ['appareil', 'volant', 'ailes', 'piste', 'ciel'], reponse: 'avion' },
  { theme: 'Instrument à cordes', phrase: "Un {musicien} fait vibrer des {cordes} avec un {archet} sur un {bois} {verni}", words: ['musicien', 'cordes', 'archet', 'bois', 'verni'], reponse: 'violon' },
  { theme: 'Ustensile de cuisine', phrase: "Un {outil} {creux} avec un {manche} sert à {verser} une {soupe} {chaude}", words: ['outil', 'creux', 'manche', 'verser', 'soupe'], reponse: 'louche' },
  { theme: 'Lieu de soin', phrase: "Des {médecins} et des {infirmiers} soignent des {patients} dans des {chambres} {blanches}", words: ['médecins', 'infirmiers', 'patients', 'chambres', 'blanches'], reponse: 'hôpital' },
  { theme: 'Fruit d\'été', phrase: "Un {fruit} {rouge} et {juteux} avec des {graines} {noires} est dégusté en {été}", words: ['fruit', 'rouge', 'juteux', 'graines', 'noires'], reponse: 'pastèque' },
];
// ── MANCHE 3 : Noms propres (ensembles thèmes) ──────────────
export const R3_SETS = [
  { theme: 'Pays du monde', words: ['FRANCE','ESPAGNE','ITALIE','ALLEMAGNE','JAPON','BRÉSIL','CANADA','MEXIQUE','CHINE','RUSSIE','AUSTRALIE','INDE','ÉGYPTE','MAROC','ARGENTINE'] },
  { theme: 'Célébrités françaises', words: ['HUGO','VOLTAIRE','MOLIÈRE','NAPOLÉON','BAUDELAIRE','ZOLA','FLAUBERT','RIMBAUD','VERLAINE','CAMUS','SARTRE','DE GAULLE','PICASSO','MONET','PROUST'] },
  { theme: 'Personnages historiques', words: ['CLÉOPÂTRE','CHARLEMAGNE','COLOMB','EINSTEIN','SHAKESPEARE','DARWIN','GALILÉE','DE VINCI','MOZART','BEETHOVEN','NEWTON','PLATON','SOCRATE','MAGELLAN','PASTEUR'] },
  { theme: 'Villes françaises', words: ['PARIS','LYON','MARSEILLE','BORDEAUX','TOULOUSE','NANTES','NICE','STRASBOURG','MONTPELLIER','RENNES','ROUEN','LILLE','GRENOBLE','DIJON','REIMS'] },
  { theme: 'Pays d\'Afrique', words: ['SÉNÉGAL','MALI','CAMEROUN','CÔTE D\'IVOIRE','TUNISIE','ALGÉRIE','NIGERIA','KENYA','GHANA','ÉTHIOPIE','TANZANIE','MADAGASCAR','MOZAMBIQUE','ANGOLA','ZAMBIE'] },

  { theme: 'Capitales du monde', words: ['PARIS','ROME','MADRID','BERLIN','TOKYO','OTTAWA','BRASILIA','PEKIN','MOSCOU','LONDRES','DUBLIN','VIENNE','PRAGUE','ATHENES','OSLO'] },
  { theme: 'Présidents américains', words: ['WASHINGTON','LINCOLN','ROOSEVELT','KENNEDY','NIXON','REAGAN','CLINTON','BUSH','OBAMA','TRUMP','BIDEN','JEFFERSON','MADISON','MONROE','GRANT'] },
  { theme: 'Écrivains célèbres', words: ['HUGO','ZOLA','ORWELL','TOLSTOI','DOSTOIEVSKI','KAFKA','HEMINGWAY','JOYCE','PROUST','CAMUS','SARTRE','BALZAC','VERNE','TWAIN','AUSTEN'] },
  { theme: 'Peintres célèbres', words: ['MONET','MANET','RENOIR','PICASSO','VAN GOGH','DALI','MICHEL-ANGE','RAPHAEL','REMBRANDT','CEZANNE','GAUGUIN','MATISSE','KANDINSKY','POLLOCK','WARHOL'] },
  { theme: 'Philosophes', words: ['PLATON','SOCRATE','ARISTOTE','DESCARTES','KANT','NIETZSCHE','ROUSSEAU','VOLTAIRE','HEGEL','MARX','SPINOZA','LOCKE','HOBBES','FOUCAULT','DERRIDA'] },

  { theme: 'Acteurs hollywoodiens', words: ['DICAPRIO','PITT','CRUISE','HANKS','DEPP','SMITH','FREEMAN','WASHINGTON','CLOONEY','DAMON','WAHLBERG','JACKMAN','BALE','PHOENIX','REEVES'] },
  { theme: 'Chanteurs internationaux', words: ['MJ','MADONNA','BEYONCE','RIHANNA','DRAKE','EMINEM','ADELE','STING','PRINCE','ELVIS','SINATRA','SHAKIRA','BIEBER','WEEKND','BRUNO MARS'] },
  { theme: 'Groupes de musique', words: ['BEATLES','QUEEN','ABBA','METALLICA','NIRVANA','U2','COLDPLAY','RADIOHEAD','PINK FLOYD','ROLLING STONES','MAROON 5','LINKIN PARK','OASIS','MUSE','IMAGINE DRAGONS'] },
  { theme: 'Marques automobiles', words: ['RENAULT','PEUGEOT','CITROEN','BMW','AUDI','MERCEDES','TESLA','TOYOTA','HONDA','FORD','FERRARI','LAMBORGHINI','VOLKSWAGEN','HYUNDAI','KIA'] },
  { theme: 'Entreprises tech', words: ['APPLE','GOOGLE','MICROSOFT','AMAZON','META','NETFLIX','TESLA','INTEL','IBM','ORACLE','SAMSUNG','SONY','UBER','AIRBNB','SPOTIFY'] },

  { theme: 'Clubs de football', words: ['PSG','OM','OL','BARCELONE','REAL MADRID','LIVERPOOL','CHELSEA','ARSENAL','BAYERN','DORTMUND','JUVENTUS','MILAN','INTER','AJAX','PORTO'] },
  { theme: 'Joueurs de football', words: ['MBAPPE','MESSI','RONALDO','NEYMAR','ZIDANE','BENZEMA','HAALAND','MODRIC','KANE','SALAH','DE BRUYNE','GRIEZMANN','POGBA','RONALDINHO','IBRAHIMOVIC'] },
  { theme: 'Films célèbres', words: ['TITANIC','AVATAR','GLADIATOR','INCEPTION','MATRIX','ALIEN','ROCKY','JOKER','AMELIE','INTOUCHABLES','FROZEN','COCO','BATMAN','SUPERMAN','SPIDERMAN'] },
  { theme: 'Personnages fictifs', words: ['HARRY POTTER','SUPERMAN','BATMAN','SPIDERMAN','HULK','IRON MAN','SHERLOCK','VADER','YODA','FRODO','GANDALF','ELSA','SIMBA','POKEMON','MARIO'] },
  { theme: 'YouTubeurs / Streamers', words: ['SQUEEZIE','CYPRIEN','MISTER V','AMIXEM','GMK','INOXTAG','MICHOU','LOCKLEAR','GOTAGA','ZERATOR','POKIMANE','NINJA','PEWDIEPIE','MRBEAST','VALOUZZ'] },

  { theme: 'Prix Nobel de physique', words: ['EINSTEIN','CURIE','BOHR','HEISENBERG','DIRAC','FEYNMAN','PLANCK','RUTHERFORD','FERMI','SCHRODINGER','PAULI','LANDAU','HIGGS','HAWKING','NOBEL'] },
  { theme: 'Pays d\'Asie', words: ['JAPON','CHINE','INDE','CORÉE','THAÏLANDE','VIETNAM','INDONÉSIE','MALAISIE','PHILIPPINES','SINGAPOUR','PAKISTAN','BANGLADESH','CAMBODGE','BIRMANIE','LAOS'] },
  { theme: 'Explorateurs & navigateurs', words: ['CHRISTOPHE COLOMB','MAGELLAN','VASCO DE GAMA','AMERIGO VESPUCCI','JAMES COOK','LEIF ERIKSON','MARCO POLO','IBN BATTUTA','ABEL TASMAN','HENRY HUDSON','BARTOLOMEU DIAS','BOUGAINVILLE','LA PEROUSE','AMUNDSEN','SHACKLETON'] },
  { theme: 'Chefs cuisiniers célèbres', words: ['BOCUSE','ROBUCHON','DUCASSE','ESCOFFIER','RAMSAY','OLIVER','TROISGROS','GUÉRARD','LOISEAU','PIERRARD','BLANC','CHAPEL','GIRARDEL','ALAIN SENDERENS','MICHEL BRAS'] },
  { theme: 'Sportifs français', words: ['ZIDANE','MBAPPE','THURAM','PLATINI','VIEIRA','HENRY','CANTONA','BARTHEZ','DESCHAMPS','PETIT','DESAILLY','LIZARAZU','PIRES','ANELKA','RIBERY'] },
];
// ── MANCHE 4 : Contre-la-montre (sets thématiques) ──────────
export const R4_SETS = [
  { theme: 'Animaux de la ferme', words: ['VACHE','COCHON','CHEVAL','MOUTON','POULE','LAPIN','ANE'] },
  { theme: 'Instruments de musique', words: ['PIANO','GUITARE','VIOLON','FLUTE','TROMPETTE','BATTERIE','HARPE'] },
  { theme: 'Sports olympiques', words: ['NATATION','CYCLISME','ATHLETISME','TENNIS','FOOTBALL','BOXE','ESCRIME'] },
  { theme: 'Fruits exotiques', words: ['MANGUE','ANANAS','PAPAYE','LITCHI','GRENADE','COCO','KIWI'] },
  { theme: 'Métiers', words: ['MEDECIN','BOULANGER','PILOTE','POMPIER','PROFESSEUR','CUISINIER','ARCHITECTE'] },

  { theme: 'Légumes', words: ['CAROTTE','TOMATE','POIREAU','COURGETTE','AUBERGINE','OIGNON','POMME DE TERRE'] },
  { theme: 'Couleurs', words: ['ROUGE','BLEU','VERT','JAUNE','NOIR','BLANC','ORANGE'] },
  { theme: 'Meubles', words: ['TABLE','CHAISE','CANAPE','LIT','ARMOIRE','BUREAU','ETAGERE'] },
  { theme: 'Vêtements', words: ['CHEMISE','PANTALON','VESTE','ROBE','CHAUSSURES','MANTEAU','T-SHIRT'] },
  { theme: 'Objets scolaires', words: ['STYLO','CRAYON','GOMME','REGLE','CAHIER','LIVRE','SAC'] },

  { theme: 'Parties du corps', words: ['TETE','BRAS','JAMBE','MAIN','PIED','YEUX','BOUCHE'] },
  { theme: 'Animaux marins', words: ['REQUIN','DAUPHIN','BALEINE','POULPE','CRABE','MEDUSE','RAIE'] },
  { theme: 'Oiseaux', words: ['AIGLE','MOINEAU','PIGEON','HIBOU','PERROQUET','CANARD','CYGNE'] },
  { theme: 'Boissons', words: ['EAU','JUS','SODA','CAFE','THE','LAIT','BIERE'] },
  { theme: 'Desserts', words: ['GATEAU','TARTE','GLACE','CREPE','MOUSSE','BISCUIT','BROWNIE'] },

  { theme: 'Transports', words: ['VOITURE','BUS','TRAIN','AVION','VELO','MOTO','BATEAU'] },
  { theme: 'Pays européens', words: ['FRANCE','ESPAGNE','ITALIE','ALLEMAGNE','BELGIQUE','SUISSE','PORTUGAL'] },
  { theme: 'Langues', words: ['FRANCAIS','ANGLAIS','ESPAGNOL','ITALIEN','ALLEMAND','CHINOIS','ARABE'] },
  { theme: 'Sports collectifs', words: ['FOOTBALL','BASKET','HANDBALL','RUGBY','VOLLEY','HOCKEY','BASEBALL'] },
  { theme: 'Objets électroniques', words: ['TELEPHONE','ORDINATEUR','TABLETTE','TELEVISION','CASQUE','SOURIS','CLAVIER'] },

  { theme: 'Saisons & météo', words: ['PRINTEMPS','ETE','AUTOMNE','HIVER','PLUIE','NEIGE','SOLEIL'] },
  { theme: 'Fleurs', words: ['ROSE','TULIPE','MARGUERITE','PIVOINE','ORCHIDEE','LIS','JASMIN'] },
  { theme: 'Épices & condiments', words: ['SEL','POIVRE','CANNELLE','CUMIN','PAPRIKA','THYM','BASILIC'] },
  { theme: 'Professions de santé', words: ['MEDECIN','INFIRMIER','CHIRURGIEN','PHARMACIEN','DENTISTE','KINESITHERAPEUTE','VETERINAIRE'] },
  { theme: 'Pays d\'Amérique latine', words: ['BRESIL','MEXIQUE','ARGENTINE','COLOMBIE','CHILI','PERU','VENEZUELA'] },

  { theme: 'Superhéros', words: ['BATMAN','SUPERMAN','SPIDERMAN','IRONMAN','HULK','THOR','FLASH'] },
  { theme: 'Planètes du système solaire', words: ['MERCURE','VENUS','TERRE','MARS','JUPITER','SATURNE','URANUS'] },
  { theme: 'Sports individuels', words: ['TENNIS','NATATION','ATHLETISME','CYCLISME','GOLF','SKI','BOXE'] },
  { theme: 'Animaux de la jungle', words: ['LION','TIGRE','ELEPHANT','GORILLE','LEOPARD','HIPPO','CROCODILE'] },
  { theme: 'Matières scolaires', words: ['MATHS','FRANCAIS','HISTOIRE','GEOGRAPHIE','SCIENCES','ANGLAIS','SPORT'] },
];

// ── Finale : La Grande Pyramide (expressions) ────────────────
export const FINAL_SETS = [
  ['AVOIR LE CAFARD','CASSER LES PIEDS','IL PLEUT DES CORDES','POSER UN LAPIN','PRENDRE LA POUDRE D\'ESCAMPETTE','TOURNER EN ROND'],
  ['AVOIR LE CŒUR SUR LA MAIN','BRÛLER LES ÉTAPES','DONNER SA LANGUE AU CHAT','METTRE LES PIEDS DANS LE PLAT','NOYER LE POISSON','TOMBER DANS LES POMMES'],
  ['AVOIR D\'AUTRES CHATS À FOUETTER','CASSER DU SUCRE SUR LE DOS','ÊTRE DANS SES PETITS SOULIERS','MANGER À TOUS LES RÂTELIERS','PRENDRE LE TAUREAU PAR LES CORNES','SE JETER À L\'EAU'],
  ['ARC-EN-CIEL','POMME DE PIN','CROQUE-MONSIEUR','SALLE À MANGER','CHEF-D\'ŒUVRE','GARDE À VUE'],
  ['PRISE DE PAROLE','MISE EN SCÈNE','PLAN DE TABLE','SENS INTERDIT','LIGNE DE VIE','POINT MORT'],
  ['COUP DE BARRE','COUP DE GUEULE','COUP DE SOLEIL','COUP DE VENT','COUP DE FEU','COUP DE THÉÂTRE'],
  ['MAIN FORTE','MAIN COURANTE','MAIN LOURDE','MAIN HEUREUSE','MAIN INVISIBLE','MAIN TENDUE'],
  ['AVOIR LA TÊTE DANS LES NUAGES','AVOIR LES YEUX PLUS GROS QUE LE VENTRE','AVOIR UN POIL DANS LA MAIN','CHERCHER MIDI À QUATORZE HEURES','METTRE DE L\'EAU DANS SON VIN','REMUER CIEL ET TERRE'],
  ['JETER L\'ÉPONGE','TENIR SA LANGUE','AVOIR LE VENT EN POUPE','ALLER DROIT AU BUT','FAIRE D\'UNE PIERRE DEUX COUPS','ÊTRE AU PIED DU MUR'],
  ['PASSER L\'ÉPONGE','PRENDRE LA TÊTE','FAIRE LA SOURDE OREILLE','DONNER LE TON','CHANGER DE DISQUE','MONTER AU CRÉNEAU'],
  ['ÊTRE SUR LES NERFS','AVOIR LA DALLE','ÊTRE À CÔTÉ DE LA PLAQUE','TOMBER DE HAUT','RESTER DE MARBRE','AVOIR LE BEGUIN'],
  ['COUP DE FOUDRE','COUP DE FIL','COUP DE CHAPEAU','COUP DE PRESSION','COUP DE POUCE','COUP DE BALAI'],
  ['FIL ROUGE','FIL CONDUCTEUR','FIL D\'ARIANE','FIL À COUDRE','FIL DE FER','FIL DE L\'HISTOIRE'],
  ['JEU D\'ENFANT','JEU DE RÔLE','JEU VIDÉO','JEU DE CARTES','JEU D\'ÉCHECS','JEU DE SOCIÉTÉ'],
  ['SAC À DOS','SAC À MAIN','SAC DE VOYAGE','SAC DE SPORT','SAC POUBELLE','SAC À MALICE'],
  ['VERRE D\'EAU','VERRE DE VIN','VERRE BRISÉ','VERRE À PIED','VERRE DOUBLÉ','VERRE FUMÉ'],
  ['TABLE RONDE','TABLE BASSE','TABLE DE NUIT','TABLE DE JEU','TABLE DE TRAVAIL','TABLE À REPASSER'],
  ['CHASSE À L\'HOMME','CHASSE AU TRÉSOR','CHASSE NEIGE','CHASSE D\'EAU','CHASSE À COURRE','CHASSE AUX SORCIÈRES'],
  ['PIERRE ANGULAIRE','PIERRE PRÉCIEUSE','PIERRE TOMBALE','PIERRE À FEU','PIERRE DE TAILLE','PIERRE QUI ROULE'],
  ['VENT DE FOLIE','VENT D\'EST','VENT DU NORD','VENT SOLAIRE','VENT CONTRAIRE','VENT ARRIÈRE'],
  ['ROUE LIBRE','ROUE DE SECOURS','ROUE ARRIÈRE','ROUE AVANT','ROUE DENTÉE','ROUE TOURNE'],
  ['FEU ROUGE','FEU VERT','FEU DE JOIE','FEU DE CAMP','FEU DE SIGNALISATION','FEU SACRÉ'],
  ['POINT DE NON-RETOUR','POINT FINAL','POINT D\'EAU','POINT DE VUE','POINT DE CHUTE','POINT DE REPÈRE'],
  ['BLANC COMME NEIGE','BLANC DE POULET','BLANC BEC','BLANC SEING','MANGER TOUT SON BLANC','NUIT BLANCHE'],
  ['CŒUR DE LION','CŒUR À CŒUR','COUP DE CŒUR','BEAU COMME UN CŒUR','EN AVOIR LE CŒUR NET','SERRER LE CŒUR'],
  ['LANGUE DE BOIS','LANGUE DE CHAT','MAUVAISE LANGUE','TENIR SA LANGUE','LANGUE VERTE','PRENDRE LANGUE'],
  ['PIQUER UNE CRISE','PIQUER UN SOLEIL','PIQUER DU NEZ','PIQUER UNE TÊTE','PIQUER AU VIF','PIQUER SA CURIOSITÉ'],
  ['MAIN DANS LE SAC','MAIN MISE','MAIN LEVÉE','EN VENIR AUX MAINS','DE MAIN DE MAÎTRE','METTRE LA MAIN À LA PÂTE'],
  ['DOS AU MUR','DANS LE DOS','EN AVOIR PLEIN LE DOS','AVOIR BON DOS','TOURNER LE DOS','SE METTRE À DOS'],
  ['COUP DE CHAPEAU','COUP DE MAIN','COUP DE FOUDRE','COUP DE GRÂCE','COUP D\'ÉTAT','COUP DE THÉÂTRE'],
];
