// ============================================================
// pyramide/data.js — Données brutes (listes de mots)
// La logique se trouve dans words.js
// ============================================================



// ── MANCHE 2 : Ping-Pong (liste plate) ──────────────────────
// Source : pyramide/mots/famille.json (858 mots)
export const R2_WORDS = [
  '14-Juillet',
  '1er-Avril',
  'Abeille',
  'Abricot',
  'Acrobate',
  'Acteur',
  'Aéroport',
  'Agneau',
  'Agriculteur',
  'Aigle',
  'Aiguille',
  'Ail',
  'Aile',
  'Air',
  'Albert Einstein',
  'Alice au pays des merveilles',
  'Allumette',
  'Amazone',
  'Ambulance',
  'Ampoule',
  'Ananas',
  'Âne',
  'Animal',
  'Anniversaire',
  'Anubis',
  'Aphrodite',
  'Apiculteur',
  'Apollon',
  'Appareil dentaire',
  'Appareil photographique',
  'Aquarium',
  'Araignée',
  'Arbre',
  'Arc-en-ciel',
  'Archéologue',
  'Architecte',
  'Arès',
  'Arête',
  'Argent',
  'Arrosoir',
  'Artémis',
  'Ascenseur',
  'Asperge',
  'Aspirateur',
  'Aspirine',
  'Assiette',
  'Astérix',
  'Astronaute',
  'Astronomie',
  'Athéna',
  'Atterrir',
  'Au clair de la lune',
  'Aubergine',
  'Automne',
  'Autruche',
  'Avion',
  'Bague',
  'Baguette',
  'Bâiller',
  'Balai',
  'Balançoire',
  'Baleine',
  'Baleine bleue',
  'Balle',
  'Ballon',
  'Banane',
  'Banc',
  'Bande dessinée',
  'Barbe',
  'Barque',
  'Barrette',
  'Basket-ball',
  'Bateau',
  'Bâton',
  'Bavoir',
  'Bec',
  'Béquille',
  'Berger',
  'Berger allemand',
  'Bermuda',
  'Beurre',
  'Biberon',
  'Bibliothèque',
  'Bifteck',
  'Big Ben',
  'Bijou',
  'Bijoutier',
  'Bille',
  'Billet',
  'Biologie',
  'Biscuit',
  'Bison',
  'Blé',
  'Bœuf',
  'Boisson',
  'Bol',
  'Bonbon',
  'Bonnet',
  'Boomerang',
  'Botte',
  'Bouche',
  'Boucher',
  'Boucherie',
  'Bouchon',
  'Boue',
  'Bouée',
  'Boulanger',
  'Boulangerie',
  'Bouteille',
  'Bouton',
  'Bracelet',
  'Bras',
  'Bretelle',
  'Brocoli',
  'Brosse à dents',
  'Brouette',
  'Bugs Bunny',
  'Bureau',
  'Bus',
  'Cabane',
  'Cadeau',
  'Cadenas',
  'Café',
  'Cafetière',
  'Cage',
  'Cagoule',
  'Caillou',
  'Calculette',
  'Calendrier',
  'Caméléon',
  'Caméra',
  'Camion',
  'Camping-car',
  'Canapé',
  'Canard',
  'Caniche',
  'Canne à pêche',
  'Car',
  'Caravane',
  'Carnaval',
  'Carotte',
  'Cartable',
  'Casque',
  'Casquette',
  'Casserole',
  'Castor',
  'Ceinture',
  'Cendrillon',
  'Centaure',
  'Cerbère',
  'Cerceau',
  'Céréale',
  'Cerf',
  'Cerf-volant',
  'Cerise',
  'Cerveau',
  'Chaise',
  'Chameau',
  'Champignon',
  'Chandeleur',
  'Chanter',
  'Chanteur',
  'Chapeau',
  'Chariot',
  'Charlemagne',
  'Charpentier',
  'Chasseur',
  'Chat',
  'Châtaigne',
  'Château',
  'Chaton',
  'Chaussette',
  'Chaussettes',
  'Chausson',
  'Chaussure',
  'Chauve-souris',
  'Chemise',
  'Chenille',
  'Chercheur d\'or',
  'Cheval',
  'Cheval de Troie',
  'Chevaliers de la Table ronde',
  'Cheveu',
  'Cheville',
  'Chèvre',
  'Chien',
  'Chiffon',
  'Chiot',
  'Chips',
  'Chirurgien',
  'Chocolat',
  'Chou',
  'Chouette',
  'Christophe Colomb',
  'Chuchoter',
  'Cigogne',
  'Cil',
  'Ciseaux',
  'Citron',
  'Citrouille',
  'Clé',
  'Clémentine',
  'Cléopâtre',
  'Clignotant',
  'Clou',
  'Clown',
  'Coccinelle',
  'Cochon',
  'Cocotte',
  'Cœur',
  'Coffre',
  'Coiffeur',
  'Collant',
  'Colle',
  'Collier',
  'Colorier',
  'Concombre',
  'Conduire',
  'Confiture',
  'Console de jeu',
  'Coq',
  'Coquelicot',
  'Coquillage',
  'Corbeau',
  'Corbeille',
  'Corde',
  'Cou',
  'Coude',
  'Coudre',
  'Couette',
  'Couronne',
  'Coussin',
  'Couteau',
  'Couver',
  'Couvercle',
  'Couverture',
  'Cow-boy',
  'Crabe',
  'Cracher',
  'Craie',
  'Crapaud',
  'Cravate',
  'Crayon',
  'Crèche',
  'Crème solaire',
  'Crêpe',
  'Creuser',
  'Crevette',
  'Crochet',
  'Crocodile',
  'Croissant',
  'Cronos',
  'Croûte',
  'Cube',
  'Cuillère',
  'Cuisinier',
  'Cuisse',
  'Culotte',
  'Cyclisme',
  'Cyclope',
  'Cygne',
  'Danser',
  'Dauphin',
  'Dé',
  'Déchirer',
  'Déguisement',
  'Dent',
  'Dentifrice',
  'Dentiste',
  'Dessert',
  'Diamant',
  'Diane',
  'Dictionnaire',
  'Dindon',
  'Dînette',
  'Dinosaure',
  'Dionysos',
  'Doigt',
  'Domino',
  'Dompteur',
  'Donald Duck',
  'Dormir',
  'Dos',
  'Dragon',
  'Drap',
  'Dromadaire',
  'Eau',
  'Écharpe',
  'Échasse',
  'Échecs',
  'Échelle',
  'École',
  'École maternelle',
  'Écran',
  'Écrire',
  'Écureuil',
  'Égypte',
  'Élastique',
  'Éléphant',
  'Elfe',
  'Empire State Building',
  'Endive',
  'Entonnoir',
  'Enveloppe',
  'Épaule',
  'Épingle',
  'Épiphanie',
  'Éponge',
  'Escalier mécanique',
  'Escargot',
  'Escrime',
  'Espagne',
  'Essence',
  'États-Unis',
  'Été',
  'Étoile',
  'Étoile de mer',
  'Étoile filante',
  'Everest',
  'Facteur',
  'Fantôme',
  'Farine',
  'Fauteuil',
  'Fauteuil roulant',
  'Fée',
  'Fer à repasser',
  'Ferme',
  'Fesse',
  'Fête de la musique',
  'Fête des grands-mères',
  'Fête des mères',
  'Fête des pères',
  'Feutre',
  'Fève',
  'Ficelle',
  'Fièvre',
  'Fil',
  'Fille',
  'Flamant rose',
  'Fleur',
  'Fleuriste',
  'Flûte traversière',
  'Football',
  'Forgeron',
  'Fossile',
  'Four',
  'Fourchette',
  'Fourmi',
  'Fraise',
  'Framboise',
  'France',
  'Frein',
  'Frisbee',
  'Frites',
  'Fromage',
  'Front',
  'Fruit',
  'Fusée',
  'Fusée spatiale',
  'Gaïa',
  'Galère',
  'Galette',
  'Gandhi',
  'Gant',
  'Garage',
  'Garçon',
  'Gardien',
  'Gare',
  'Gargamel',
  'Gâteau',
  'Gaulois',
  'Géant',
  'Genou',
  'Géologie',
  'Girafe',
  'Glaçon',
  'Gobelet',
  'Golf',
  'Gomme',
  'Gorille',
  'Grande Muraille de Chine',
  'Grèce',
  'Grenouille',
  'Griffe',
  'Groseille',
  'Grotte',
  'Grue',
  'Gruyère',
  'Guépard',
  'Guêpe',
  'Guirlande',
  'Gymnase',
  'Gymnastique',
  'Hadès',
  'Halloween',
  'Hamster',
  'Handball',
  'Haricot vert',
  'Hélicoptère',
  'Héphaïstos',
  'Héra',
  'Héraclès',
  'Herbe',
  'Hérisson',
  'Hermès',
  'Hibou',
  'Hippocampe',
  'Hippopotame',
  'Hirondelle',
  'Hiver',
  'Hockey sur glace',
  'Hôpital',
  'Hoquet',
  'Horloge',
  'Horus',
  'Hôtel',
  'Huile',
  'Husky',
  'Icare',
  'Idéfix',
  'Imprimante',
  'Infirmier',
  'Informaticien',
  'Insecte',
  'Italie',
  'Jambe',
  'Jambon',
  'Janus',
  'Japon',
  'Jeanne d\'Arc',
  'Jolly Jumper',
  'Jongler',
  'Jongleur',
  'Joue',
  'Journaliste',
  'Journée internationale des femmes',
  'Judo',
  'Jumelles',
  'Jument',
  'Jupe',
  'Jus d\'orange',
  'Kangourou',
  'Karaté',
  'Ketchup',
  'Kilt',
  'Kiwi',
  'La Reine des neiges',
  'La Schtroumpfette',
  'Lacet',
  'Lait',
  'Lancer du disque',
  'Langue',
  'Lapin',
  'Larme',
  'Las Vegas',
  'Lave-linge',
  'Le Capitaine Haddock',
  'Le Grand Schtroumpf',
  'Le Marsupilami',
  'Le Monde de Nemo',
  'Le Petit Prince',
  'Le Roi lion',
  'Le Schtroumpf à lunettes',
  'Léopard',
  'Les Schtroumpfs',
  'Lèvre',
  'Lèvres',
  'Lézard',
  'Libellule',
  'Libraire',
  'Licorne',
  'Lièvre',
  'Limace',
  'Lion',
  'Lire',
  'Lit',
  'Livre',
  'Louche',
  'Loup',
  'Loupe',
  'Loup-Garou',
  'Lucky Luke',
  'Luge',
  'Lune',
  'Lunettes',
  'Lunettes de soleil',
  'Lutin',
  'Maçon',
  'Magicien',
  'Maillot',
  'Maillot de bain',
  'Main',
  'Maison',
  'Manège',
  'Mante religieuse',
  'Manteau',
  'Marguerite',
  'Marie Curie',
  'Marin',
  'Marionnette',
  'Marmotte',
  'Marteau',
  'Médecin',
  'Médecine',
  'Médicament',
  'Méduse',
  'Melon',
  'Menton',
  'Merlin l\'Enchanteur',
  'Métal',
  'Météorite',
  'Métro',
  'Mexique',
  'Mickey Mouse',
  'Microscope',
  'Mie',
  'Miel',
  'Mille-pattes',
  'Milou',
  'Minnie Mouse',
  'Minotaure',
  'Miroir',
  'Moineau',
  'Monstre du Loch Ness',
  'Mont Blanc',
  'Montagne',
  'Montgolfière',
  'Montre',
  'Morse (animal)',
  'Moteur',
  'Moto',
  'Mouche',
  'Mouchoir',
  'Mouette',
  'Moufle',
  'Moule',
  'Moulin',
  'Moustache',
  'Moustique',
  'Moutarde',
  'Mouton',
  'Mûre',
  'Musique',
  'Nager',
  'Nain',
  'Nappe',
  'Nasique',
  'Navet',
  'Neil Armstrong',
  'Nez',
  'Nid',
  'Nil',
  'Noël',
  'Noisette',
  'Noix',
  'Nombril',
  'Nouvel An Chinois',
  'Noyau',
  'Obélix',
  'Odin',
  'Œil',
  'Œuf',
  'Ogre',
  'Oie',
  'Oignon',
  'Oiseau',
  'Olive',
  'Ongle',
  'ONU (Organisation des Nations unies)',
  'Opticien',
  'Or',
  'Orange',
  'Ordinateur',
  'Ordonnance',
  'Oreille',
  'Oreiller',
  'Ornithorynque',
  'Orque',
  'Orteil',
  'Os',
  'Otarie',
  'Ours',
  'Ours blanc',
  'Oursin',
  'Ouvre-boîte',
  'Ouvrier',
  'Paille',
  'Pain',
  'Palais',
  'Pamplemousse',
  'Panda',
  'Pansement',
  'Pantalon',
  'Panthère',
  'Papier alu',
  'Papillon',
  'Parapluie',
  'Parasol',
  'Paris',
  'Pâte',
  'Pâte à modeler',
  'Pâtes',
  'Pâtisserie',
  'Patte',
  'Peau',
  'Pêche',
  'Pêcheur',
  'Pédale',
  'Pégase',
  'Peigne',
  'Pélican',
  'Pelle',
  'Peluche',
  'Perceuse',
  'Perle',
  'Perroquet',
  'Persil',
  'Pétanque',
  'Petit pois',
  'Pharmacie',
  'Phénix',
  'Phoque',
  'Piano',
  'Picsou',
  'Pied',
  'Pieuvre',
  'Pigeon',
  'Pinceau',
  'Pinocchio',
  'Pion',
  'Piquer',
  'Piqûre',
  'Pizza',
  'Planche',
  'Planche à découper',
  'Plastique',
  'Plâtre',
  'Pleurer',
  'Plombier',
  'Plume',
  'Pneu',
  'Poêle',
  'Poignet',
  'Poing',
  'Poire',
  'Poireau',
  'Poison',
  'Poisson',
  'Police',
  'Pomme',
  'Pomme de terre',
  'Pompier',
  'Poney',
  'Pont',
  'Popcorn',
  'Port',
  'Porte',
  'Portemanteau',
  'Poséidon',
  'Poubelle',
  'Pouce',
  'Poulain',
  'Poule',
  'Poulet',
  'Poumon',
  'Poupée',
  'Poussette',
  'Poussin',
  'Prince',
  'Princesse',
  'Printemps',
  'Prométhée',
  'Prune',
  'Puissance 4',
  'Pull-over',
  'Purée',
  'Putois',
  'Puzzle',
  'Pyjama',
  'Pyramides d\'Égypte',
  'Quetzalcoatl',
  'Queue',
  'Raclette',
  'Radiateur',
  'Radio',
  'Radis',
  'Raisin',
  'Rantanplan',
  'Raquette',
  'Rasoir',
  'Rat',
  'Râteau',
  'Raton laveur',
  'Rê',
  'Recette',
  'Réfrigérateur',
  'Reine',
  'Renard',
  'Requin',
  'Restaurant',
  'Réveil',
  'Rêver',
  'Rhinocéros',
  'Rideau',
  'Riz',
  'Robe',
  'Robinet',
  'Robinson Crusoé',
  'Robot',
  'Roi',
  'Roi Arthur',
  'Rome',
  'Roue',
  'Rouge-Gorge',
  'Rouleau à pâtisserie',
  'Sable',
  'Saint-Valentin',
  'Salade',
  'Salade de fruits',
  'Saladier',
  'Salière',
  'Sang',
  'Sanglier',
  'Sapin',
  'Sardine',
  'S\'asseoir',
  'Satyre',
  'Saumon',
  'Saut à la perche',
  'Savon',
  'Scie',
  'Science',
  'Scooter',
  'Scorpion',
  'Se baisser',
  'Se coucher',
  'Se déshabiller',
  'Se laver',
  'Se maquiller',
  'Se moucher',
  'Seau',
  'Sein',
  'Sel',
  'Serpent',
  'Serpent de mer',
  'Serrure',
  'Serviette',
  'Shampooing',
  'Sherlock Holmes',
  'Shiva',
  'Singe',
  'Sirène',
  'Ski',
  'Soleil',
  'Sonnette',
  'Sorcière',
  'Soucoupe volante',
  'Soupe',
  'Sourcil',
  'Souris',
  'Sous-marin',
  'Sphinx',
  'Squelette',
  'Statue de la Liberté',
  'Stéthoscope',
  'Stylo',
  'Sucre',
  'Superman',
  'Table',
  'Tableau',
  'Tablette',
  'Tablier',
  'Taille-crayon',
  'Talon',
  'Tambour',
  'Tandem',
  'Tapis',
  'Tapis volant',
  'Tarte',
  'Tartine',
  'Tasse',
  'Taupe',
  'Taureau',
  'Télécommande',
  'Téléphone',
  'Téléphone portable',
  'Télévision',
  'Tennis',
  'Tente',
  'Tête',
  'Téter',
  'Thé',
  'Thermomètre',
  'Thor',
  'Thot',
  'Tigre',
  'Timbre',
  'Tiroir',
  'Toboggan',
  'Tomate',
  'Torchon',
  'Tortue',
  'Tour de Pise',
  'Tour Eiffel',
  'Tournevis',
  'Toutatis',
  'Tracteur',
  'Train',
  'Traîneau',
  'Trampoline',
  'Trésor',
  'Tricycle',
  'Trompette',
  'Trône',
  'Trottinette',
  'Trou noir',
  'Trousse',
  'Truie',
  'Tuyau',
  'UE (Union européenne)',
  'Ulysse',
  'Un Saint-Bernard',
  'Un, deux, trois, soleil',
  'Une Laisse',
  'Une souris verte',
  'Univers',
  'Urine',
  'Usine',
  'Vache',
  'Valise',
  'Valkyrie',
  'Vampire',
  'Vase',
  'Vautour',
  'Veau',
  'Vélo',
  'Venise',
  'Ventre',
  'Ver de terre',
  'Verre',
  'Vétérinaire',
  'Viande',
  'Vikings',
  'Vin',
  'Vis',
  'Visage',
  'Voile',
  'Voiture',
  'Volcan',
  'Volet',
  'Xylophone',
  'Yahourt',
  'Yangzi Jiang',
  'Yéti',
  'Zèbre',
  'Zeus',
  'Zombie',
  'Zoo'
];

export const R1_PHRASE_SETS_ADULTE = [ 

  { theme: 'formes anciennes', phrase: "Un élément {circulaire} de {semoule} {garni} de {verdure} est souvent servi avec de la {sauce}", words: ['circulaire', 'semoule', 'garni', 'verdure', 'sauce'], reponse: 'ravioli' },

  { theme: 'organisation invisible', phrase: "Une {portée} contient une {tonalité} et un {tempo} de {vibration} joué par un {outil}", words: ['portée', 'tonalité', 'tempo', 'vibration', 'outil'], reponse: 'mélodie' },

  { theme: 'apparition fugace', phrase: "Après la {bruine} et l'{astre}, une {farandole} de {teinte} apparaît dans la {voûte}", words: ['bruine', 'astre', 'farandole', 'teinte', 'voûte'], reponse: 'arc-en-ciel' },

  { theme: 'transmission', phrase: "Un {formateur} utilise une {pierre} pour {tracer} sur un {support} en {cours}", words: ['formateur', 'pierre', 'tracer', 'support', 'cours'], reponse: 'école' },

  { theme: 'prolongement de soi', phrase: "Un objet {nomade} avec {surface} {sensible} permet un {contact} et une {fonction}", words: ['nomade', 'surface', 'sensible', 'contact', 'fonction'], reponse: 'smartphone' },

  { theme: 'contraste vivant', phrase: "Un {carnivore} {indompté} d'{savane} possède des {bandes} {sombre} et clair", words: ['carnivore', 'indompté', 'savane', 'bandes', 'sombre'], reponse: 'zèbre' },

  { theme: 'plaisir partagé', phrase: "Un aliment {sucré} au {glucose} et à la {préparation} sort du {foyer} pour une {célébration}", words: ['sucré', 'glucose', 'préparation', 'foyer', 'célébration'], reponse: 'gâteau' },

  { theme: 'force en mouvement', phrase: "Un {vétuste} moyen de {trajet} avec {convoi} à {fumée} circule sur des {voies}", words: ['vétuste', 'trajet', 'convoi', 'fumée', 'voies'], reponse: 'locomotive' },

  { theme: 'illusion de similitude', phrase: "Une {ondulation} de {grains} s'étend à l'{ligne} comme une {berge} sans {iode}", words: ['ondulation', 'grains', 'ligne', 'berge', 'iode'], reponse: 'mer' },

  { theme: 'trace humaine', phrase: "Un {ouvrage} avec {jaquette} raconte un {récit} sur plusieurs {feuillets} écrits par un {écrivain}", words: ['ouvrage', 'jaquette', 'récit', 'feuillets', 'écrivain'], reponse: 'livre' },

  { theme: 'cycle discret', phrase: "Un objet {calcule} l'{instant} et la {division} avec un {battement} visible sur un {disque}", words: ['calcule', 'instant', 'division', 'battement', 'disque'], reponse: 'horloge' },

  { theme: 'quête', phrase: "Une {esquisse} indique un {butin} rempli d'{métal} sur une {terre} avec un {magot}", words: ['esquisse', 'butin', 'métal', 'terre', 'magot'], reponse: 'pirate' },

  { theme: 'nécessité rapide', phrase: "Un {encas} avec {mie}, {chair} et {condiment} se mange avec la {paume}", words: ['encas', 'mie', 'chair', 'condiment', 'paume'], reponse: 'sandwich' },

  { theme: 'défi simulé', phrase: "Un {participant} utilise un {contrôleur} pour battre un {ennemi} dans un {palier} à l'{affichage}", words: ['participant', 'contrôleur', 'ennemi', 'palier', 'affichage'], reponse: 'jeu vidéo' },

  { theme: 'ralentissement', phrase: "Sur une {cime}, un {cristal} {pâle} tombe avec la {gelée} et le {givre}", words: ['cime', 'cristal', 'pâle', 'gelée', 'givre'], reponse: 'hiver' },

  { theme: 'équilibre vital', phrase: "Un élément {chlorophyllien} avec {fronde}, {tronc} et {ancrage} produit de l'{air}", words: ['chlorophyllien', 'fronde', 'tronc', 'ancrage', 'air'], reponse: 'arbre' },

  { theme: 'navigation abstraite', phrase: "Un {explorateur} de {requête} permet une {pression} vers une {interface} du {maillage}", words: ['explorateur', 'requête', 'pression', 'interface', 'maillage'], reponse: 'navigateur' },

  { theme: 'immensité', phrase: "Dans la {pénombre}, une {lueur} d'{astre} brille dans la vaste {nébuleuse} {sans fin}", words: ['pénombre', 'lueur', 'astre', 'nébuleuse', 'sans fin'], reponse: 'univers' },

  { theme: 'patience', phrase: "Un {brin} de {fibres} sur une {tige} crée un {assemblage} en {boucle}", words: ['brin', 'fibres', 'tige', 'assemblage', 'boucle'], reponse: 'tricot' },

  { theme: 'transformation', phrase: "Un {assemblage} de {grains} {chauffé} donne une {croûte} et une {mie}", words: ['assemblage', 'grains', 'chauffé', 'croûte', 'mie'], reponse: 'pain' },

  { theme: 'verticalité', phrase: "Une {structure} de {pierre} {élevée} domine la {ville} avec des {étages}", words: ['structure', 'pierre', 'élevée', 'ville', 'étages'], reponse: 'tour' },

  { theme: 'flux continu', phrase: "Une {masse} d'{eau} en {mouvement} suit un {lit} jusqu'à la {mer}", words: ['masse', 'eau', 'mouvement', 'lit', 'mer'], reponse: 'rivière' },

  { theme: 'contenu fermé', phrase: "Un {récipient} avec {couvercle} garde un {liquide} à l'abri de l'{air}", words: ['récipient', 'couvercle', 'liquide', 'air'], reponse: 'bouteille' },

  { theme: 'projection', phrase: "Un {dispositif} diffuse une {image} sur un {mur} dans une {salle}", words: ['dispositif', 'image', 'mur', 'salle'], reponse: 'projecteur' },

  { theme: 'repère', phrase: "Un {signe} indique une {direction} sur une {route} pour les {voyageurs}", words: ['signe', 'direction', 'route', 'voyageurs'], reponse: 'panneau' },

  { theme: 'équilibre fragile', phrase: "Une {surface} {plane} repose sur {pieds} et supporte des {objets}", words: ['surface', 'plane', 'pieds', 'objets'], reponse: 'table' },

  { theme: 'empreinte', phrase: "Une {marque} laissée par un {pas} sur le {sol} humide", words: ['marque', 'pas', 'sol'], reponse: 'trace' },

  { theme: 'répétition', phrase: "Un {cycle} de {jours} forme une {unité} de {temps}", words: ['cycle', 'jours', 'unité', 'temps'], reponse: 'semaine' },

  { theme: 'énergie contenue', phrase: "Un {élément} {chargé} fournit du {courant} à un {appareil}", words: ['élément', 'chargé', 'courant', 'appareil'], reponse: 'batterie' },

  { theme: 'reflet', phrase: "Une {surface} {polie} renvoie une {image} fidèle du {visage}", words: ['surface', 'polie', 'image', 'visage'], reponse: 'miroir' },

  { theme: 'fragment', phrase: "Un {morceau} de {verre} {tranchant} issu d'une {cassure}", words: ['morceau', 'verre', 'tranchant', 'cassure'], reponse: 'éclat' },

  { theme: 'liaison', phrase: "Un {objet} {souple} relie deux {points} sous {tension}", words: ['objet', 'souple', 'points', 'tension'], reponse: 'corde' },

  { theme: 'passage', phrase: "Un {espace} étroit permet le {franchissement} entre deux {lieux}", words: ['espace', 'franchissement', 'lieux'], reponse: 'couloir' },

  { theme: 'capture', phrase: "Un {outil} {adhésif} retient un {élément} par {contact}", words: ['outil', 'adhésif', 'élément', 'contact'], reponse: 'colle' },

  { theme: 'division', phrase: "Un {instrument} coupe une {matière} en plusieurs {parties}", words: ['instrument', 'matière', 'parties'], reponse: 'couteau' },

  { theme: 'signal faible', phrase: "Un {son} bref attire l'attention dans le {silence}", words: ['son', 'attention', 'silence'], reponse: 'bip' },

  { theme: 'support', phrase: "Une {planche} {fixée} au {mur} accueille des {objets}", words: ['planche', 'fixée', 'mur', 'objets'], reponse: 'étagère' },

  { theme: 'protection', phrase: "Un {revêtement} {épais} isole du {froid} et du {vent}", words: ['revêtement', 'épais', 'froid', 'vent'], reponse: 'manteau' },

  { theme: 'élévation', phrase: "Un {dispositif} permet de monter d''un {niveau} à un autre sans {effort}", words: ['dispositif', 'niveau', 'effort'], reponse: 'ascenseur' },

  { theme: 'contrainte', phrase: "Un {lien} {rigide} maintient un {objet} en {place}", words: ['lien', 'rigide', 'objet', 'place'], reponse: 'clou' },

  { theme: 'oscillation', phrase: "Un {mouvement} {régulier} alterne entre deux {positions}", words: ['mouvement', 'régulier', 'positions'], reponse: 'balancement' },

  { theme: 'ouverture', phrase: "Une {partie} mobile permet l'{entrée} dans un {espace}", words: ['partie', 'entrée', 'espace'], reponse: 'porte' },

  { theme: 'filtration', phrase: "Un {dispositif} sépare le {solide} du {liquide}", words: ['dispositif', 'solide', 'liquide'], reponse: 'filtre' },

  { theme: 'projection mentale', phrase: "Une {représentation} interne guide une {action} future", words: ['représentation', 'action'], reponse: 'idée' },

  { theme: 'réserve', phrase: "Un {espace} contient des {ressources} pour un usage {ultérieur}", words: ['espace', 'ressources', 'ultérieur'], reponse: 'stock' },

  { theme: 'pression', phrase: "Un {gaz} comprimé dans un {volume} exerce une {force}", words: ['gaz', 'volume', 'force'], reponse: 'air' },

  { theme: 'guidage', phrase: "Un {tracé} indique un {chemin} à suivre sur une {surface}", words: ['tracé', 'chemin', 'surface'], reponse: 'ligne' },

  { theme: 'diffusion', phrase: "Une {substance} se répand dans un {milieu} jusqu'à {uniformité}", words: ['substance', 'milieu', 'uniformité'], reponse: 'odeur' },

  { theme: 'résistance', phrase: "Un {matériau} oppose une {force} à une {déformation}", words: ['matériau', 'force', 'déformation'], reponse: 'solidité' },

  { theme: 'accumulation', phrase: "Un {amas} de {particules} forme une {surface} instable", words: ['amas', 'particules', 'surface'], reponse: 'tas' },

  { theme: 'vitesse', phrase: "Un {déplacement} rapide couvre une {distance} en peu de {temps}", words: ['déplacement', 'distance', 'temps'], reponse: 'course' },

  { theme: 'rotation', phrase: "Un {objet} tourne autour d'un {axe} de manière {continue}", words: ['objet', 'axe', 'continue'], reponse: 'roue' },

  { theme: 'chaleur', phrase: "Une {source} produit de la {température} par {combustion}", words: ['source', 'température', 'combustion'], reponse: 'feu' },

  { theme: 'contact', phrase: "Deux {surfaces} se touchent en un {point} commun", words: ['surfaces', 'point'], reponse: 'contact' },

  { theme: 'séparation', phrase: "Une {barrière} divise un {espace} en deux {zones}", words: ['barrière', 'espace', 'zones'], reponse: 'mur' },

  { theme: 'retour', phrase: "Un {chemin} mène à son {point} de {départ}", words: ['chemin', 'point', 'départ'], reponse: 'boucle' },

  { theme: 'résonance', phrase: "Un {espace} amplifie un {son} par {vibration}", words: ['espace', 'son', 'vibration'], reponse: 'écho' },

  { theme: 'observation', phrase: "Un {instrument} permet de voir à {distance} avec précision", words: ['instrument', 'distance'], reponse: 'jumelles' },

  { theme: 'compression', phrase: "Un {objet} réduit son {volume} sous une {force}", words: ['objet', 'volume', 'force'], reponse: 'ressort' },

  { theme: 'distribution', phrase: "Un {réseau} répartit une {ressource} vers plusieurs {points}", words: ['réseau', 'ressource', 'points'], reponse: 'circuit' },

  { theme: 'stabilité', phrase: "Une {base} large assure l'{équilibre} d'un {objet}", words: ['base', 'équilibre', 'objet'], reponse: 'socle' },

  { theme: 'transition', phrase: "Un {moment} marque le passage d'un {état} à un autre", words: ['moment', 'état'], reponse: 'changement' },

  { theme: 'mouvement interne', phrase: "Une {force} agit à l'intérieur d'un {corps} en {action}", words: ['force', 'corps', 'action'], reponse: 'énergie' },

  { theme: 'alignement', phrase: "Plusieurs {éléments} disposés en {suite} forment une {structure}", words: ['éléments', 'suite', 'structure'], reponse: 'ligne' },

  { theme: 'acte', phrase: "Une {réaction} rapide suit un {stimulus} sans {calcul}", words: ['réaction', 'stimulus', 'calcul'], reponse: 'réflexe' },

  { theme: 'suspension', phrase: "Un {objet} reste en {l'air} sans {support} visible", words: ['objet', 'air', 'support'], reponse: 'flottement' },

  { theme: 'origine', phrase: "Un {point} marque le début d'un {processus}", words: ['point', 'processus'], reponse: 'départ' },

  { theme: 'pas plus', phrase: "Un {moment} conclut une {suite} d'{événements}", words: ['moment', 'suite', 'événements'], reponse: 'fin' },


];
// ── MANCHE 1 : Les Énigmes (phrases à trous) ────────────────
export const R1_PHRASE_SETS = [
  
  { mode:"child",theme: 'Cuisine italienne', phrase: 'Un élément {rond} de {pâte} {farci} de {légume} est souvent servi avec de la {tomate}', words: ['rond', 'pâte', 'farci', 'légume', 'tomate'], reponse: 'ravioli' },
  { mode:"child",theme: 'Phénomène météo', phrase: 'Après la {pluie} et le {soleil}, un {arc} de {couleur} apparaît dans le {ciel}', words: ['pluie', 'soleil', 'arc', 'couleur', 'ciel'], reponse: 'arc-en-ciel' },
  {mode:"child", theme: 'Vie scolaire', phrase: 'Un {enseignant} utilise une {craie} pour {écrire} sur un {tableau} en {classe}', words: ['enseignant', 'craie', 'écrire', 'tableau', 'classe'], reponse: 'école' },
  { mode:"child",theme: 'Technologie mobile', phrase: 'Un objet {portable} avec {écran} {tactile} permet un {appel} et une {application}', words: ['portable', 'écran', 'tactile', 'appel', 'application'], reponse: 'smartphone' },
  { mode:"child",theme: 'Animal sauvage', phrase: "Un {félin} {sauvage} d'{Afrique} possède des {rayures} {noir} et blanc", words: ['félin', 'sauvage', 'Afrique', 'rayures', 'noir'], reponse: 'zèbre' },
  {mode:"child", theme: 'Synonyme de politesse', phrase: 'Dans une {formule} de {politesse}, un mot {signifiant} {content} et {enchanté} est utilisé', words: ['formule', 'politesse', 'signifiant', 'content', 'enchanté'], reponse: 'ravi' },
  { mode:"child",theme: 'Pâtisserie & fête', phrase: 'Un aliment {gourmand} au {sucre} et à la {pâte} sort du {four} pour une {fête}', words: ['gourmand', 'sucre', 'pâte', 'four', 'fête'], reponse: 'gâteau' },
  { mode:"child",theme: 'Musique & harmonie', phrase: 'Une {partition} contient une {note} et un {rythme} de {son} joué par un {instrument}', words: ['partition', 'note', 'rythme', 'son', 'instrument'], reponse: 'mélodie' },
  { mode:"child",theme: 'Transport ancien', phrase: 'Un {ancien} moyen de {voyage} avec {wagon} à {vapeur} circule sur des {rails}', words: ['ancien', 'voyage', 'wagon', 'vapeur', 'rails'], reponse: 'locomotive' },
  { mode:"child",theme: 'Nature & étendue', phrase: "Une {vague} de {sable} s'étend à l'{horizon} comme une {plage} sans {sel}", words: ['vague', 'sable', 'horizon', 'plage', 'sel'], reponse: 'mer' },
  { mode:"child",theme: 'Lecture & littérature', phrase: 'Un {roman} avec {couverture} raconte une {histoire} sur plusieurs {pages} écrites par un {auteur}', words: ['roman', 'couverture', 'histoire', 'pages', 'auteur'], reponse: 'livre' },
  { mode:"child",theme: 'Mesure du temps', phrase: "Un objet {mesure} l'{heure} et la {minute} avec un {tic} visible sur un {cadran}", words: ['mesure', 'heure', 'minute', 'tic', 'cadran'], reponse: 'horloge' },
  { mode:"child",theme: 'Aventure & trésor', phrase: "Une {carte} indique un {coffre} rempli d'{or} sur une {île} avec un {trésor}", words: ['carte', 'coffre', 'or', 'île', 'trésor'], reponse: 'pirate' },
  { mode:"child",theme: 'Repas rapide', phrase: 'Un {snack} avec {pain}, {viande} et {sauce} se mange avec la {main}', words: ['snack', 'pain', 'viande', 'sauce', 'main'], reponse: 'sandwich' },
  { mode:"child",theme: 'Jeu vidéo', phrase: "Un {joueur} utilise une {manette} pour battre un {boss} dans un {niveau} à l'{écran}", words: ['joueur', 'manette', 'boss', 'niveau', 'écran'], reponse: 'jeu vidéo' },
  { mode:"child",theme: 'Saison froide', phrase: 'Sur une {montagne}, un {flocon} {blanc} tombe avec la {neige} et le {froid}', words: ['montagne', 'flocon', 'blanc', 'neige', 'froid'], reponse: 'hiver' },
  { mode:"child",theme: 'Végétal & nature', phrase: "Un élément {vert} avec {feuille}, {bois} et {racine} produit de l'{oxygène}", words: ['vert', 'feuille', 'bois', 'racine', 'oxygène'], reponse: 'arbre' },
  { mode:"child",theme: 'Internet & web', phrase: 'Un {moteur} de {recherche} permet un {clic} vers une {page} du {réseau}', words: ['moteur', 'recherche', 'clic', 'page', 'réseau'], reponse: 'navigateur' },
  { mode:"child",theme: 'Astronomie', phrase: "Dans la {nuit}, une {lumière} d'{étoile} brille dans la vaste {galaxie} {infinie}", words: ['nuit', 'lumière', 'étoile', 'galaxie', 'infinie'], reponse: 'univers' },
  { mode:"child",theme: 'Artisanat textile', phrase: 'Un {fil} de {laine} sur une {aiguille} crée un {tissu} en {maille}', words: ['fil', 'laine', 'aiguille', 'tissu', 'maille'], reponse: 'tricot' },
];
// ── MANCHE 3 : Noms propres (ensembles thèmes) ──────────────
export const R3_SETS = [
  { theme: 'Pays du monde', words: ['FRANCE','ESPAGNE','ITALIE','ALLEMAGNE','JAPON','BRÉSIL','CANADA','MEXIQUE','CHINE','RUSSIE','AUSTRALIE','INDE','ÉGYPTE','MAROC','ARGENTINE'] },
  { theme: 'Célébrités françaises', words: ['HUGO','VOLTAIRE','MOLIÈRE','NAPOLÉON','BAUDELAIRE','ZOLA','FLAUBERT','RIMBAUD','VERLAINE','CAMUS','SARTRE','DE GAULLE','PICASSO','MONET','PROUST'] },
  { theme: 'Personnages historiques', words: ['CLÉOPÂTRE','CHARLEMAGNE','COLOMB','EINSTEIN','SHAKESPEARE','DARWIN','GALILÉE','DE VINCI','MOZART','BEETHOVEN','NEWTON','PLATON','SOCRATE','MAGELLAN','PASTEUR'] },
  { theme: 'Villes françaises', words: ['PARIS','LYON','MARSEILLE','BORDEAUX','TOULOUSE','NANTES','NICE','STRASBOURG','MONTPELLIER','RENNES','ROUEN','LILLE','GRENOBLE','DIJON','REIMS'] },
  { theme: 'Pays d\'Afrique', words: ['SÉNÉGAL','MALI','CAMEROUN','CÔTE D\'IVOIRE','TUNISIE','ALGÉRIE','NIGERIA','KENYA','GHANA','ÉTHIOPIE','TANZANIE','MADAGASCAR','MOZAMBIQUE','ANGOLA','ZAMBIE'] },

  { theme: 'Capitales du monde', words: ['PARIS','ROME','MADRID','BERLIN','TOKYO','OTTAWA','BRASILIA','PEKIN','MOSCOU','LONDRES','DUBLIN','VIENNE','PRAGUE','ATHENES','OSLO'] },
  { theme: 'Présidents américains', words: ['WASHINGTON','LINCOLN','ROOSEVELT','KENNEDY','NIXON','REAGAN','CLINTON','BUSH','OBAMA','TRUMP','BIDEN','JEFFERSON','MADISON','MONROE','GRANT'] },
  { theme: 'Écrivains célèbres', words: ['HUGO','ZOLA','ORWELL','TOLSTOI','DOSTOIEVSKI','KAFKA','HEMINGWAY','JOYCE','PROUST','CAMUS','SARTRE','BALZAC','VERNE','TWAIN','AUSTEN'] },
  { theme: 'Peintres célèbres', words: ['MONET','MANET','RENOIR','PICASSO','VAN GOGH','DALI','MICHEL-ANGE','RAPHAEL','REMBRANDT','CEZANNE','GAUGUIN','MATISSE','KANDINSKY','POLLOCK','WARHOL'] },
  { theme: 'Philosophes', words: ['PLATON','SOCRATE','ARISTOTE','DESCARTES','KANT','NIETZSCHE','ROUSSEAU','VOLTAIRE','HEGEL','MARX','SPINOZA','LOCKE','HOBBES','FOUCAULT','DERRIDA'] },

  { theme: 'Acteurs hollywoodiens', words: ['DICAPRIO','PITT','CRUISE','HANKS','DEPP','SMITH','FREEMAN','WASHINGTON','CLOONEY','DAMON','WAHLBERG','JACKMAN','BALE','PHOENIX','REEVES'] },
  { theme: 'Chanteurs internationaux', words: ['MJ','MADONNA','BEYONCE','RIHANNA','DRAKE','EMINEM','ADELE','STING','PRINCE','ELVIS','SINATRA','SHAKIRA','BIEBER','WEEKND','BRUNO MARS'] },
  { theme: 'Groupes de musique', words: ['BEATLES','QUEEN','ABBA','METALLICA','NIRVANA','U2','COLDPLAY','RADIOHEAD','PINK FLOYD','ROLLING STONES','MAROON 5','LINKIN PARK','OASIS','MUSE','IMAGINE DRAGONS'] },
  { theme: 'Marques automobiles', words: ['RENAULT','PEUGEOT','CITROEN','BMW','AUDI','MERCEDES','TESLA','TOYOTA','HONDA','FORD','FERRARI','LAMBORGHINI','VOLKSWAGEN','HYUNDAI','KIA'] },
  { theme: 'Entreprises tech', words: ['APPLE','GOOGLE','MICROSOFT','AMAZON','META','NETFLIX','TESLA','INTEL','IBM','ORACLE','SAMSUNG','SONY','UBER','AIRBNB','SPOTIFY'] },

  { theme: 'Clubs de football', words: ['PSG','OM','OL','BARCELONE','REAL MADRID','LIVERPOOL','CHELSEA','ARSENAL','BAYERN','DORTMUND','JUVENTUS','MILAN','INTER','AJAX','PORTO'] },
  { theme: 'Joueurs de football', words: ['MBAPPE','MESSI','RONALDO','NEYMAR','ZIDANE','BENZEMA','HAALAND','MODRIC','KANE','SALAH','DE BRUYNE','GRIEZMANN','POGBA','RONALDINHO','IBRAHIMOVIC'] },
  { theme: 'Films célèbres', words: ['TITANIC','AVATAR','GLADIATOR','INCEPTION','MATRIX','ALIEN','ROCKY','JOKER','AMELIE','INTOUCHABLES','FROZEN','COCO','BATMAN','SUPERMAN','SPIDERMAN'] },
  { theme: 'Personnages fictifs', words: ['HARRY POTTER','SUPERMAN','BATMAN','SPIDERMAN','HULK','IRON MAN','SHERLOCK','VADER','YODA','FRODO','GANDALF','ELSA','SIMBA','POKEMON','MARIO'] },
  { theme: 'YouTubeurs / Streamers', words: ['SQUEEZIE','CYPRIEN','MISTER V','AMIXEM','GMK','INOXTAG','MICHOU','LOCKLEAR','GOTAGA','ZERATOR','MRBEAST','MC FLY ET CARLITO'] },
];
// ── MANCHE 4 : Contre-la-montre (sets thématiques) ──────────
export const R4_SETS = [
  { theme: 'Animaux de la ferme', words: ['VACHE','COCHON','CHEVAL','MOUTON','POULE','LAPIN','ANE'] },
  { theme: 'Instruments de musique', words: ['PIANO','GUITARE','VIOLON','FLUTE','TROMPETTE','BATTERIE','HARPE'] },
  { theme: 'Sports olympiques', words: ['NATATION','CYCLISME','ATHLETISME','TENNIS','FOOTBALL','BOXE','ESCRIME'] },
  { theme: 'Fruits exotiques', words: ['MANGUE','ANANAS','PAPAYE','LITCHI','GRENADE','COCO','KIWI'] },
  { theme: 'Métiers', words: ['MEDECIN','BOULANGER','PILOTE','POMPIER','PROFESSEUR','CUISINIER','ARCHITECTE'] },

  { theme: 'Légumes', words: ['CAROTTE','TOMATE','POIREAU','COURGETTE','AUBERGINE','OIGNON','POMME DE TERRE'] },
  { theme: 'Couleurs', words: ['ROUGE','BLEU','VERT','JAUNE','NOIR','BLANC','ORANGE'] },
  { theme: 'Meubles', words: ['TABLE','CHAISE','CANAPE','LIT','ARMOIRE','BUREAU','ETAGERE'] },
  { theme: 'Vêtements', words: ['CHEMISE','PANTALON','VESTE','ROBE','CHAUSSURES','MANTEAU','T-SHIRT'] },
  { theme: 'Objets scolaires', words: ['STYLO','CRAYON','GOMME','REGLE','CAHIER','LIVRE','SAC'] },

  { theme: 'Parties du corps', words: ['TETE','BRAS','JAMBE','MAIN','PIED','YEUX','BOUCHE'] },
  { theme: 'Animaux marins', words: ['REQUIN','DAUPHIN','BALEINE','POULPE','CRABE','MEDUSE','RAIE'] },
  { theme: 'Oiseaux', words: ['AIGLE','MOINEAU','PIGEON','HIBOU','PERROQUET','CANARD','CYGNE'] },
  { theme: 'Boissons', words: ['EAU','JUS','SODA','CAFE','THE','LAIT','BIERE'] },
  { theme: 'Desserts', words: ['GATEAU','TARTE','GLACE','CREPE','MOUSSE','BISCUIT','BROWNIE'] },

  { theme: 'Transports', words: ['VOITURE','BUS','TRAIN','AVION','VELO','MOTO','BATEAU'] },
  { theme: 'Pays européens', words: ['FRANCE','ESPAGNE','ITALIE','ALLEMAGNE','BELGIQUE','SUISSE','PORTUGAL'] },
  { theme: 'Langues', words: ['FRANCAIS','ANGLAIS','ESPAGNOL','ITALIEN','ALLEMAND','CHINOIS','ARABE'] },
  { theme: 'Sports collectifs', words: ['FOOTBALL','BASKET','HANDBALL','RUGBY','VOLLEY','HOCKEY','BASEBALL'] },
  { theme: 'Objets électroniques', words: ['TELEPHONE','ORDINATEUR','TABLETTE','TELEVISION','CASQUE','SOURIS','CLAVIER'] },
];

// ── Finale : La Grande Pyramide (expressions) ────────────────
export const FINAL_SETS = [
  ['AVOIR LE CAFARD','CASSER LES PIEDS','IL PLEUT DES CORDES','POSER UN LAPIN','PRENDRE LA POUDRE D\'ESCAMPETTE','TOURNER EN ROND'],
  ['AVOIR LE CŒUR SUR LA MAIN','BRÛLER LES ÉTAPES','DONNER SA LANGUE AU CHAT','METTRE LES PIEDS DANS LE PLAT','NOYER LE POISSON','TOMBER DANS LES POMMES'],
  ['AVOIR D\'AUTRES CHATS À FOUETTER','CASSER DU SUCRE SUR LE DOS','ÊTRE DANS SES PETITS SOULIERS','MANGER À TOUS LES RÂTELIERS','PRENDRE LE TAUREAU PAR LES CORNES','SE JETER À L\'EAU'],
// ── Ajout massif : 70+ expressions supplémentaires ───────────
  ['ARC-EN-CIEL','POMME DE PIN','CROQUE-MONSIEUR','SALLE À MANGER','CHEF-D\'ŒUVRE','GARDE À VUE'],
  ['PRISE DE PAROLE','MISE EN SCÈNE','PLAN DE TABLE','SENS INTERDIT','LIGNE DE VIE','POINT MORT'],
  ['COUP DE BARRE','COUP DE GUEULE','COUP DE SOLEIL','COUP DE VENT','COUP DE FEU','COUP DE THÉÂTRE'],
  ['MAIN FORTE','MAIN COURANTE','MAIN LOURDE','MAIN HEUREUSE','MAIN INVISIBLE','MAIN TENDUE'],
  ['AVOIR LA TÊTE DANS LES NUAGES','AVOIR LES YEUX PLUS GROS QUE LE VENTRE','AVOIR UN POIL DANS LA MAIN','CHERCHER MIDI À QUATORZE HEURES','METTRE DE L\'EAU DANS SON VIN','REMUER CIEL ET TERRE'],
  ['JETER L\'ÉPONGE','TENIR SA LANGUE','AVOIR LE VENT EN POUPE','ALLER DROIT AU BUT','FAIRE D\'UNE PIERRE DEUX COUPS','ÊTRE AU PIED DU MUR'],
  ['PASSER L\'ÉPONGE','PRENDRE LA TÊTE','FAIRE LA SOURDE OREILLE','DONNER LE TON','CHANGER DE DISQUE','MONTER AU CRÉNEAU'],
  ['ÊTRE SUR LES NERFS','AVOIR LA DALLE','ÊTRE À CÔTÉ DE LA PLAQUE','TOMBER DE HAUT','RESTER DE MARBRE','AVOIR LE BEGUIN'],
['COUP DE FOUDRE','AMOUR INSTANTANÉ','PASSION SOUDAINE','ATTIRANCE FORTE','ÉLAN DU CŒUR','CHOC ÉMOTIONNEL'],
['FIL ROUGE','IDÉE DIRECTRICE','THÈME CENTRAL','LIGNE CONDUCTRICE','TRAME PRINCIPALE','SENS GLOBAL'],
['JEU DE RÔLE','PARTIE D\'ÉCHECS','MATCH VIDÉO','TOURNOI DE CARTES','ACTIVITÉ LUDIQUE','DIVERTISSEMENT'],
['SAC À DOS','VALISE DE VOYAGE','BESACE EN CUIR','CARTABLE SCOLAIRE','POCHETTE À MAIN','CABAS'],
['VERRE DE VIN','GOBELET EN PLASTIQUE','TASSE À CAFÉ','CHOPE DE BIÈRE','FLÛTE À CHAMPAGNE','RÉCIPIENT EN VERRE'],
['TABLE BASSE','BUREAU DE TRAVAIL','MEUBLE DE NUIT','PLAN DE CUISINE','SURFACE À MANGER','TABLE DE JEU'],
['CHASSE AU TRÉSOR','TRAQUE POLICIÈRE','RECHERCHE D\'INDICES','POURSUITE D\'ANIMAL','QUÊTE SECRÈTE','EXPÉDITION'],
['PIERRE PRÉCIEUSE','ROCHER MASSIF','GALET POLI','BLOC DE GRANIT','MINÉRAL BRUT','CRISTAL'],
['VENT DU NORD','BRISE LÉGÈRE','RAFALe VIOLENTE','COURANT D\'AIR','SOUFFLE MARIN','TEMPÊTE'],
['ROUE DE SECOURS','PNEU AVANT','ENGRENAGE MÉCANIQUE','DISQUE ROTATIF','JANTE MÉTALLIQUE','SYSTÈME DE ROULAGE'],
['FEU DE CAMP','INCENDIE VIOLENT','FLAMME VIVE','BRASIER ARDENT','SIGNAL LUMINEUX','COMBUSTION'],
['POINT DE VUE','POSITION FINALE','REPÈRE VISUEL','ZONE DE CHUTE','LIEU PRÉCIS','LOCALISATION']
];
