// This file is auto-generated by .github/scripts/sync-match3-version.mjs
// It mirrors root /version.js.
export const SITE_SEMVER = {
  major: 1,
  minor: 176,
  patch: 1,
  prerelease: '',
  buildDate: '2026-05-04T22:01:42.902Z',
};

export function getVersion() {
  const { major, minor, patch, prerelease } = SITE_SEMVER;
  const base = `${major}.${minor}.${patch}`;
  return prerelease ? `${base}-${prerelease}` : base;
}

export function getBuildDate() {
  return SITE_SEMVER.buildDate || '';
}
