/**
 * words.js — Base de données de mots pour le jeu Pyramide
 *
 * 10 catégories, 300+ mots en français.
 * Chaque partie sélectionne 15 mots au hasard pour former la pyramide.
 */

export const CATEGORIES = {
  sport:       { label: 'Sport',        emoji: '⚽' },
  cinema:      { label: 'Cinéma',       emoji: '🎬' },
  geographie:  { label: 'Géographie',   emoji: '🌍' },
  animaux:     { label: 'Animaux',      emoji: '🦁' },
  nourriture:  { label: 'Nourriture',   emoji: '🍕' },
  metiers:     { label: 'Métiers',      emoji: '👷' },
  objets:      { label: 'Objets',       emoji: '🔧' },
  musique:     { label: 'Musique',      emoji: '🎵' },
  histoire:    { label: 'Histoire',     emoji: '📜' },
  actions:     { label: 'Actions',      emoji: '🏃' },
};

const POOL = [
  // ─── Sport ────────────────────────────────────────────────────────────────────
  { word: 'Football',        cat: 'sport' },
  { word: 'Tennis',          cat: 'sport' },
  { word: 'Natation',        cat: 'sport' },
  { word: 'Cyclisme',        cat: 'sport' },
  { word: 'Basketball',      cat: 'sport' },
  { word: 'Rugby',           cat: 'sport' },
  { word: 'Ski',             cat: 'sport' },
  { word: 'Boxe',            cat: 'sport' },
  { word: 'Golf',            cat: 'sport' },
  { word: 'Volleyball',      cat: 'sport' },
  { word: 'Judo',            cat: 'sport' },
  { word: 'Athlétisme',      cat: 'sport' },
  { word: 'Handball',        cat: 'sport' },
  { word: 'Escrime',         cat: 'sport' },
  { word: 'Équitation',      cat: 'sport' },
  { word: 'Tir à l\'arc',    cat: 'sport' },
  { word: 'Aviron',          cat: 'sport' },
  { word: 'Plongée',         cat: 'sport' },
  { word: 'Escalade',        cat: 'sport' },
  { word: 'Triathlon',       cat: 'sport' },
  { word: 'Badminton',       cat: 'sport' },
  { word: 'Pétanque',        cat: 'sport' },
  { word: 'Bowling',         cat: 'sport' },
  { word: 'Curling',         cat: 'sport' },
  { word: 'Biathlon',        cat: 'sport' },
  { word: 'Kayak',           cat: 'sport' },
  { word: 'Surf',            cat: 'sport' },
  { word: 'Skateboard',      cat: 'sport' },
  { word: 'Ping-pong',       cat: 'sport' },
  { word: 'Patinage',        cat: 'sport' },

  // ─── Cinéma ───────────────────────────────────────────────────────────────────
  { word: 'Avatar',             cat: 'cinema' },
  { word: 'Titanic',            cat: 'cinema' },
  { word: 'Matrix',             cat: 'cinema' },
  { word: 'Inception',          cat: 'cinema' },
  { word: 'Interstellar',       cat: 'cinema' },
  { word: 'Le Parrain',         cat: 'cinema' },
  { word: 'Star Wars',          cat: 'cinema' },
  { word: 'Spider-Man',         cat: 'cinema' },
  { word: 'Batman',             cat: 'cinema' },
  { word: 'Superman',           cat: 'cinema' },
  { word: 'Alien',              cat: 'cinema' },
  { word: 'Jurassic Park',      cat: 'cinema' },
  { word: 'Indiana Jones',      cat: 'cinema' },
  { word: 'James Bond',         cat: 'cinema' },
  { word: 'Harry Potter',       cat: 'cinema' },
  { word: 'Astérix',            cat: 'cinema' },
  { word: 'Intouchables',       cat: 'cinema' },
  { word: 'Les Misérables',     cat: 'cinema' },
  { word: 'OSS 117',            cat: 'cinema' },
  { word: 'Le Dîner de Cons',   cat: 'cinema' },
  { word: 'La Grande Vadrouille', cat: 'cinema' },
  { word: 'Kaamelott',          cat: 'cinema' },
  { word: 'Amélie Poulain',     cat: 'cinema' },
  { word: 'Le Fabuleux Destin', cat: 'cinema' },
  { word: 'Toy Story',          cat: 'cinema' },
  { word: 'Le Roi Lion',        cat: 'cinema' },
  { word: 'Shrek',              cat: 'cinema' },
  { word: 'Frozen',             cat: 'cinema' },
  { word: 'Titanic',            cat: 'cinema' },
  { word: 'Mad Max',            cat: 'cinema' },

  // ─── Géographie ───────────────────────────────────────────────────────────────
  { word: 'Paris',         cat: 'geographie' },
  { word: 'Lyon',          cat: 'geographie' },
  { word: 'Marseille',     cat: 'geographie' },
  { word: 'Tokyo',         cat: 'geographie' },
  { word: 'New York',      cat: 'geographie' },
  { word: 'Londres',       cat: 'geographie' },
  { word: 'Rome',          cat: 'geographie' },
  { word: 'Berlin',        cat: 'geographie' },
  { word: 'Madrid',        cat: 'geographie' },
  { word: 'Barcelone',     cat: 'geographie' },
  { word: 'Sahara',        cat: 'geographie' },
  { word: 'Amazonie',      cat: 'geographie' },
  { word: 'Himalaya',      cat: 'geographie' },
  { word: 'Everest',       cat: 'geographie' },
  { word: 'Nil',           cat: 'geographie' },
  { word: 'Méditerranée',  cat: 'geographie' },
  { word: 'Pacifique',     cat: 'geographie' },
  { word: 'Atlantique',    cat: 'geographie' },
  { word: 'Arctique',      cat: 'geographie' },
  { word: 'Antarctique',   cat: 'geographie' },
  { word: 'Brésil',        cat: 'geographie' },
  { word: 'Australie',     cat: 'geographie' },
  { word: 'Canada',        cat: 'geographie' },
  { word: 'Mexique',       cat: 'geographie' },
  { word: 'Égypte',        cat: 'geographie' },
  { word: 'Maroc',         cat: 'geographie' },
  { word: 'Sénégal',       cat: 'geographie' },
  { word: 'Chine',         cat: 'geographie' },
  { word: 'Inde',          cat: 'geographie' },
  { word: 'Islande',       cat: 'geographie' },

  // ─── Animaux ──────────────────────────────────────────────────────────────────
  { word: 'Éléphant',      cat: 'animaux' },
  { word: 'Girafe',        cat: 'animaux' },
  { word: 'Crocodile',     cat: 'animaux' },
  { word: 'Pingouin',      cat: 'animaux' },
  { word: 'Koala',         cat: 'animaux' },
  { word: 'Panda',         cat: 'animaux' },
  { word: 'Tigre',         cat: 'animaux' },
  { word: 'Lion',          cat: 'animaux' },
  { word: 'Zèbre',         cat: 'animaux' },
  { word: 'Rhinocéros',    cat: 'animaux' },
  { word: 'Autruche',      cat: 'animaux' },
  { word: 'Flamant rose',  cat: 'animaux' },
  { word: 'Perroquet',     cat: 'animaux' },
  { word: 'Aigle',         cat: 'animaux' },
  { word: 'Hibou',         cat: 'animaux' },
  { word: 'Requin',        cat: 'animaux' },
  { word: 'Dauphin',       cat: 'animaux' },
  { word: 'Baleine',       cat: 'animaux' },
  { word: 'Méduse',        cat: 'animaux' },
  { word: 'Pieuvre',       cat: 'animaux' },
  { word: 'Fourmi',        cat: 'animaux' },
  { word: 'Abeille',       cat: 'animaux' },
  { word: 'Papillon',      cat: 'animaux' },
  { word: 'Coccinelle',    cat: 'animaux' },
  { word: 'Serpent',       cat: 'animaux' },
  { word: 'Lézard',        cat: 'animaux' },
  { word: 'Grenouille',    cat: 'animaux' },
  { word: 'Tortue',        cat: 'animaux' },
  { word: 'Chameau',       cat: 'animaux' },
  { word: 'Kangourou',     cat: 'animaux' },

  // ─── Nourriture ───────────────────────────────────────────────────────────────
  { word: 'Pizza',         cat: 'nourriture' },
  { word: 'Sushi',         cat: 'nourriture' },
  { word: 'Tacos',         cat: 'nourriture' },
  { word: 'Hamburger',     cat: 'nourriture' },
  { word: 'Croissant',     cat: 'nourriture' },
  { word: 'Baguette',      cat: 'nourriture' },
  { word: 'Fromage',       cat: 'nourriture' },
  { word: 'Chocolat',      cat: 'nourriture' },
  { word: 'Glace',         cat: 'nourriture' },
  { word: 'Crêpe',         cat: 'nourriture' },
  { word: 'Raclette',      cat: 'nourriture' },
  { word: 'Fondue',        cat: 'nourriture' },
  { word: 'Cassoulet',     cat: 'nourriture' },
  { word: 'Quiche',        cat: 'nourriture' },
  { word: 'Omelette',      cat: 'nourriture' },
  { word: 'Soufflé',       cat: 'nourriture' },
  { word: 'Tarte Tatin',   cat: 'nourriture' },
  { word: 'Madeleine',     cat: 'nourriture' },
  { word: 'Éclair',        cat: 'nourriture' },
  { word: 'Spaghetti',     cat: 'nourriture' },
  { word: 'Risotto',       cat: 'nourriture' },
  { word: 'Paella',        cat: 'nourriture' },
  { word: 'Ramen',         cat: 'nourriture' },
  { word: 'Brownie',       cat: 'nourriture' },
  { word: 'Tiramisu',      cat: 'nourriture' },
  { word: 'Macarons',      cat: 'nourriture' },
  { word: 'Millefeuille',  cat: 'nourriture' },
  { word: 'Choucroute',    cat: 'nourriture' },
  { word: 'Foie gras',     cat: 'nourriture' },
  { word: 'Crème brûlée',  cat: 'nourriture' },

  // ─── Métiers ──────────────────────────────────────────────────────────────────
  { word: 'Médecin',         cat: 'metiers' },
  { word: 'Boulanger',       cat: 'metiers' },
  { word: 'Pompier',         cat: 'metiers' },
  { word: 'Policier',        cat: 'metiers' },
  { word: 'Enseignant',      cat: 'metiers' },
  { word: 'Architecte',      cat: 'metiers' },
  { word: 'Ingénieur',       cat: 'metiers' },
  { word: 'Plombier',        cat: 'metiers' },
  { word: 'Électricien',     cat: 'metiers' },
  { word: 'Maçon',           cat: 'metiers' },
  { word: 'Infirmier',       cat: 'metiers' },
  { word: 'Pharmacien',      cat: 'metiers' },
  { word: 'Dentiste',        cat: 'metiers' },
  { word: 'Vétérinaire',     cat: 'metiers' },
  { word: 'Chirurgien',      cat: 'metiers' },
  { word: 'Avocat',          cat: 'metiers' },
  { word: 'Juge',            cat: 'metiers' },
  { word: 'Comptable',       cat: 'metiers' },
  { word: 'Chef cuisinier',  cat: 'metiers' },
  { word: 'Pâtissier',       cat: 'metiers' },
  { word: 'Boucher',         cat: 'metiers' },
  { word: 'Pilote',          cat: 'metiers' },
  { word: 'Astronaute',      cat: 'metiers' },
  { word: 'Marin',           cat: 'metiers' },
  { word: 'Militaire',       cat: 'metiers' },
  { word: 'Acteur',          cat: 'metiers' },
  { word: 'Chanteur',        cat: 'metiers' },
  { word: 'Journaliste',     cat: 'metiers' },
  { word: 'Photographe',     cat: 'metiers' },
  { word: 'Agriculteur',     cat: 'metiers' },

  // ─── Objets ───────────────────────────────────────────────────────────────────
  { word: 'Téléphone',     cat: 'objets' },
  { word: 'Voiture',       cat: 'objets' },
  { word: 'Vélo',          cat: 'objets' },
  { word: 'Avion',         cat: 'objets' },
  { word: 'Bateau',        cat: 'objets' },
  { word: 'Télévision',    cat: 'objets' },
  { word: 'Ordinateur',    cat: 'objets' },
  { word: 'Montre',        cat: 'objets' },
  { word: 'Lunettes',      cat: 'objets' },
  { word: 'Parapluie',     cat: 'objets' },
  { word: 'Valise',        cat: 'objets' },
  { word: 'Marteau',       cat: 'objets' },
  { word: 'Tournevis',     cat: 'objets' },
  { word: 'Ciseau',        cat: 'objets' },
  { word: 'Scie',          cat: 'objets' },
  { word: 'Perceuse',      cat: 'objets' },
  { word: 'Frigo',         cat: 'objets' },
  { word: 'Micro-ondes',   cat: 'objets' },
  { word: 'Cafetière',     cat: 'objets' },
  { word: 'Grille-pain',   cat: 'objets' },
  { word: 'Lampe',         cat: 'objets' },
  { word: 'Miroir',        cat: 'objets' },
  { word: 'Tabouret',      cat: 'objets' },
  { word: 'Aspirateur',    cat: 'objets' },
  { word: 'Fer à repasser', cat: 'objets' },
  { word: 'Lave-linge',    cat: 'objets' },
  { word: 'Bougie',        cat: 'objets' },
  { word: 'Calculatrice',  cat: 'objets' },
  { word: 'Thermomètre',   cat: 'objets' },
  { word: 'Loupe',         cat: 'objets' },

  // ─── Musique ──────────────────────────────────────────────────────────────────
  { word: 'Beatles',          cat: 'musique' },
  { word: 'Mozart',           cat: 'musique' },
  { word: 'Beethoven',        cat: 'musique' },
  { word: 'Elvis',            cat: 'musique' },
  { word: 'Michael Jackson',  cat: 'musique' },
  { word: 'Madonna',          cat: 'musique' },
  { word: 'David Bowie',      cat: 'musique' },
  { word: 'Prince',           cat: 'musique' },
  { word: 'Bob Marley',       cat: 'musique' },
  { word: 'Freddie Mercury',  cat: 'musique' },
  { word: 'Édith Piaf',       cat: 'musique' },
  { word: 'Jacques Brel',     cat: 'musique' },
  { word: 'Serge Gainsbourg', cat: 'musique' },
  { word: 'Charles Aznavour', cat: 'musique' },
  { word: 'Dalida',           cat: 'musique' },
  { word: 'Johnny Hallyday',  cat: 'musique' },
  { word: 'Daft Punk',        cat: 'musique' },
  { word: 'Stromae',          cat: 'musique' },
  { word: 'Aya Nakamura',     cat: 'musique' },
  { word: 'Angèle',           cat: 'musique' },
  { word: 'Soprano',          cat: 'musique' },
  { word: 'Vianney',          cat: 'musique' },
  { word: 'Kendji Girac',     cat: 'musique' },
  { word: 'Amir',             cat: 'musique' },
  { word: 'Louane',           cat: 'musique' },
  { word: 'Maes',             cat: 'musique' },
  { word: 'Nekfeu',           cat: 'musique' },
  { word: 'Orelsan',          cat: 'musique' },
  { word: 'Bigflo & Oli',     cat: 'musique' },
  { word: 'Francis Cabrel',   cat: 'musique' },

  // ─── Histoire ─────────────────────────────────────────────────────────────────
  { word: 'Napoléon',              cat: 'histoire' },
  { word: 'Marie Curie',           cat: 'histoire' },
  { word: 'Einstein',              cat: 'histoire' },
  { word: 'Shakespeare',           cat: 'histoire' },
  { word: 'Picasso',               cat: 'histoire' },
  { word: 'Léonard de Vinci',      cat: 'histoire' },
  { word: 'Christophe Colomb',     cat: 'histoire' },
  { word: 'Jules César',           cat: 'histoire' },
  { word: 'Cléopâtre',             cat: 'histoire' },
  { word: 'Louis XIV',             cat: 'histoire' },
  { word: 'Victor Hugo',           cat: 'histoire' },
  { word: 'Voltaire',              cat: 'histoire' },
  { word: 'Molière',               cat: 'histoire' },
  { word: 'Jeanne d\'Arc',         cat: 'histoire' },
  { word: 'Marco Polo',            cat: 'histoire' },
  { word: 'Alexandre le Grand',    cat: 'histoire' },
  { word: 'Galilée',               cat: 'histoire' },
  { word: 'Newton',                cat: 'histoire' },
  { word: 'Darwin',                cat: 'histoire' },
  { word: 'Freud',                 cat: 'histoire' },
  { word: 'Nelson Mandela',        cat: 'histoire' },
  { word: 'Gandhi',                cat: 'histoire' },
  { word: 'Martin Luther King',    cat: 'histoire' },
  { word: 'Charles de Gaulle',     cat: 'histoire' },
  { word: 'Simone de Beauvoir',    cat: 'histoire' },
  { word: 'Louis Pasteur',         cat: 'histoire' },
  { word: 'Marie Antoinette',      cat: 'histoire' },
  { word: 'Napoléon Bonaparte',    cat: 'histoire' },
  { word: 'Abraham Lincoln',       cat: 'histoire' },
  { word: 'Winston Churchill',     cat: 'histoire' },

  // ─── Actions ──────────────────────────────────────────────────────────────────
  { word: 'Courir',        cat: 'actions' },
  { word: 'Sauter',        cat: 'actions' },
  { word: 'Nager',         cat: 'actions' },
  { word: 'Voler',         cat: 'actions' },
  { word: 'Grimper',       cat: 'actions' },
  { word: 'Danser',        cat: 'actions' },
  { word: 'Chanter',       cat: 'actions' },
  { word: 'Jouer',         cat: 'actions' },
  { word: 'Travailler',    cat: 'actions' },
  { word: 'Dormir',        cat: 'actions' },
  { word: 'Manger',        cat: 'actions' },
  { word: 'Boire',         cat: 'actions' },
  { word: 'Lire',          cat: 'actions' },
  { word: 'Écrire',        cat: 'actions' },
  { word: 'Dessiner',      cat: 'actions' },
  { word: 'Cuisiner',      cat: 'actions' },
  { word: 'Conduire',      cat: 'actions' },
  { word: 'Téléphoner',    cat: 'actions' },
  { word: 'Voyager',       cat: 'actions' },
  { word: 'Photographier', cat: 'actions' },
  { word: 'Jardiner',      cat: 'actions' },
  { word: 'Bricoler',      cat: 'actions' },
  { word: 'Pêcher',        cat: 'actions' },
  { word: 'Skier',         cat: 'actions' },
  { word: 'Surfer',        cat: 'actions' },
  { word: 'Peindre',       cat: 'actions' },
  { word: 'Tricoter',      cat: 'actions' },
  { word: 'Coudre',        cat: 'actions' },
  { word: 'Conduire',      cat: 'actions' },
  { word: 'Réparer',       cat: 'actions' },
];

/** Mélange aléatoire (Fisher-Yates) */
export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/**
 * Retourne 15 mots mélangés pour une partie.
 * Assure la diversité des catégories : max 3 mots par catégorie.
 */
export function getGameWords() {
  const byCategory = {};
  for (const w of POOL) {
    if (!byCategory[w.cat]) byCategory[w.cat] = [];
    byCategory[w.cat].push(w);
  }

  const result = [];
  const shuffledCats = shuffle(Object.keys(byCategory));

  // Pick up to 2 words per category in first pass
  for (const cat of shuffledCats) {
    const words = shuffle(byCategory[cat]);
    const pick = Math.min(2, words.length);
    result.push(...words.slice(0, pick));
  }

  // Shuffle and take 15
  return shuffle(result).slice(0, 15);
}
