// Fichier généré par sprites/build-packs.mjs — ne pas modifier à la main.
// Paquet de sprites (fichier de sprites/cn/) qui contient chaque PNJ et chaque ennemi dessiné : sert à ne charger
// que les paquets utiles à la région affichée.
export const NPC_PACK = {
    change: 'actors-a',
    change_moon: 'actors-b',
    crane_envoy: 'actors-b',
    elder_wen: 'actors-a',
    envoy_longwang: 'actors-b',
    farmer_lin: 'actors-a',
    ferryman_gu: 'actors-a',
    fisher_hai: 'actors-b',
    guide_dawa: 'actors-a',
    herbalist_xu: 'actors-a',
    hermit_lei: 'actors-a',
    hunter_wu: 'actors-b',
    merchant_ma: 'actors-a',
    miner_shan: 'actors-b',
    monk_zhen: 'actors-a',
    parley_sun2: 'actors-a',
    parley_sun3: 'actors-a',
    parley_sun5: 'actors-a',
    parley_sun6: 'actors-b',
    parley_sun8: 'actors-b',
    parley_sun9: 'actors-b',
    priestess_yan: 'actors-b',
    shepherd_zi: 'actors-b',
    smith_tie: 'actors-a',
    sun_ten: 'actors-b',
    weaver_mei: 'actors-a'
};

export const ENEMY_PACK = {
    arcane_scholar: 'enemies-1',
    bone_reaver: 'enemies-1',
    crypt_lich: 'enemies-1',
    crystal_sage: 'enemies-2',
    deep_sea_serpent: 'enemies-2',
    ember_dragon: 'enemies-2',
    ember_wolf: 'suns',
    fengmeng_1: 'actors-b',
    fengmeng_2: 'actors-b',
    fengmeng_3a: 'actors-b',
    fengmeng_3b: 'actors-b',
    fire_tiger: 'suns',
    flame_boar: 'suns',
    forest_guardian: 'enemies-1',
    frost_dragon: 'enemies-2',
    fungal_horror: 'enemies-1',
    goblin_saboteur: 'enemies-1',
    ice_witch: 'enemies-2',
    iron_gladiator: 'enemies-1',
    lava_behemoth: 'enemies-2',
    moon_priestess: 'enemies-2',
    orc_warmaster: 'enemies-2',
    plague_doctor: 'enemies-1',
    rizieres_w_toad: 'enemies-1',
    sand_colossus: 'enemies-2',
    shadow_assassin: 'enemies-1',
    storm_knight: 'enemies-1',
    storm_wyrm: 'enemies-1',
    sun_1: 'suns',
    sun_2: 'suns',
    sun_3: 'suns',
    sun_4: 'suns',
    sun_5: 'suns',
    sun_6: 'suns',
    sun_7: 'suns',
    sun_8: 'suns',
    sun_9: 'suns',
    sun_paladin: 'enemies-2',
    temple_warden: 'enemies-1',
    void_vampire: 'enemies-2',
    war_troll: 'enemies-2'
};
